- docs/agents.qmd
> Fix spacing in eval tool environment example

- CHANGELOG.md
- src/inspect_ai/model/_providers/providers.py
> bump required openai and note support for "any" in changelog

- docs/CNAME
- docs/_quarto.yml
> use custom domain

- src/inspect_ai/_view/www/src/components/ChatView.mjs
The input may be an object or array, so be sure to properly handle these.
Tool calls which have complex (e.g. object, array) inputs will not be rendered properly.
Tool calls which have complex (e.g. object, array) inputs will be rendered properly.
> Properly process complex inputs

- CHANGELOG.md
- docs/agents.qmd
- docs/extensions.qmd
- src/inspect_ai/tool/_environment/docker/docker.py
- src/inspect_ai/tool/_environment/environment.py
- src/inspect_ai/tool/_environment/local.py
- tests/test_package/inspect_package/toolenv/podman.py
> Add `cwd` argument to `ToolEnvironment.exec()`

- CHANGELOG.md
- src/inspect_ai/model/_providers/mistral.py
- src/inspect_ai/model/_providers/openai.py
- src/inspect_ai/model/_providers/together.py
- src/inspect_ai/model/_providers/util.py
> Gracefully handle tool calls that include only a single value (rather than a named dict of parameters).

- CHANGELOG.md
- pyproject.toml
- src/inspect_ai/_eval/eval.py
- src/inspect_ai/model/_model.py
> Correctly resolve default model based on CLI --model argument

- CHANGELOG.md
- docs/models.qmd
- docs/parallelism.qmd
- docs/scorers.qmd
- pyproject.toml
> additional docs on vllm server

- pyproject.toml
- src/inspect_ai/model/_providers/vllm.py
- src/inspect_ai/scorer/_metric.py
- src/inspect_ai/solver/_solver.py
- src/inspect_ai/util/_subprocess.py
- tests/model/providers/test_hf.py
- tests/model/providers/test_vllm.py
- tests/model/test_logprobs.py
- tests/model/test_num_choices.py
- tests/test_helpers/utils.py
Also only run vllm tests when vllm is installed, and only run hf tests when transformers is installed.
> remove vllm dev dependency (works only on linux)

- pyproject.toml
- src/inspect_ai/model/_providers/groq.py
- src/inspect_ai/model/_providers/providers.py
- tests/model/providers/test_groq.py
- tests/model/test_api_key.py
- tests/model/test_stop_reason.py
- tests/scorer/test_multiscorer.py
- tests/test_helpers/utils.py
This PR integrates Groq as a provider into the framework. No breaking changes - this just adds code and the tests.
> Integrate Groq

- src/inspect_ai/_view/www/App.mjs
Too high of polling frequency creates CPU contention for other user tasks.
reduce frequency
> Reduce polling frequency when loading logs

- CHANGELOG.md
- docs/scorers.qmd
> docs on stderr change

- src/inspect_ai/_eval/run.py
- src/inspect_ai/_eval/task/run.py
> handle asyncio cancellations in root coroutine (and propagate down)

- src/inspect_ai/_eval/registry.py
> improved error message for task not found

- CHANGELOG.md
- docs/models.qmd
- docs/parallelism.qmd
- src/inspect_ai/model/_providers/google.py
- tests/model/providers/test_google.py
Addresses https://github.com/UKGovernmentBEIS/inspect_ai/issues/109
> enable overriding of default safety settings for google models

- src/inspect_ai/_view/www/src/utils/Format.mjs
Our input to string function wasn’t properly deal with lists of messages, causing an error.
Our input to string function properly deals with lists of messages, not causing an error.
> Properly handle inputs which include images

- CHANGELOG.md
- examples/tool_use.py
- src/inspect_ai/_cli/eval.py
- src/inspect_ai/model/_call_tools.py
- src/inspect_ai/model/_generate_config.py
- src/inspect_ai/model/_providers/groq.py
- src/inspect_ai/model/_providers/openai.py
Make multiple tool calls in parallel. 
Parallel tool calls occur by default for OpenAI, Anthropic, Mistral, and Groq. You can disable this behaviour for OpenAI and Groq with `--parallel-tool-calls false`
> parallel tool calls

- src/inspect_ai/util/_resource.py
> handle ValueError from fsspec

- src/inspect_ai/util/_sandbox/docker/cleanup.py
> verify that project is in running projects before removal

- docs/extensions.qmd
- docs/models.qmd
- src/inspect_ai/model/_model.py
> improved docs on model_args

- docs/models.qmd
- src/inspect_ai/model/_providers/providers.py
- src/inspect_ai/model/_providers/vertex.py
- tests/model/providers/test_google.py
- tests/model/providers/test_vertex.py
- tests/test_helpers/utils.py
- tests/tools/test_tools.py
- tests/util/test_images.py
This simply adds a new provider for Google Vertex AI. This uses a different core python library to Google AI, which most people will use. Vertex is used for more mature MLOps setups, which this should help us support.
Although the core library is different (`vertexai` instead of `google.generativeai`) the interface is very similar. Consequently, this is largely a copy/paste from the `google.py` provider, with relevant parts fixed up.
Note that I refrained from DRYing up `safety_settings` in a shared utility because the types are different, but also Vertex supports `HARM_CATEGORY_UNSPECIFIED` whereas Google AI doesn't. Although minor, it seems reasonable to assume these may diverge in other ways in the future, but I'm happy to extract this to a shared util if required!
No.
> Implement provider for Google Vertex AI

- CHANGELOG.md
- docs/scorers.qmd
> tweak score reducer docs

- src/inspect_ai/_view/www/src/components/MessageContent.mjs
- src/inspect_ai/_view/www/src/samples/SampleScoreView.mjs
some questions include long unbroken strings which should be forced to wrap.
Long input strings do not wrap.
Long input strings will be forced to wrap.
> Ensure long strings wrap

- CHANGELOG.md
- src/inspect_ai/_display/rich.py
- src/inspect_ai/_eval/context.py
- src/inspect_ai/_util/logger.py
> Fix issue with rate limit reporting being per task not per eval

- src/inspect_ai/model/_providers/vertex.py
Debug logging shows when using vertex when it shouldn't (sorry, my bad!)
It does not.
No
> Fix erroneous debug logging in vertex

- CHANGELOG.md
- src/inspect_ai/tool/_tools/_web_search.py
> retry with exponential backoff for web_search google provider

- CHANGELOG.md
- docs/log-viewer.qmd
- docs/models.qmd
- docs/parallelism.qmd
- docs/scorers.qmd
- tests/tools/test_tools.py
> doc changes in preparation for v0.3.19 release

- src/inspect_ai/_view/www/App.css
- src/inspect_ai/_view/www/App.mjs
- src/inspect_ai/_view/www/src/Constants.mjs
- src/inspect_ai/_view/www/src/components/Browser.mjs
- src/inspect_ai/_view/www/src/components/FindBand.mjs
No find in vscode web views.
Enable find in vscode web views. Use ctrl/cmd + F to launch find. Press enter to search (it can't be interactively searching due to focus management issues).
> Baseline implementation of Find in VSCode

- src/inspect_ai/scorer/_reducer/reducer.py
```
╭─ gpqa (20 x 5 samples): openai/gpt-4o ───────────────────────────────────────────────────────────╮
│ epochs_reducer: ['pass_at_1', 'pass_at_2', 'pass_at_5'], max_connections:     dataset: gpqa_main │
│ 10                                                                                scorer: choice │
│                                                                                                  │
│ total time:              0:00:05                                                                 │
│ openai/gpt-4o            24,947 tokens [24,647 + 300]                                            │
│                                                                                                  │
│ accuracy[pass_at_1]: 0.48  stderr[pass_at_1]: 0.0851  accuracy[pass_at_2]: …
```
> Correct typo

- src/inspect_ai/_view/www/src/components/MessageContent.mjs
display broken image if `--no-log-images`
display file name if `--no-log-images`
> Display image name if no image is logged

- src/inspect_ai/_view/www/README.md
> Add README for inspect viewer

- docs/log-viewer.qmd
> Update docs to point to correct path

- src/inspect_ai/model/_model.py
- src/inspect_ai/model/_providers/util/__init__.py
- src/inspect_ai/model/_providers/util/chatapi.py
- src/inspect_ai/model/_providers/util/llama31.py
> correct model name splitting

- src/inspect_ai/model/_providers/util/llama31.py
- tweak system prompt based on observation of common failure modes of llama 3.1
- parse multiple tools calls as well as supplementary content
> minor improvements to llama 3.1 tool calling

- src/inspect_ai/model/_model_output.py
#240 
We can create `Logprob` objects with bytes input.
No
> Add default value to bytes

- benchmarks/mmlu.py
> fixed typo in comments

- docs/agents-api.qmd
Broken anchor
Anchor no longer broken
> Fix broken anchor

- src/inspect_ai/_view/www/App.css
- src/inspect_ai/_view/www/dist/assets/index.css
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/components/RenderedContent.mjs
- src/inspect_ai/_view/www/src/samples/transcript/EventPanel.mjs
- src/inspect_ai/_view/www/src/samples/transcript/ModelEventView.mjs
- src/inspect_ai/_view/www/src/utils/Format.mjs
- Forward vscode diff colors
- fix event indenting
- correct alignment issue in event panel heading
- format usage numbers
> Viewer/Transcript: Minor Fixes

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/usage/UsageCard.mjs
> Fix error when usage is not available.

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/components/JsonPanel.mjs
- src/inspect_ai/_view/www/src/samples/transcript/EventRow.mjs
- src/inspect_ai/_view/www/src/samples/transcript/InfoEventView.mjs
- Provide complete implementation for info events (display syntax highlighted json)
- Use correct text color for log even header text and icon
> Event View Fixes

- CHANGELOG.md
- docs/_quarto.yml
- docs/agents-api.qmd
- docs/interactivity.qmd
- src/inspect_ai/_display/_display.py
- src/inspect_ai/_display/rich.py
- src/inspect_ai/_eval/run.py
- src/inspect_ai/_eval/task/run.py
- src/inspect_ai/_eval/task/transcript.py
- src/inspect_ai/scorer/_model.py
- src/inspect_ai/util/__init__.py
- src/inspect_ai/util/_console.py
This PR introduces a mechanism for cleanly prompting for user input, temporarily clearing the task display and enabling use of varoius Rich console primitives. Example uses include:
-   Confirming consequential actions like requests made to web services
-   Prompting the model dynamically based on the trajectory of the evaluation
-   Scoring model output with human judges
Note that prompting the user is a synchronous operation that pauses other activity within the evaluation (pending model requests or subprocesses will continue to execute, but their results won't be processed until the input is complete).
You can prompt the user for input at any point in an evaluation using the `input_screen()` context manager, which clears the normal task display and provides access to a …
> input_screen() context manager for user input

- .pre-commit-config.yaml
- Makefile
- README.md
- pyproject.toml
This contains a few of improvements that I made as I was working on my first PR to inspect. I hope they seem helpful but I don't mind if you prefer to reject any/all of them.
1. The behaviour of the `ruff format` command is not consistent with the pre-commit hooks due to mismatched versions
2. It took some searching to figure out how to set up hooks and run the static analysis and tests locally
1. Pin `ruff` version and update version in `.pre-commit.config.yaml` to match 
2. Add `Makefile` with common commands: 
* `hooks` to install the hooks
* `check` to lint, format, and typecheck (I took the mypy command from the actions workflow)
* I tried to use `pre-commit check --all-files` for this command, but that ended up changing extra files. So I added the commands manually.
* `test` to run …
> Improve onboarding for new devs

- CHANGELOG.md
- src/inspect_ai/_cli/eval.py
- src/inspect_ai/_view/www/log-schema.json
- src/inspect_ai/_view/www/src/types/log.d.ts
- src/inspect_ai/model/_generate_config.py
- src/inspect_ai/model/_providers/openai.py
3 somewhat unrelated changes accumulated in one session:
1) [improved handling of parallel_tool_calls](https://github.com/UKGovernmentBEIS/inspect_ai/commit/62d027ec674bd58eaaf678c63ccb99adc6d33bc9)
2) [update schema with is_a_directory error type](https://github.com/UKGovernmentBEIS/inspect_ai/commit/bb68ebaa5f749402b8476ccedb35cbc929819cba)
3) [only enable strict mode for OpenAI tool calls when all function parameters are required](https://github.com/UKGovernmentBEIS/inspect_ai/commit/6e80a2a636b22c6f5d8dd9135a330f60a6561c9e)
> dynamic strict tool calling + misc option/types tweaks

- src/inspect_ai/_view/view.py
This behavior is identical but None reads better than sys.maxsize
No behavior change
This just fixes code lint
> Default header-only to None

- src/inspect_ai/util/_console.py
Error on Windows
No Error on Windows
> Don’t import readline on Windows

- src/inspect_ai/_view/www/App.css
- src/inspect_ai/_view/www/dist/assets/index.css
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/components/Card.mjs
- src/inspect_ai/_view/www/src/components/FindBand.mjs
- src/inspect_ai/_view/www/src/samples/transcript/ToolEventView.mjs
- src/inspect_ai/_view/www/src/samples/transcript/TranscriptView.mjs
- Find appearing below modal dialogs in vscode
- Store updated event not showing diff view in transcript
- Card / Event Panel background color too dark
- Show tool errors in transcript tool events
- Show collapse panel in transcript tool output
- Improve viewer appearance in vscode dark themes
> Fine tuning in transcript view

- evals/swe_bench/README.md
- evals/swe_bench/build_images.py
- evals/swe_bench/resources/baselines/download_baselines.sh
- evals/swe_bench/resources/tests/create_test_repos.py
I had missed off a download baselines script, which should now be added.
> Adding a script for downloading the baselines, editing the README

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/components/MessageContent.mjs
- src/inspect_ai/_view/www/src/components/Tools.mjs
- src/inspect_ai/_view/www/src/samples/transcript/state/StateEventRenderers.mjs
- src/inspect_ai/_view/www/src/samples/transcript/state/StateEventView.mjs
- Properly trim tool output
- System message is always full width
- `use_tools`will properly display summary in transcript
- tools previews in transcript will show only the tools that were changed in this state update
> Improved Transcript Rendering

- CHANGELOG.md
- src/inspect_ai/_cli/info.py
> Fix error when runningFix error when running `inspect info log-types`

- evals/gdm_capabilities/in_house_ctf/data/cmd_injection/Dockerfile
- evals/gdm_capabilities/in_house_ctf/data/idor/Dockerfile
- evals/gdm_capabilities/in_house_ctf/data/spray/Dockerfile
- evals/gdm_capabilities/in_house_ctf/data/sqli/Dockerfile
- evals/gdm_capabilities/in_house_ctf/dataset.py
- Files should not be copied into the container (they were already copied into the Dockerfile)
- Entire directory should not copied in the Dockerfile (as that leaks the solution!)
cc @XkunW
> GDM CTF file handling improvements

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/samples/transcript/EventPanel.mjs
- src/inspect_ai/_view/www/src/samples/transcript/ModelEventView.mjs
- Sometimes solver steps would appear empty - properly invalidate the pill selection state when the children change.
- Fix a grid blowout in tool rendering
- Fix a rendering issue with model API calls which would result in the model api output not being displayed
fixes #445
> Fix View Issues

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/package.json
- src/inspect_ai/_view/www/src/components/MarkdownDiv.mjs
- src/inspect_ai/_view/www/yarn.lock
This appears to be a better renderer.
fixes #442
> Convert Markdown Rendering to Use Marked JS

- evals/gaia/gaia.py
Passing the path to the compose file explicitly, so that it works even when you aren't in the task directory.
> Making gaia compose work when not in task dir

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/samples/transcript/InfoEventView.mjs
> Markdown render string in info events

- tools/vscode/CHANGELOG.md
- tools/vscode/package.json
- tools/vscode/src/providers/codelens/codelens-provider.ts
Improve task recognition for code lens (more permissive task function recognition)
Fixes #464
> Fix issue showing run/debug button for multiline functions

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/appearance/Icons.mjs
- src/inspect_ai/_view/www/src/samples/transcript/SubtaskEventView.mjs
- Title the card with ‘Fork’ prefix
- Don’t show a summary - just show the transcript for the fork
> Special case fork subtasks

- src/inspect_ai/scorer/_metric.py
- [] New features
- [] Changes to dev-tools e.g. CI config / github tooling
- [] Code refactor
> Update _metric.py: fix some typos in the docstring

- CHANGELOG.md
- docs/agents.qmd
- src/inspect_ai/util/_sandbox/context.py
- src/inspect_ai/util/_sandbox/docker/compose.py
- src/inspect_ai/util/_sandbox/docker/docker.py
Addresses https://github.com/UKGovernmentBEIS/inspect_ai/issues/495
> allow docker sandboxes configured with `x-default` to be referred to by their declared service name

- evals/gdm_capabilities/in_house_ctf/README.md
- evals/gdm_capabilities/in_house_ctf/task.py
- default max_attempts to max_messages
- remove newlines from system message
> tweaks to gdm in_house_ctf

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/components/ChatView.mjs
Duplicate tool_call_ids will result in showing mismatched responses to tool calls.
This change now makes tool calls appear with the message that preceded them (so order is important).
> Don’t depend upon tool_call_id when matching messages with tool output

- src/inspect_ai/_display/rich.py
- provide retry command for packaged tasks
- provide total number of samples in message
> improvements to task termination messages

- evals/mathematics/utils.py
Addresses https://github.com/UKGovernmentBEIS/inspect_ai/issues/580
> Escape LaTeX braces in mathematics fewshots

- src/inspect_evals/gaia/README.md
> Update plan -> solver in GAIA README

- CHANGELOG.md
- src/inspect_ai/_util/registry.py
Addresses https://github.com/UKGovernmentBEIS/inspect_ai/issues/616
> task args: don't attempt to serialise registry objects that don't have captured parameters

- CHANGELOG.md
- src/inspect_ai/_eval/task/run.py
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/log-schema.json
- src/inspect_ai/_view/www/src/samples/transcript/ScoreEventView.mjs
- src/inspect_ai/_view/www/src/types/log.d.ts
- src/inspect_ai/log/_transcript.py
Transcript now includes the target in the Score Event rendering.
> Display Target in ScoreEventView

- CHANGELOG.md
- examples/browser/browser.py
- src/inspect_ai/model/_call_tools.py
- src/inspect_ai/model/_model.py
Also fixes a transcript issue introduced by the original implementation.
> Improved implementation of disabling parallel tool calling 

- src/inspect_ai/log/_bundle.py
A divide by zero error attempting to show progress
A nice prerequisite error - it doesn't make sense to bundle an empty log dir
> Error if the log directory is empty

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/components/ExpandablePanel.mjs
- src/inspect_ai/_view/www/src/components/Tools.mjs
- src/inspect_ai/_view/www/src/samples/transcript/ToolEventView.mjs
> Show more lines in expandable panel

- docs/index.qmd
> docs: Fix missing and broken imports in homepage solver example

- docs/workflow.qmd
> docs: Fix minor typo regarding solver config (very -> vary)

- docs/solvers.qmd
> docs: Fix minor typo regarding solver config (smaple -> sample)

- src/inspect_ai/_view/www/src/utils/Json.mjs
Fixes #675
#675 
Correctly terminates the worker after each parsing attempt.
No
It's probably better practice to keep the worker around rather than creating/destroying it on every invocation. However, for the sake of brevity, I've gone with the proposed change.
> Fix memory leak in worker-based JSON parsing

- CHANGELOG.md
- src/inspect_ai/log/_transcript.py
Resolves https://github.com/UKGovernmentBEIS/inspect_ai/issues/694
> strip protocol prefix when resolving eval event content

- CHANGELOG.md
- src/inspect_ai/model/_providers/util/llama31.py
Extraneous assistant headers may appear (especially in Bedrock). This removes them.
> Remove extraneous assistant message headers

- src/inspect_ai/solver/_multiple_choice.py
- tests/solver/test_multiple_choice.py
fixes #721
In cot responses particularly, the string `answer:` could appear in the reasoning tokens, which in some cases confuses the extraction regex for determining the answer.
This fix takes a first pass using a more strict search, looking for a line which contains `answer: A`, using that as the answer if present. If no such line is present, we will use the previous search to determine the answer.
> Improve answer detection in multichoice scorer

- CHANGELOG.md
- src/inspect_ai/_eval/eval.py
Resolves https://github.com/UKGovernmentBEIS/inspect_ai/issues/729
> Support INSPECT_EVAL_MODEL_ARGS environment variable for calls to `eval()`

- CHANGELOG.md
- docs/agents.qmd
- src/inspect_ai/util/_sandbox/docker/config.py
- src/inspect_ai/util/_sandbox/docker/docker.py
- src/inspect_ai/util/_sandbox/docker/util.py
- tests/tools/test_sandbox_dockerfile.py
Resolves https://github.com/UKGovernmentBEIS/inspect_ai/issues/727
> Support Dockerfile as config path for Docker sandboxes (previously only supported compose files)

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/App.mjs
- src/inspect_ai/_view/www/src/Types.mjs
- src/inspect_ai/_view/www/src/index.js
- src/inspect_ai/_view/www/src/samples/SampleDialog.mjs
- src/inspect_ai/_view/www/src/samples/SampleDisplay.mjs
- src/inspect_ai/_view/www/src/samples/SampleList.mjs
- src/inspect_ai/_view/www/src/samples/SamplesTab.mjs
- src/inspect_ai/_view/www/src/samples/tools/SampleFilter.mjs
- src/inspect_ai/_view/www/src/samples/tools/filters.mjs
- src/inspect_ai/_view/www/src/workspace/WorkSpace.mjs
- tools/vscode/src/providers/activity-bar/log-listing/log-listing-data.ts
- tools/vscode/src/providers/logview/logview-editor.ts
Properly restore the view state when possible (when in vscode).
> Efficiently Restore Inspect View State

- tools/vscode/src/core/uri.ts
- tools/vscode/src/providers/activity-bar/log-listing/log-listing.ts
This is a fix to the issue, though I'm not sure I'd say it's the best fix. Opening so we can discuss the issue and other potential solutions (some of which I've explored and found unsuitable).
> Correctly compute log relative path on windows

- tools/vscode/CHANGELOG.md
- tools/vscode/package.json
- tools/vscode/src/providers/inspect/inspect-constants.ts
We require 0.3.43 in order for all new features to be enabled.
> Fix error with Inspect 0.3.42

- src/inspect_ai/util/_sandbox/docker/docker.py
- src/inspect_ai/util/_sandbox/self_check.py
The previous optimization of write_file #745 didn't correctly handle spaces in filenames so it was reverted
I've reintroduced it with correct handling, and also added a test
> Optimize write file (again)

- CHANGELOG.md
- src/inspect_ai/_eval/loader.py
- tests/test_eval_set.py
- tests/test_helpers/utils.py
Resolves https://github.com/UKGovernmentBEIS/inspect_ai/issues/805
> fix issue with correctly logging task_args for eval-set tasks which are interrupted

- CHANGELOG.md
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/App.mjs
- src/inspect_ai/_view/www/src/components/ExpandablePanel.mjs
- src/inspect_ai/_view/www/src/navbar/SecondaryBar.mjs
- src/inspect_ai/_view/www/src/samples/SamplesDescriptor.mjs
- src/inspect_ai/_view/www/src/sidebar/Sidebar.mjs
- src/inspect_ai/_view/www/src/workspace/WorkSpace.mjs
> Improve display of large number of config/parameters in log viewer

- CHANGELOG.md
- src/inspect_ai/model/_model_output.py
- src/inspect_ai/model/_providers/groq.py
This adds more detailed (optional!) logging metrics to the ModelUsage object, and system fingerprints and request IDs to a new ModelTracing object.
the Groq provider implementation is also updated to utilize this.
> feat: add more detailed logging metrics

- CHANGELOG.md
- src/inspect_ai/model/_providers/mistral.py
- src/inspect_ai/model/_providers/providers.py
- tests/util/test_images.py
Requires v1.2 of mistralai package.
> Mistral: Support for multi-modal models 

- src/inspect_ai/model/_providers/groq.py
Groq only supports text queries
Groq now also supports images!!
> feat: add image support to groq

- CHANGELOG.md
- src/inspect_ai/model/_call_tools.py
- src/inspect_ai/model/_providers/google.py
- src/inspect_ai/model/_providers/vertex.py
- src/inspect_ai/tool/_tools/_execute.py
> gemini: combine consecutive tool messages into single content part; ensure no empty text content parts

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/samples/SampleDisplay.mjs
Fixes padding on single samples.
> Fix single sample display padding

- CHANGELOG.md
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/samples/SampleDisplay.mjs
- src/inspect_ai/_view/www/src/samples/SampleList.mjs
- src/inspect_ai/_view/www/src/samples/SamplesDescriptor.mjs
> Display sample ids rather than sample numbers

- src/inspect_ai/log/_file.py
- src/inspect_ai/util/_sandbox/docker/compose.py
> don't use thread pool executor for read_eval_log_headers

- CHANGELOG.md
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/log-schema.json
- src/inspect_ai/_view/www/src/samples/SampleList.mjs
- src/inspect_ai/_view/www/src/types/log.d.ts
- src/inspect_ai/model/_call_tools.py
- src/inspect_ai/tool/_tool_call.py
- tools/vscode/src/@types/log.d.ts
This enable custom tool input viewers for the message view.
> Use view in message tool rendering

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/navbar/Navbar.mjs
- src/inspect_ai/_view/www/src/navbar/SecondaryBar.mjs
- src/inspect_ai/_view/www/src/usage/UsageCard.mjs
- src/inspect_ai/_view/www/src/utils/Format.mjs
- src/inspect_ai/_view/www/src/workspace/WorkSpace.mjs
> Add Task duration to the secondary nav bar

- docs/parallelism.qmd
- [] Bug fixes
Typos fixed. No behavior changes.
No.
> Fix typos in parallelism.qmd

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/samples/transcript/ModelEventView.mjs
This fixes an unreported (as of yet) issue where multiple renders of the transcript could differ in the model call output as the inputs were reversed back and forth.
> Don’t mutate the event inputs

- CHANGELOG.md
- src/inspect_ai/_view/server.py
- src/inspect_ai/log/_file.py
s3fs can deadlock when run from multiple threads
> don't do eval log listing on background threads

- src/inspect_ai/util/_sandbox/self_check.py
self_check test was hanging: adduser was expecting input and hence did not complete
It's given the comment field it wanted. I also improved the verbosity in case one of the self_check tests hangs like this in future
> Fix self_check test: adduser hanging on input

- CHANGELOG.md
- src/inspect_ai/solver/_task_state.py
- tests/test_sample_limits.py
Has the current total tokens used across all calls to `generate()` (same value that is used for enforcing token limits).
> Add `token_usage` property to `TaskState`

- src/inspect_ai/tool/_tools/_execute.py
* Fix typo python tool description
> Fix typo in python tool description

- docs/workflow.qmd
- fixed typo in import statement
> import typo in workflow.qmd

- docs/solvers.qmd
> Fixed minor typo

- CHANGELOG.md
- src/inspect_ai/solver/_basic_agent.py
* Update basic agent to make max output configurable
* Update basic agent to set state.completed = True when successfully submitting
> Add max_output and state.completed = True to basic_agent

- CHANGELOG.md
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/samples/SampleDisplay.mjs
> Properly display sample id in single sample view

- CHANGELOG.md
- src/inspect_ai/model/_providers/bedrock.py
additionalProperties must be excluded
> Fix Nova tool calling

- CHANGELOG.md
- src/inspect_ai/_display/core/progress.py
- src/inspect_ai/_display/core/results.py
- src/inspect_ai/_display/textual/widgets/tasks.py
Coordinate the task display to ensure that progress bars align even when there are differing numbers of samples or metrics between tasks.
> Improve layout of task progress

- CHANGELOG.md
- src/inspect_ai/model/_providers/bedrock.py
> Add jpeg support to converse models

- CHANGELOG.md
- src/inspect_ai/_eval/registry.py
This regressed with our improved support for local modules in 0.3.42
> fix inability to define and run tasks in a notebook

- CHANGELOG.md
- src/inspect_ai/model/_providers/bedrock.py
> correct max tokens for old llamas

- docs/scorers.qmd
Regretfully submitting this to fix a typo that made me smile.
N/A
N/A
No
N/A
> Update scorers.qmd to fix typo

- CHANGELOG.md
- src/inspect_ai/_eval/task/run.py
- tests/util/sandbox/sandbox_setup_error.sh
- tests/util/sandbox/test_sandbox_setup.py
Resolves: https://github.com/UKGovernmentBEIS/inspect_ai/issues/1090
> sandboxes: setup and initialisation errors are now handled at the sample level

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/log-schema.json
- src/inspect_ai/_view/www/src/components/MessageContent.mjs
- src/inspect_ai/_view/www/src/types/log.d.ts
- tools/vscode/src/@types/log.d.ts
> Log Viewer support for playing audio/video

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/components/MessageBand.mjs
- src/inspect_ai/_view/www/src/samples/SamplesDescriptor.mjs
- Ensure errors in sample list have proper column width
- Ensure info bands have proper text color in vscode
> Minor view appearance tweaks

- CHANGELOG.md
- src/inspect_ai/scorer/__init__.py
- src/inspect_ai/scorer/_metrics/std.py
> Add deprecation warning for bootstrap std

- CHANGELOG.md
> Correct Changelog

- CHANGELOG.md
- src/inspect_ai/_cli/eval.py
- src/inspect_ai/model/_generate_config.py
- src/inspect_ai/model/_providers/google.py
- src/inspect_ai/model/_providers/providers.py
py.typed support and removal of logprobs generation options
> Google: Update to v0.8.4 of google-generativeai

- src/inspect_ai/_cli/common.py
fix issue with display plain and inspect view
> use rich w/ no color for --no-ansi

- tools/vscode/CHANGELOG.md
- tools/vscode/package.json
- tools/vscode/src/providers/inspect/inspect-eval.ts
Use the integrated terminal when debugging tasks.
> Use the integrated terminal when debugging tasks.

- CHANGELOG.md
- docs/models.qmd
- pyproject.toml
- src/inspect_ai/model/_providers/goodfire.py
- src/inspect_ai/model/_providers/providers.py
- tests/model/providers/test_goodfire.py
- tests/test_helpers/utils.py
> refinements + docs to goodfire model provider

- src/inspect_ai/model/_providers/together.py
> fix type hint to allow overriding TogetherAPI max_tokens

- src/inspect_ai/tool/beta/_computer/_resources/entrypoint/x11vnc_startup.sh
Although the mouse cursor is visible in computer tool usage logs, it is not visible when observing the computer via VNC.
The remote mouse cursor is now visible in VNC.
No.
> Enable viewing computer tool's remote mouse cursor in VNC.

- CHANGELOG.md
- src/inspect_ai/_eval/task/error.py
- src/inspect_ai/_eval/task/run.py
- tests/log/test_log_streaming.py
@dragonstyle Could you review this one carefully, both for correctness as well as to verify that this results in the UK we want in the viewer?
> log sample with error prior to raising task-ending exception

- src/inspect_ai/_view/www/dist/assets/index.css
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/components/JsonPanel.tsx
- src/inspect_ai/_view/www/src/samples/SampleDisplay.module.css
- src/inspect_ai/_view/www/src/samples/SampleDisplay.tsx
- src/inspect_ai/_view/www/src/samples/transcript/SampleInitEventView.tsx
- src/inspect_ai/_view/www/src/usage/ModelTokenTable.tsx
- src/inspect_ai/_view/www/src/usage/TokenTable.tsx
- src/inspect_ai/_view/www/src/workspace/tabs/JsonTab.module.css
- src/inspect_ai/_view/www/src/workspace/tabs/JsonTab.tsx
> Json tab should be full width, other cleanup

- CHANGELOG.md
- src/inspect_ai/util/_sandbox/docker/docker.py
- src/inspect_ai/util/_sandbox/self_check.py
- tests/tools/test_sandbox_docker_and_local.py
Copying files into the container is convoluted;
Copying files uses tee, which is simpler
See also
#121
#1034 
https://inspectcommunity.slack.com/archives/C0805HJTK8U/p1738694687834399
Depends on #1246
> Copy files with tee

- .pylintrc
- Makefile
- pyproject.toml
- src/inspect_ai/_cli/main.py
- src/inspect_ai/_cli/trace.py
- src/inspect_ai/_display/core/active.py
- src/inspect_ai/_eval/eval.py
- src/inspect_ai/_eval/evalset.py
- src/inspect_ai/_util/hash.py
- src/inspect_ai/log/_log.py
- src/inspect_ai/log/_recorders/json.py
- src/inspect_ai/model/_providers/openai_o1.py
- src/inspect_ai/tool/beta/_computer/_computer.py
- src/inspect_ai/tool/beta/_computer/_resources/tool/_x11_client.py
Our current static analysis suite fails to catch some errors such as the regression caused by #1234. Unfortunately, there is no single Python static analysis tool that has a superset of coverage. 
Added `pylint` to the project.
> Add pylint to our CI flow with a conservative set of rules. Fix some real surfaced issues and suppress a couple of false positives.

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/plan/PlanDetailView.tsx
Minor tweak to info panel appearance
> Correct inspect package info (in log viewer)

- src/inspect_ai/_view/www/App.css
- src/inspect_ai/_view/www/dist/assets/index.css
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/App.tsx
- src/inspect_ai/_view/www/src/workspace/navbar/ResultsPanel.module.css
- src/inspect_ai/_view/www/src/workspace/navbar/ResultsPanel.tsx
- src/inspect_ai/_view/www/src/workspace/sidebar/SidebarScoreView.tsx
- src/inspect_ai/_view/www/src/workspace/sidebar/SidebarScoresView.tsx
- src/inspect_ai/_view/www/src/workspace/utils.ts
Improve the overall appearance and layout of metrics in the Sidebar and Navbar. Display metric param names when possible (display the first parameter name and an ellipsis if there are more than one param).
<br/>
> Improved Metric Display

- CHANGELOG.md
- src/inspect_ai/_display/core/config.py
- src/inspect_ai/_eval/task/log.py
- src/inspect_ai/log/_log.py
Addresses https://github.com/UKGovernmentBEIS/inspect_ai/issues/1245
> write eval config defaults into log file

- tools/vscode/CHANGELOG.md
- tools/vscode/package.json
- tools/vscode/src/providers/activity-bar/log-listing/log-listing-data.ts
- tools/vscode/src/providers/activity-bar/log-listing/log-listing-server-queue.ts
> Fix `Invalid Tree Item` (vscode 0.3.53)

- tools/vscode/CHANGELOG.md
- tools/vscode/package.json
- tools/vscode/src/core/log.ts
- tools/vscode/src/extension.ts
- tools/vscode/src/providers/activity-bar/activity-bar-provider.ts
- tools/vscode/src/providers/workspace/workspace-task-provider.ts
> VSCode 0354 (startup perf debugging)

- CHANGELOG.md
- src/inspect_ai/_view/www/dist/assets/index.css
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/samples/error/FlatSampleErrorView.tsx
- src/inspect_ai/_view/www/src/workspace/navbar/StatusPanel.module.css
- src/inspect_ai/_view/www/src/workspace/navbar/StatusPanel.tsx
> Fix Sample Error Display Formatting

- tools/vscode/CHANGELOG.md
- tools/vscode/package.json
- tools/vscode/src/providers/activity-bar/log-listing/log-listing-data.ts
- tools/vscode/src/providers/activity-bar/log-listing/log-listing-server-queue.ts
Removes the log-listing activity bar display of status icons. This could be related to reports of performance problems rendering the list of logs and it does pose performance challenges in other scenarios. We'll add some version of this back in the future.
> VSCode 0.3.55

- CHANGELOG.md
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/samples/descriptor/score/ObjectScoreDescriptor.tsx
> Properly display non string, non numeric score values in dictionaries

- CHANGELOG.md
- src/inspect_ai/util/_sandbox/docker/cleanup.py
- src/inspect_ai/util/_sandbox/docker/docker.py
- src/inspect_ai/util/_sandbox/docker/util.py
> Docker: Print sample id and epoch for each container when using `--no-sandbox-cleanup`

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/samples/chat/MessageContent.tsx
- src/inspect_ai/_view/www/src/samples/chat/messages.ts
- src/inspect_ai/_view/www/src/samples/chat/tools/ToolCallView.tsx
> Correct types for reasoning

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/samples/chat/tools/ToolInput.tsx
Sometimes changing the current sample with left/right arrows produces the following error:
```
Error: Minified React error #310; visit https://react.dev/errors/310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.$
at $Error: Minified React error #310; visit https://react.dev/errors/310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
at updateWorkInProgressHook (http://127.0.0.1:7575/assets/index.js:3632:17)
at Object.updateRef [as useRef] (http://127.0.0.1:7575/assets/index.js:4086:14)
at react_production.useRef (http://127.0.0.1:7575/assets/index.js:774:39)
at http://127.0.0.1:7575/assets/index.js:21569:42
at renderWithHooks …
```
> Fix Minified React error #310 when changing samples

- CHANGELOG.md
- src/inspect_ai/_view/www/App.css
- src/inspect_ai/_view/www/dist/assets/index.css
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/components/ErrorPanel.tsx
- src/inspect_ai/_view/www/src/components/LightboxCarousel.module.css
- src/inspect_ai/_view/www/src/components/LightboxCarousel.tsx
- src/inspect_ai/_view/www/src/samples/chat/tools/ToolInput.tsx
- src/inspect_ai/_view/www/src/samples/chat/tools/ToolOutput.module.css
- src/inspect_ai/_view/www/src/samples/chat/tools/ToolOutput.tsx
- src/inspect_ai/_view/www/src/samples/transcript/state/StateEventView.tsx
- memo to prevent unneeded rendering
- constrain lightbox contents to viewport
> Fix layout issues with asciinema player

- tools/vscode/CHANGELOG.md
- tools/vscode/package.json
- tools/vscode/src/providers/logview/commands.ts
- tools/vscode/src/providers/logview/log-file-selector.ts
- tools/vscode/src/providers/logview/logview-link-provider.ts
- tools/vscode/src/providers/logview/logview-view.ts
(Shipped in VSCode 0.3.57, then improved to better reuse window context in 0.3.58)
> VSCode: Open Log Command

- docs/sandboxing.qmd
> Fix typo - sandboxing.qmd

- CHANGELOG.md
- src/inspect_ai/util/_json.py
- tests/model/test_structured_output.py
> Structured Output: Properly handle Pydantic BaseModel that contains other BaseModel definitions in its schema.

- pyproject.toml
- src/inspect_ai/_eval/run.py
- src/inspect_ai/_eval/task/run.py
- src/inspect_ai/log/_recorders/json.py
- src/inspect_ai/model/_call_tools.py
- src/inspect_ai/model/_model.py
- src/inspect_ai/model/_providers/vertex.py
There are a handful of bugs in the code where we reference an unbound variable. 
I enabled `mypy`'s support for detecting this class of bug by adding the following to `pyproject.toml`:
```toml
enable_error_code = "possibly-undefined"
```
I then went and fixed all of the extant bugs that the new warning surfaced.
> Enabled mypy to check for references to possibly unbound variables and fix uncovered bugs.

- CHANGELOG.md
- src/inspect_ai/_view/www/dist/assets/index.css
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/samples/descriptor/score/CategoricalScoreDescriptor.tsx
- src/inspect_ai/_view/www/src/samples/descriptor/score/NumericScoreDescriptor.tsx
- src/inspect_ai/_view/www/src/samples/sample-tools/SortFilter.tsx
> Correct sorting of numeric and categorical results

- examples/intervention/README.md
The example commands fail due to an incorrect path: `WARNING  No inspect tasks were found at the specified paths.`
The example commands succeed.
> fix cli instructions for intervention example

- CHANGELOG.md
- src/inspect_ai/_view/www/dist/assets/index.css
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/samples/transcript/ModelEventView.module.css
> Properly wrap model API text in the transcript

- CHANGELOG.md
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/samples/chat/tools/ToolCallView.tsx
- src/inspect_ai/_view/www/src/samples/chat/tools/ToolInput.tsx
> Don’t label non-language tool Input as a language

- docs/index.qmd
- Some typos on the Welcome page
- Typos fixed 
- No
> Fix typos on Welcome page docs

- tools/vscode/CHANGELOG.md
- tools/vscode/package.json
Add support for live log updating to the vscode extension
> Prepare release

- CHANGELOG.md
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/samples/transcript/state/StateEventView.tsx
Improve our handling of state diffing for objects containing arrays.
> Fix support for nested arrays

- CHANGELOG.md
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/samples/InlineSampleDisplay.tsx
- src/inspect_ai/_view/www/src/samples/transcript/StepEventView.tsx
- src/inspect_ai/_view/www/src/samples/transcript/TranscriptView.tsx
- src/inspect_ai/_view/www/src/samples/transcript/TranscriptVirtualListComponent.tsx
- src/inspect_ai/_view/www/src/samples/transcript/state/StateEventRenderers.tsx
- src/inspect_ai/_view/www/src/samples/transcript/state/StateEventView.tsx
> Properly render user or assistant solvers

- CHANGELOG.md
- src/inspect_ai/_eval/eval.py
- src/inspect_ai/_eval/evalset.py
Ensure that each pass runs against an entirely new task instance.
> eval-set: resolve tasks before each pass 

- src/inspect_ai/model/_call_tools.py
- src/inspect_ai/solver/_basic_agent.py
add deprecation warning back to call_tools
> use execute_tools in basic agent

- docs/scorers.qmd
> tweak grouped docs

- src/inspect_ai/tool/_tools/_think.py
> Remove dangling quote from think tool description

- tools/vscode/CHANGELOG.md
- tools/vscode/package.json
- tools/vscode/src/components/task.ts
- tools/vscode/src/core/log.ts
- tools/vscode/src/providers/inspect/inspect-commands.ts
- tools/vscode/src/providers/inspect/inspect-eval.ts
- tools/vscode/src/providers/inspect/inspect-view-server.ts
- tools/vscode/src/providers/logview/commands.ts
- Add vscode support for viewing live logs.
- Fix issue parsing complex task params
> VSCode 0.3.60 - Live Log Support + Task Params

- src/inspect_ai/log/_recorders/buffer/database.py
(Otherwise attachment strings will be displayed until the sample is completed)
> Resolve attachments when fetching sample summaries

- CHANGELOG.md
- src/inspect_ai/_display/textual/widgets/task_detail.py
> Ensure we allow mounting before we attach the grid

- CHANGELOG.md
- src/inspect_ai/agent/_react.py
- src/inspect_ai/agent/_types.py
- tests/agent/test_agent_react.py
- "continue using best judgement" like basic_agent + extra reminder to call submit() tool if appropriate.
- use  dynamic name for the submit tool.
> react agent: improve default `on_continue()` message

- src/inspect_ai/_view/www/dist/assets/index.css
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/metadata/MetaDataView.module.css
- src/inspect_ai/_view/www/src/metadata/MetaDataView.tsx
- src/inspect_ai/_view/www/src/metadata/RenderedContent.tsx
This is a fix to improve how we deal with Arrays in rendering content. Previously, we were not properly dealing with empty or arrays that contain only a single null value.
> Better deal with null metadata

- CHANGELOG.md
- docs/providers.qmd
- src/inspect_ai/model/_providers/openai.py
- src/inspect_ai/model/_providers/openai_responses.py
- src/inspect_ai/model/_providers/providers.py
- tests/model/providers/test_openai.py
Support for [flex processing](https://platform.openai.com/docs/guides/flex-processing), which provides lower inference costs in exchange for slower response times and occasional resource unavailability (added in v1.75.0, which is now required).
> openai flex processing

- CHANGELOG.md
- src/inspect_ai/_view/www/dist/assets/index.css
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/components/ExpandablePanel.tsx
- src/inspect_ai/_view/www/src/samples/chat/MessageContent.module.css
- src/inspect_ai/_view/www/src/samples/chat/MessageContent.tsx
Improve the appearance of reasoning to better differentiate it from model content.
> Improved Reasoning Display

- src/inspect_ai/_eval/loader.py
- src/inspect_ai/_eval/registry.py
- src/inspect_ai/_util/registry.py
- src/inspect_ai/approval/_policy.py
- src/inspect_ai/scorer/_metric.py
- src/inspect_ai/scorer/_scorer.py
- src/inspect_ai/solver/_plan.py
- src/inspect_ai/solver/_solver.py
- tests/util/test_registry.py
> Nicer typing for registry_create

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/app/samples/InlineSampleDisplay.tsx
- src/inspect_ai/_view/www/src/client/api/client-api.ts
> Fix error restoring to single sample views

- src/inspect_ai/_view/www/dist/assets/index.css
- src/inspect_ai/_view/www/src/app/App.css
> make code output in markdown output wrap

- src/inspect_ai/_view/www/dist/assets/index.css
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/app/samples/transcript/ModelEventView.module.css
- src/inspect_ai/_view/www/src/app/samples/transcript/TranscriptView.module.css
- src/inspect_ai/_view/www/src/app/samples/transcript/TranscriptVirtualListComponent.module.css
> Further tighten tool events over model events

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/app/samples/descriptor/score/NumericScoreDescriptor.tsx
- src/inspect_ai/_view/www/src/utils/numeric.ts
> Properly sort Nan

- src/inspect_ai/tool/_json_rpc_helpers.py
Inspect side JSON RPC client code intentionally mapped `-32602` responses to a `RuntimeError` reasoning that the tool calling code would prevent bogus calls. 
However, the Inspect side code makes best efforts to validate parameters, but it's impossible for it to know how any possible tool may validate the passed parameters.
This situation now properly raises a `ToolParsingError`.
> Map JSON-RPC code `-32602` to `ToolParsingError` rather than `RuntimeError` since the Inspect side code cannot catch all violations.

- src/inspect_tool_support/src/inspect_tool_support/_remote_tools/_web_browser/controller.py
- src/inspect_tool_support/unreleased_changes/+9f58866d.patch.md
There is no runtime impact. This change just uses a more concise and pythonic functional pattern.
> Cleaned up code that needlessly created named functions when a lambda would have been sufficient.

- docs/tasks.qmd
> Fix typo in Task Basics example

- docs/solvers.qmd
- docs/tasks.qmd
1. Current example in the docs incorrectly passes `max_attempts`
2. Built-in solvers section is misformatted
1. Current example in the docs correctly passes `attempts`
2. Improve the formatting of the built-in solvers section
No
Just improving the docs
> Improve the docs

- CHANGELOG.md
- src/inspect_ai/_util/trace.py
> Ignore OSError that occurs while rotating trace files.

- src/inspect_ai/model/_model.py
> Simplify type hinting for `.reduce` accumulator.

- CHANGELOG.md
- requirements.txt
- src/inspect_ai/tool/_mcp/_sandbox.py
> Fix MCP `server_sandbox` regression caused by SDK bump.

- CHANGELOG.md
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/app/samples/descriptor/score/NumericScoreDescriptor.tsx
- src/inspect_ai/_view/www/src/app/samples/descriptor/score/PassFailScoreDescriptor.tsx
- src/inspect_ai/_view/www/src/app/samples/sample-tools/SortFilter.tsx
- src/inspect_ai/_view/www/src/state/scoring.ts
- Skip samples with errors when computing available scorers from running evals
- Properly sort errors when sorting samples by score
> Score Sorting and Filtering Fixes

- src/inspect_ai/dataset/_dataset.py
> Remove extra line from `Sample#__init__` docstring

- CHANGELOG.md
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/app/samples/SampleDisplay.tsx
- src/inspect_ai/_view/www/src/app/samples/transcript/ErrorEventView.tsx
> Improve text wrapping in ANSI output (errors)

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/package.json
- src/inspect_ai/_view/www/yarn.lock
> update zustand tp 5.05+

- src/inspect_ai/tool/_tools/_web_search/_tavily.py
> Fix regression in Tavily provider caused by switching to Pydantic models.

- src/inspect_ai/agent/_run.py
- src/inspect_ai/util/_limit.py
I ought to have updated these as part of #1878.
> Docstring corrections (related to limits)

- CHANGELOG.md
- src/inspect_ai/model/_call_tools.py
- src/inspect_ai/util/_json.py
- tests/tools/test_call_tools.py
- tests/tools/test_tool_parse.py
Tools with `Enum` arguments cannot be used.
Tools with `Enum` arguments can be used.
No.
Also added a testcase for `Literal` arguments, which were already supported, but didn't have a direct test.
> Support Enum arguments in tools.

- CHANGELOG.md
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/app/content/MetaDataGrid.tsx
> Don’t crash when metadata contains null

- CHANGELOG.md
- src/inspect_ai/_display/textual/widgets/task_detail.py
- src/inspect_ai/_display/textual/widgets/tasks.py
- span the extra column
- switch to a static 3 column display that will properly wrap
-
> Improve Task Detail Scoring Display

- CHANGELOG.md
- src/inspect_ai/_display/core/textual.py
Fixes #1943
Mouse support is broken on some terminals, including at least ghostty. See #1943.
Mouse support works on ghostty.
> fix mouse support

- CHANGELOG.md
- src/inspect_ai/_cli/eval.py
- src/inspect_ai/_eval/eval.py
- src/inspect_ai/_eval/evalset.py
- src/inspect_ai/_eval/run.py
- src/inspect_ai/_eval/task/log.py
- src/inspect_ai/log/_recorders/eval.py
- src/inspect_ai/log/_recorders/json.py
- src/inspect_ai/log/_recorders/recorder.py
- tests/test_eval_set.py
> revert 61a7f0fbc03794b6de047f8eefabb30ebf12105c

- CHANGELOG.md
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/app/log-view/LogView.tsx
- src/inspect_ai/_view/www/src/app/routing/logNavigation.ts
- src/inspect_ai/_view/www/src/app/routing/sampleNavigation.ts
- src/inspect_ai/_view/www/src/app/samples/SampleDialog.tsx
- src/inspect_ai/_view/www/src/app/samples/SampleDisplay.tsx
- src/inspect_ai/_view/www/src/app/samples/list/SampleList.tsx
- src/inspect_ai/_view/www/src/app/samples/transcript/outline/TranscriptOutline.tsx
> Correctly update browser path when navigating samples

- CHANGELOG.md
- src/inspect_ai/_view/www/dist/assets/index.css
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/app/samples/chat/ChatMessage.module.css
- src/inspect_ai/_view/www/src/app/samples/chat/ChatMessage.tsx
Add support for displaying metadata for ChatMessages (displayed as a labeled value beneath the message).
> Display chat message metadata

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/app/samples/sample-tools/sample-filter/SampleFilter.tsx
> Add sample ID and metadata to tooltip help

- docs/agent-bridge.qmd
Docs spelling fix
Docs spelling fix
No
> Fix spelling to->so and add comma

- CHANGELOG.md
- src/inspect_ai/_eval/task/run.py
> Return inner exception from run_sample.

- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/app/log-list/grid/columns/columns.ts
> reorganize columns (model next to task)

- CHANGELOG.md
- src/inspect_ai/_eval/task/log.py
- src/inspect_ai/_util/eval_task_group.py
- src/inspect_ai/model/_providers/util/batch.py
- tests/util/test_run_in_background.py
- Fix task group handling to allow operations outside evaluation context
- Prevent crashes caused by logging accessing cleaned up database resources
- Initialize proper logging context for batch processing background tasks
> A variety of logging, and task group bug fixes.

- pyproject.toml
- src/inspect_ai/hooks/_hooks.py
> Conform to mypy breaking change.

- CHANGELOG.md
- src/inspect_ai/_view/www/dist/assets/index.js
- src/inspect_ai/_view/www/src/app/routing/url.ts
- src/inspect_ai/_view/www/src/app/samples/transcript/transform/treeify.ts
> Support linking via event ids

- CHANGELOG.md
- docs/dataframe.qmd
- docs/reference/_sidebar.yml
- docs/reference/inspect_ai.analysis.qmd
- src/inspect_ai/analysis/beta/__init__.py
- src/inspect_ai/analysis/beta/_prepare/log_viewer.py
- src/inspect_ai/analysis/beta/_prepare/operation.py
- src/inspect_ai/analysis/beta/_prepare/prepare.py
- tests/analysis/test_prepare.py
-`log_viewer()` operation to creating links to logs published with `inspect view bundle`
> analysis: `prepare()` function for standard data preparation operations

- src/inspect_ai/_view/www/src/app/samples/chat/MessageContents.tsx
> Don’t fail if messages have no content

- src/inspect_ai/_view/www/package.json
- src/inspect_ai/_view/www/yarn.lock
> Remove disused dependencies

- src/inspect_ai/analysis/beta/_prepare/model_data/anthropic.yml
- tests/dataset/test_model_info.py
> Correct Anthropic model names

- src/inspect_ai/_view/www/src/app/samples/chat/ChatViewVirtualList.tsx
> Search tool message ids when resolve message ids in url

- tests/tools/test_sandbox_dockerfile.py
> Use `mockllm` for a sandbox test.

- tests/solver/test_bridge.py
> Add missing test dependency decorator.

- src/inspect_ai/analysis/_prepare/model_data/anthropic.yml
- src/inspect_ai/analysis/_prepare/model_data/openai.yml
> GPT-5, Claude 4.1 Opus Model Info

- CHANGELOG.md
- docs/eval-logs.qmd
- docs/reference/inspect_ai.log.qmd
- requirements.txt
- src/inspect_ai/_util/error.py
- src/inspect_ai/_view/www/log-schema.json
- src/inspect_ai/_view/www/src/@types/log.d.ts
- src/inspect_ai/log/__init__.py
- src/inspect_ai/log/_file.py
- src/inspect_ai/log/_log.py
- src/inspect_ai/log/_recorders/eval.py
- src/inspect_ai/log/_recorders/json.py
- src/inspect_ai/log/_recorders/recorder.py
- tests/log/test_s3_conditional_writes.py
> s3 conditional writes

- src/inspect_ai/_view/www/dist/assets/index.css
- src/inspect_ai/_view/www/src/app/content/RecordTree.module.css
- src/inspect_ai/_view/www/src/app/content/RecordTree.tsx
- src/inspect_ai/_view/www/src/app/samples/chat/server-tools/ServerToolCall.module.css
- src/inspect_ai/_view/www/src/app/samples/chat/server-tools/ServerToolCall.tsx
- server side web search
- mcp_list_tools
- Fix background color in vs code dark mode
- Fix open ai argument rendering
> Improve web result rendering

- src/inspect_ai/_view/www/dist/assets/index.css
- src/inspect_ai/_view/www/src/app/samples/chat/server-tools/ServerToolCall.module.css
- src/inspect_ai/_view/www/src/app/samples/chat/server-tools/ServerToolCall.tsx
- src/inspect_ai/_view/www/src/components/ExpandablePanel.tsx
(allow the grid layout to pass through to the children of the exandable panel)
> Allow server tool list to be collapsible

- tests/model/test_structured_output.py
> Mark more flakiness.

- docs/extensions/extensions.yml
This extension was renamed to reflect the fact it now integrates with the W&B Models API as well as the Weave API
> docs: rename inspect_weave to inspect_wandb

- CHANGELOG.md
- src/inspect_ai/_view/www/dist/assets/index.css
- src/inspect_ai/_view/www/src/app/appearance/icons.ts
- src/inspect_ai/_view/www/src/app/samples/chat/MessageContents.tsx
- src/inspect_ai/_view/www/src/app/samples/chat/tools/ToolCallView.tsx
- src/inspect_ai/_view/www/src/app/samples/chat/tools/ToolInput.tsx
- src/inspect_ai/_view/www/src/app/samples/chat/tools/tool-input/TodoWriteInput.module.css
- src/inspect_ai/_view/www/src/app/samples/chat/tools/tool-input/TodoWriteInput.tsx
- src/inspect_ai/_view/www/src/app/samples/chat/tools/tool.ts
- src/inspect_ai/_view/www/src/app/samples/transcript/ToolEventView.tsx
currently only support TodoWrite
> Custom Tool Input Rendering

- tests/agent/test_agent_sandbox_bridge.py
- tests/tools/test_mcp_tools_remote.py
> Refine the flakiness configuration for a few tests.

- src/inspect_ai/agent/_human/install.py
human agent installation fails in k8s environments where the default tool user is not root (i.e. most METR environments)
Specify the `root` user for necessary commands to allow non-root users to complete the rest
No, should be backwards compatble
https://github.com/UKGovernmentBEIS/inspect_k8s_sandbox/pull/97
> Fix human_agent installation when default tool user is not root

- src/inspect_ai/_view/www/src/client/api/api-shared.ts
- src/inspect_ai/_view/www/src/client/api/client-api.ts
- src/inspect_ai/_view/www/src/client/api/types.ts
- src/inspect_ai/_view/www/src/components/DownloadButton.tsx
- src/inspect_ai/_view/www/src/components/DownloadPanel.tsx
> Correct type annotation

- src/inspect_ai/scorer/_metric.py
> number check for negatives

- src/inspect_ai/_cli/log.py
#2465 somehow forgot to add the option to the CLI 🤦
> Add `--resolve-attachments` to `log convert` CLI

- CHANGELOG.md
- tests/model/test_model_length.py
- tests/tools/test_tool_images.py
- tests/tools/test_tools.py
- tests/util/test_media.py
> Bump model versions for deprecated Google models in slow tests.

- CHANGELOG.md
- src/inspect_ai/model/_providers/anthropic.py
- src/inspect_ai/model/_providers/providers.py
- Also correct the claude 4 regex to properly match claude 4 versions
- This in turn requires update to the latest version of the anthropic client.
> Provide correct tool version for Claude Sonnet 4.5

- CHANGELOG.md
- src/inspect_ai/_view/www/src/app/log-list/LogsPanel.tsx
- src/inspect_ai/_view/www/src/app/log-view/LogViewContainer.tsx
- src/inspect_ai/_view/www/src/state/logsSlice.ts
> Inspect View: Fix Issue with Incorrect Log Display
