src/inspect_ai/model/_providers/hf.py

I have a multi-GPU setup and wanted to distribute a model across multiple devices (using `-M device=auto` via the CLI).
`HuggingFaceAPI` currently uses `self.device` for both the model's `device_map` arg as well as the input's `device`. This resulted in trying to send inputs to `auto`, causing an error.
Now inputs are sent to the (first) device associated with the model
No, this is backwards-compatible
I didn't open an issue since the fix was so quick, but I'm happy to do that or follow other conventions for the project.

fix(HuggingFaceAPI): send inputs to model device

---

src/inspect_ai/model/_providers/openai.py

When setting tool_choice="any" and expecting tool choice to be enforced, it is only set to auto which may cause the tool call to fail.
Using the `"required"` option of the OpenAI API to enforce calling at least one tool as described for `"any"`.
See https://platform.openai.com/docs/api-reference/chat/create#chat-create-tool_choice for reference.

Fix tool_choice="any" for OpenAI

---

src/inspect_ai/_view/www/src/samples/tools/SortFilter.mjs

When the samples have differing types of id (e.g. some samples have a numeric id, others have a string id), we shouldn’t fail with an error.
The sorting behavior may be unintuitive in this case, but we shouldn’t be failing with an error.
The log viewer fails with an error when an evaluation contains samples with ids of different types (e.g. a numeric id and and string id).
The log viewer properly displays the log. Ensure we coerce both types to strings before sorting.
No

Allow sorting by ids of differing types

---

docs/log-viewer.qmd
src/inspect_ai/_view/www/App.mjs
src/inspect_ai/_view/www/src/api/api-browser.mjs
src/inspect_ai/_view/www/src/api/api-http.mjs
src/inspect_ai/_view/www/src/api/api-shared.mjs
src/inspect_ai/_view/www/src/api/index.mjs

The viewer may now be hosted alongside deployed log files, which will be loaded individually using:
`?log_file=<path>`
So, for example, you can serve the log viewer and then display a log file using:
`http://localhost:8000/?log_file=logs/2024-07-18T09-00-04-04-00_bash_QuRMsu7hRUWrJjxe8xePLa.json`
Inspect view must be served from `inspect` or within vscode.
Inspect view may be served by http for a single file.

Hostable Viewer

---

docs/index.qmd
docs/models.qmd
pyproject.toml
src/inspect_ai/model/_generate_config.py
src/inspect_ai/model/_providers/hf.py
src/inspect_ai/model/_providers/providers.py
src/inspect_ai/model/_providers/vllm.py
src/inspect_ai/scorer/_metric.py
src/inspect_ai/solver/_solver.py
src/inspect_ai/util/_subprocess.py
tests/model/providers/test_vllm.py
tests/model/test_logprobs.py
tests/model/test_num_choices.py

This PR adds support for using vLLM to run local model inference as an alternative to the huggingface backend. The main benefit of vLLM is that it is much faster than huggingface and automatically manages GPU memory so you don't have to find the optimal batch size. Here is a small example where vLLM is 5x faster than huggingface on an A100 (for larger datasets I've found vLLM can be around 30x faster):
```bash
inspect eval examples/popularity.py --model hf/meta-llama/Meta-Llama-3-8B-Instruct -M device='cuda:0'
inspect eval examples/popularity.py --model vllm/meta-llama/Meta-Llama-3-8B-Instruct -M device=0
```
The other benefits is that it has support for some of the parameters in `GenerateConfig` that huggingface doesn't support such as `best_of`, `frequency_penalty`, `presence_penalty`, …

Add vLLM provider support

---

CHANGELOG.md
src/inspect_ai/dataset/_util.py
tests/dataset/test_dataset.py
tests/dataset/test_dataset/samples-md.csv
tests/dataset/test_dataset/samples-md.json
tests/dataset/test_dataset/samples-md.jsonl

If samples have a `metadata` field (i.e. they have been prepared specifically for Inspect) we now automatically read it (including parsing JSON if it is represented as a string). 
Resolves https://github.com/UKGovernmentBEIS/inspect_ai/issues/87

sample metadata

---

CHANGELOG.md
docs/agents.qmd
docs/datasets.qmd
examples/agents/intercode-ctf/dataset.py
examples/agents/intercode-ctf/task.py
src/inspect_ai/_eval/task/run.py
src/inspect_ai/dataset/_dataset.py
src/inspect_ai/dataset/_util.py
src/inspect_ai/tool/_environment/context.py

This PR introduces support for a new `setup` field for `Sample` objects. The `setup` field specifies a script to execute within the default tool environment after any Sample `files` are copied into the environment. The `setup` field can be either the script contents, a file path containing the script, or a base64 encoded [Data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs).
The `setup` script is by default interpreted as a bash script, however you can have it executed by another interpreter using a shebang comment. For example, this will be executed as a Python script:
``` bash
#!/usr/bin/env python3
print('hello from python')
```
The Intercode-CTF example is also updated to use the `setup` field (previously it had done its own `setup` handling using a …

sample setup script

---

benchmarks/mathematics.py
docs/_examples/mathematics.qmd
docs/examples.qmd
docs/scorers.qmd
src/inspect_ai/scorer/__init__.py
src/inspect_ai/scorer/_answer.py
src/inspect_ai/scorer/_choice.py
src/inspect_ai/scorer/_match.py
src/inspect_ai/scorer/_metrics/__init__.py
src/inspect_ai/scorer/_metrics/std.py
src/inspect_ai/scorer/_model.py
src/inspect_ai/scorer/_pattern.py
tests/scorer/test_metric.py
tests/scorer/test_multiscorer.py

We currently compute `bootstrap_std` for our scorers. 
We now compute `stderr` instead as a replacement for `bootstrap_std`. `boostrap_std` is still a supported metric when explicitly specified for a scorer. Added `std` metric as well.
Kind of? Users may be expecting to see `bootstrap_std` in their results (either JSON or viewer) and it will now be replaced by `stderr`, which we believe is a better measure.
We are able to compute the error directly using `stderr` (rather than using bootstrapping to estimate it) since the evaluation scores are means of numbers having finite variance. Using bootstrapping isn't really necessary since we can just compute it directly.

Replace `bootstrap_std` with `stderr` as default metric

---

CHANGELOG.md
docs/_sample-preservation.md
docs/extensions.qmd
src/inspect_ai/_eval/run.py
src/inspect_ai/_eval/task/run.py
src/inspect_ai/tool/_environment/context.py
src/inspect_ai/tool/_environment/docker/cleanup.py
src/inspect_ai/tool/_environment/docker/docker.py
src/inspect_ai/tool/_environment/docker/util.py
src/inspect_ai/tool/_environment/environment.py

This PR relaxes the constraint around tool environments for parallel tasks. Previously, all tasks in a parallel run needed to not only have the same working directory but also have the same tool environment. With this PR, unique tool environments are pulled out of the list of tasks and initialised and shutdown as required.
There are still a couple of issues I am running down w/ Ctrl+C cancellation, so the PR is still in draft status.

parallel tasks w/ multiple toolenvs

---

CHANGELOG.md
examples/tool_use.py
src/inspect_ai/tool/_environment/docker/docker.py

Previously we used `docker cp`, which in some cases refused to overwrite certain files (e.g. `/etc/hosts`). Using `tee` runs inside the container so has the correct privileges to write to any file in the container.

Use tee for Docker implementation of write_file

---

CHANGELOG.md
docs/models.qmd
src/inspect_ai/model/_providers/openai.py

The OpenAI provider will choose whether to make a connection to the main OpenAI service or Azure based on the presence of environment variables. If the `AZUREAI_OPENAI_API_KEY` variable is defined Azure will be used, otherwise OpenAI will be used (via the `OPENAI_API_KEY`). You can override this default behaviour using the `azure` model argument. For example:
``` bash
$ inspect eval eval.py -M azure=true  # force azure
$ inspect eval eval.py -M azure=false # force no azure
```

Add `azure` model arg for OpenAI provider to force binding (or not binding) to the Azure OpenAI back-end

---

benchmarks/gpqa.py
src/inspect_ai/util/_resource.py

- Remove unsupported `cot` argument from gpqa benchmark
- Catch `ValueError` in `resource()` function when probing to determine if the argument is a string a file path.

multiple choice fixes/cleanup

---

CHANGELOG.md
src/inspect_ai/scorer/_choice.py
tests/scorer/test_choice.py

When scoring using the choice scorer, the current implementation will raise an error when scoring if the answer isn’t present (which blows up the eval). This error condition occurred frequently when testing Llama 3 and 3.1 models.
Failing to throw will result in the sample being scored as `incorrect`, which seems like the correct behavior.

don't raise error for missing answers

---

CHANGELOG.md
docs/parallelism.qmd
src/inspect_ai/_eval/loader.py

Add `chdir` option to `@task` to opt-out of changing the working directory during task execution.

add chdir option to @task

---

src/inspect_ai/_view/www/src/utils/Format.mjs

In viewer, when duration of eval exceeds one hour, the number of days is wrong:
No.

Fix calculation of task duration in viewer

---

CHANGELOG.md
docs/_toolenv-interface.md
docs/agents.qmd
docs/extensions.qmd
docs/parallelism.qmd
docs/tools.qmd
src/inspect_ai/model/_call_tools.py
src/inspect_ai/tool/_environment/docker/docker.py
src/inspect_ai/tool/_environment/environment.py
src/inspect_ai/tool/_environment/local.py
src/inspect_ai/util/_subprocess.py
tests/util/test_subprocess.py

- No longer raise `ToolError` from tool environments
- Propagate `TimeoutError` up from `subprocess()` and `tool_environment().exec()`.
- Fault barrier on tool calls to catch expected exceptions (`TimeoutError`, `PermissionError`, `FileNotFoundError`, and `UnicodeDecodeErrors`).
- Improved documentation on the exception contract implemented by tool environments.

improved tool error handling

---

CHANGELOG.md
src/inspect_ai/model/_providers/anthropic.py

preserve tool_error text for anthropic tool call responses

---

src/inspect_ai/model/_providers/openai.py

If you try to run an eval with an Azure OpenAI model using a command like:
```
inspect eval benchmarks/gpqa.py@gpqa_diamond --model openai/azr-gpt-4o-latest
```
with an .env file that has the following contents
```
AZUREAI_OPENAI_BASE_URL=https://???.openai.azure.com
AZUREAI_OPENAI_API_KEY=???
OPENAI_API_VERSION=2024-02-15-preview
```
you will get the following error:
```
File "/home/ubuntu/repos/tonys-evals/inspect_ai/src/inspect_ai/model/_model.py", line 488, in get_model
modelapi_instance = modelapi_type(
^^^^^^^^^^^^^^
File "/home/ubuntu/repos/tonys-evals/inspect_ai/src/inspect_ai/model/_registry.py", line 56, in model_wrapper
model = model_type(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ubuntu/repos/tonys-evals/inspect_ai/src/inspect_ai/model/_providers/openai.py", line …
```

Fix Azure bug

---

docs/agents.qmd
examples/tool_use.py
src/inspect_ai/_view/schema.py
src/inspect_ai/_view/www/log-schema.json
src/inspect_ai/_view/www/log.d.ts
src/inspect_ai/_view/www/src/components/ChatView.mjs
src/inspect_ai/dataset/_util.py
src/inspect_ai/model/_call_tools.py
src/inspect_ai/model/_chat_message.py
src/inspect_ai/model/_providers/anthropic.py
src/inspect_ai/model/_providers/google.py
src/inspect_ai/model/_providers/mistral.py
src/inspect_ai/model/_providers/openai.py
src/inspect_ai/tool/_tool.py
src/inspect_ai/tool/_tool_call.py
src/inspect_ai/util/_sandbox/docker/docker.py

A few improvements to make error handling from tool calls more deterministic and diagnostic rich:
- Extract error conditions from stderr of Docker Compose commands and convert to requisite Python types
- Exception barrier after tool call that catches and appropriately formats error messages for consumption by the model.
- Provide error type information on `ChatMessageTool` for custom tool use loops that want to dispatch on specific error conditions.

various improvements to tool error handling

---

CHANGELOG.md
src/inspect_ai/model/_providers/openai.py

We have recently observed OpenAI returning a lot of more of these errors with source error of httpx.ConnectTimeout (which is only 5 seconds by default in the OpenAI client). This PR will treat APITimeoutError as a rate limit error (and thus retry it).

Invoke rate limit retry for OpenAI APITimeoutError

---

CHANGELOG.md
docs/log-viewer.qmd
src/inspect_ai/_display/logger.py

With this PR, uou can also arrange to have Python logger entries written to an external file. Set the `INSPECT_PY_LOGGER_FILE` environment variable to do this:
```bash
export INSPECT_PY_LOGGER_FILE=/tmp/inspect.log
```
By default, messages of level `info` and higher will be written to the log file. If you set your main `--log-level` lower than that (e.g. to `http`) then the log file will follow. To set a distinct log level for the file, set the `INSPECT_PY_LOGGER_FILE` environment variable. For example:
```bash
export INSPECT_PY_LOGGER_LEVEL=http
```

option to write Python logger entries to an external file

---

src/inspect_ai/model/_providers/anthropic.py
src/inspect_ai/tool/_tools/_execute.py

anthropic requires that content be populated when is_error is true (throws bad_request_error when not) so make sure this precondition is always met. there are two parts to this:
1) The original culprit was sandbox().exec() returning error statuses for bash/python commands with no stderr (which is entirely within expectation). This code was modified to always output a simple error message (e.g. "error executing code") in that case.
2) There is a failsafe in the anthropic handler to minimally output "error" in the case that there is no error message and no other content.

anthropic: ensure that there is always content when is_error is true

---

src/inspect_ai/_eval/run.py
src/inspect_ai/_eval/task/run.py

The work on parallel disks changed the directory from which we computed relative log locations, which in turn resulted in either absolute paths or task dir relative paths in the task display. This PR correctly offsets these paths from the eval working dir before printing them.

show eval dir relative log file paths in task output

---

src/inspect_ai/_view/www/src/samples/SamplesDescriptor.mjs

This function should’ve been there!
fixes #175
Categorical scores throw an error when rendering.
Categorical scores don't throw an error when rendering.
No

Add omitted render method for categorical scores

---

src/inspect_ai/_eval/loader.py
src/inspect_ai/_util/registry.py

Any Task created via an `@task` decorated function now has its parameters recorded (and is thus retryable). Formerly, parameterised tasks were only retryable if they had explicit task args (e.g. via `-T` or `task_args=`). 
Minimal retry example:
```python
from inspect_ai import Task, eval, eval_retry, task
from inspect_ai.dataset import example_dataset
from inspect_ai.scorer import model_graded_fact
from inspect_ai.solver import generate
@task
def security_guide(grader_model="openai/gpt-4o"):
return Task(
dataset=example_dataset("security_guide"),
plan=[generate()],
scorer=model_graded_fact(grader_model),
)
if __name__ == "__main__":
logs = eval(security_guide(grader_model="claude-3-5-sonnet-20240620"))
logs = eval_retry(logs)
```
Note that an important restriction on retryable task args …

improve recording of @task args

---

src/inspect_ai/_display/_display.py
src/inspect_ai/_display/rich.py
src/inspect_ai/_eval/task/run.py

We currently always print the eval-retry message, even for tasks that can't be retried (not from the filesystem) or tasks that have no logged samples. This PR makes the message conditional on whether the retry will actually work!

only print eval-retry message for filesystem based tasks with logged samples

---

src/inspect_ai/_view/www/log-schema.json
src/inspect_ai/_view/www/log.d.ts
src/inspect_ai/log/_log.py

Enhance the `LoggingMessage` class to include the subsystem name (e.g. "httpx"),  filename, module, line number, and additional args passed to the logging function.
All of these values have defaults so that old logs without these fields are still readable (i.e. they validate on the log file schema).

enhance python logger messages

---

CHANGELOG.md
src/inspect_ai/_view/www/src/sidebar/Sidebar.mjs
src/inspect_ai/_view/www/src/title/TitleBlock.mjs
src/inspect_ai/_view/www/src/workspace/WorkSpace.mjs

When there were multiple epoch reducers, scores could be be duplicated in the display.
Don't duplicate.

Fix multi-epoch reducer score display

---

src/inspect_ai/_util/logger.py
src/inspect_ai/tool/_tool.py

(Ironically) when inspect tries to emit a warning, the following warning is emitted:
```
.venv/lib/python3.11/site-packages/inspect_ai/tool/_tool.py:121
.venv/lib/python3.11/site-packages/inspect_ai/tool/_tool.py:121: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
logger.warn(
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
No `logging` deprecation warning emitted.
No
I believe this has been deprecated since Python 3.3 https://stackoverflow.com/a/15655674

Replace `logging.warn()` (deprecated) -> `logging.warning()`

---

src/inspect_ai/model/_providers/openai.py

we don't handle APIConnectionError error properly for openAI, if I'm not mistaken. In [anthropic.py](https://github.com/UKGovernmentBEIS/inspect_ai/blob/main/src/inspect_ai/model/_providers/anthropic.py) an APIConnectionError is treated as a rate limit error and retried, but this is not the case in openai.py where we only retry on RateLimitError and APITimeoutError.  
now `is_rate_limit` returns true for APIConnectionErrors and they should be retried.
no

add `APIConnectionError` to rate limit errors for openai

---

src/inspect_ai/model/_providers/openai.py

We don't catch and retry Openai's internal server errors afaict
now we do catch and retry them, as recommended by [OpenAI docs](https://platform.openai.com/docs/guides/error-codes/python-library-error-types) (ctrl-f InternalServerError)
no

Add InternalServerError to rate_limit / retry errors for OpenAI

---

CHANGELOG.md
src/inspect_ai/_eval/task/run.py

During an eval, the answer field of scores was not being logged. It looks like this was first introduced in the[ Feature / epoch reducer pr: ](https://github.com/UKGovernmentBEIS/inspect_ai/commit/a9ba06eb7419ba4e3d2916123fef799668747398)
Should fix https://github.com/UKGovernmentBEIS/inspect_ai/issues/208
Starts logging this again
Shouldn't do

Added the answer to be logged during evals

---

src/inspect_ai/scorer/_common.py

I found an issue with the `match()` scorer. When calling the `match_str()` function with the following inputs:
```python
target = "16"
value = "4 eggs. The answer is 16.00"
match_str(value=value, target=target, location="end", numeric=True)
```
I get `('4', False)` instead of `('16', True)`. The bug can be found in `first_number_normalized()` where any word representing a float with decimals is ignored. This function is called by `match_str()` which is called by the `match()` scorer.
`first_number_normalized(words)` ignores any string representing a float with a character "." in the `words` list. In the above example, the list is `words = ['16.00', 'is', 'answer', 'the', 'eggs', '4']`. This function returns `'4'` instead of `'16'`. 
`first_number_normalized(words)` returns the first …

Fix bug in match() scorer where float value would be ignored

---

src/inspect_ai/model/_providers/anthropic.py

Internally, Anthropic’s SDK is using `AWS_REGION` if the region isn’t explicitly passed.
- First, see if that value is set and if it is, don’t set the region (just let Anthropic do what it does).
- If that value isn’t set, see if our documented ‘AWS_DEFAULT_REGION’ is set (this is what boto3 uses and what we documented). If that is set, pass it explicitly.
- Otherwise, just use the default, which is currently `us-east-1`. Since this is the default chosen by Anthropic, I don’t think we should override it- but, just in case we think otherwise, only the Claude3 Opus model isn’t available in us-east (all others are).

Properly resolve was region for Bedrock Anthropic

---

tools/vscode/CHANGELOG.md
tools/vscode/package.json
tools/vscode/src/providers/logview/logview-webview.ts

This was fixed to support the latest bundling of inspect-ai, but I didn’t implement in a way that was compatible with older installations of inspect. this fixes that, performing in a backward compatible way by applying fixups specifically based upon what is present in the html.

Make html fixups backward compatible

---

src/inspect_ai/model/_model_output.py

When constructing a logprob without `top_logprobs` there was a schema violation error reading the log (as we had no default value for the field). This PR remedies that.

ensure logprob fields

---

src/inspect_ai/_view/www/App.css
src/inspect_ai/_view/www/dist/assets/index.css
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/dist/index.html
src/inspect_ai/_view/www/index.html
src/inspect_ai/_view/www/src/components/TabSet.mjs
src/inspect_ai/_view/www/src/navbar/Navbar.mjs

This improves the appearance of the log viewer at very narrow widths
Appearance at 500px wide:

Increase density of title block, add min-width

---

.github/workflows/log_viewer.yml
src/inspect_ai/_view/www/App.css
src/inspect_ai/_view/www/dist/assets/index.css
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/dist/index.html
src/inspect_ai/_view/www/vite.config.js

We’re currently prefixing the assets paths with `/` which means when it is deployed (for example statically) to a non-root directory, the paths fail to resolve. Setting base will result in the paths being treated as relative `./`.
Static deployment to a non-root folder fails to load assets.
Static deployment to a non-root folder successfully loads assets.

Use relative paths when generating HTML

---

benchmarks/README.md
benchmarks/drop/README.md
benchmarks/drop/drop.py
benchmarks/drop/requirements.txt

The package currently does not support the [DROP](https://arxiv.org/pdf/1903.00161) benchmark.
Implementation of the [DROP](https://arxiv.org/pdf/1903.00161) benchmark, including the implementation of a custom scorer for DROP  f1-score.
The benchmark can be run using the following command:
```python
cd benchmarks
inspect eval drop/drop.py  --model openai/gpt-4o
``` 
This implementation has been validated against the results for `Llama-3-8B-Instruct` reported in the paper [here](https://ai.meta.com/research/publications/the-llama-3-herd-of-models/). The following generations parameters were passed to reproduce the results: `--max-tokens 256 --temperature 0 --seed 42 --stop-seqs '<|eot_id|>'`
| f1-score | mean | std |
|--------|--------|--------|
| Llama-3 paper | 59.50 | 0.50 |
| Inspect | …

DROP benchmark

---

tools/vscode/src/providers/inspect/inspect-constants.ts

#246 
The correct name should be INSPECT_EVAL_MODEL_BASE_URL, not INSPECT_MODEL_BASE_URL.
No

Fix environment variable name

---

src/inspect_ai/_eval/task/generate.py
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/log-schema.json
src/inspect_ai/_view/www/src/samples/SampleTranscript.mjs
src/inspect_ai/_view/www/src/samples/transcript/StepEventView.mjs
src/inspect_ai/_view/www/src/samples/transcript/SubtaskEventView.mjs
src/inspect_ai/_view/www/src/samples/transcript/ToolEventView.mjs
src/inspect_ai/_view/www/src/samples/transcript/TranscriptView.mjs
src/inspect_ai/_view/www/src/types/log.d.ts
src/inspect_ai/model/_call_tools.py
src/inspect_ai/solver/_subtask/subtask.py
src/inspect_ai/solver/_subtask/transcript.py

This PR adds treatment for the `ToolCall` event that parallels what we do for `SubtaskEvent`, specifically:
1) `ToolEvent` now carries an `events` field that has the transcript of events that occurred within the tool call.
2) `StoreEvent` is now emitted inside this event stream if the store is updated during the tool call.
Additionally, there are two content-aliasing related changes here:
1) All content aliasing is done at the root `Sample` (previously `SubtaskEvent` had its own content bucket, no longer).
2) When resolving content aliases all changes in `StateEvent` should be handled (previously we used this conditional: `if change.path.startswith("/messages") or change.path.startswith("/output"):`, no longer)
A related question, currently `StateEvent` can duplicate changes when there …

track changes/transcript for tool calls

---

CHANGELOG.md
src/inspect_ai/util/_sandbox/docker/config.py

Specify `init` value in default Docker compose file so that exit signals are handled correctly (substantially improves container shutdown performance)

docker init for faster shutdown

---

src/inspect_ai/_eval/task/run.py
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/samples/transcript/EventPanel.mjs
src/inspect_ai/_view/www/src/samples/transcript/SampleInitEventView.mjs

File bodies are now just an empty string, so we should update the UI to show the files as a simple list of filenames.

remove file bodies from sample init event

---

src/inspect_ai/model/_providers/vllm.py

----
```python
if 0 < config.temperature > 0.02:
config.temperature = 0.02
kwargs["temperature"] = config.temperature
```
Notice the `config.temperature > 0.02` in the code. This condition sets temperature to 0.02 for any temperature greater than 0.02!
----
To reproduce an end-to-end example, place breakpoint or print statement inside the `LLM` class of vLLM:
```python
class LLM:
def generate(
self,
...
) -> List[RequestOutput]:
print("generating with temperature", sampling_params.temperature)
```
Then run this minimal example with a temperature of 5:
```python
from inspect_ai import Task, task, eval
from inspect_ai.dataset import Sample, hf_dataset
from inspect_ai.model import GenerateConfig
from inspect_ai.scorer import match
from inspect_ai.solver import generate
def …
```

Fix bug that sets all temperatures to 0.02 or less for vLLM

---

CHANGELOG.md
examples/agents/langchain/inspect_langchain.py
examples/agents/langchain/wikipedia.py
pyproject.toml
src/inspect_ai/model/_providers/hf.py
tests/model/providers/test_hf.py
tests/model/test_logprobs.py
tests/test_helpers/utils.py

Remove packages used in examples as well as transformers/accelerate from dev dependencies (these can be installed piecemeal as required).

lighten dev dependencies

---

CHANGELOG.md
docs/agents-api.qmd
docs/agents.qmd
docs/datasets.qmd
src/inspect_ai/_eval/loader.py
src/inspect_ai/_eval/run.py
src/inspect_ai/_eval/task/log.py
src/inspect_ai/_eval/task/run.py
src/inspect_ai/_eval/task/sandbox.py
src/inspect_ai/_view/www/log-schema.json
src/inspect_ai/_view/www/src/types/log.d.ts
src/inspect_ai/dataset/_dataset.py
src/inspect_ai/dataset/_sources/util.py
src/inspect_ai/dataset/_util.py
src/inspect_ai/log/_log.py
src/inspect_ai/util/_sandbox/context.py
tests/dataset/test_dataset.py
tests/dataset/test_dataset/samples.csv
tests/dataset/test_dataset/samples.json
tests/dataset/test_dataset/samples.jsonl

Sandbox environments can be now bound at the `Sample`, `Task`, or `eval()` level. Binding precedence goes from `eval()`, to `Task` to `Sample`, however sandbox config files defined on the `Sample` always take precedence when the sandbox type for the `Sample` is the same as the enclosing `Task` or `eval()`.
Here is a `Task` that defines a `sandbox` and corresponding sandbox config file:
``` python
Task(
dataset=dataset,
plan([
use_tools([read_file(), list_files()])), 
generate()
]),
scorer=match(),
sandbox=("docker", "compose.yaml")
)
```
Here is a `Sample` that specifies a custom sandbox:
```python
Sample(
...,
sandbox=("docker", "compose42.yaml")
)
```
When specified in a dataset file you can specify either a plain string or an array of [sandbox_type,config]:
```
{
..., …
```

allow sandboxes to specified at the sample level

---

docs/interactivity.qmd
src/inspect_ai/_display/_display.py
src/inspect_ai/_display/rich.py
src/inspect_ai/util/_console.py

This PR introduces a new `transient` option for the `input_screen()` context manager. Evaluations with user input alternate between asking for input and displaying task progress. By default, the normal task status display is shown when a user input screen is not active.
However, if your evaluation is dominated by user input with very short model interactions in between, the task display flashing on and off might prove distracting. For these cases, you can now specify the `transient=False` option, to indicate that the input screen should be shown at all times. For example:
``` python
with input_screen(transient=False) as console:
console.print("Some preamble text")
input = console.input("Please enter your name: ")
```
This will result in the input screen staying active throughout the …

add 'transient` option for input_screen()

---

tests/conftest.py
tests/test_helpers/utils.py

#282 
* Add `api` pytest mark and `--runapi` flag
* Update the `skip_if_no_x` decorators to use the `api` mark where appropriate
* No
* I considered adding this directly to the `skip_if_no_env_var` function, but it seems that it's not required in all cases.  We could have added a flag, but it seems more explicit to just add it directly to the functions that need it
* I manually tested this by running various tests with/without the variables and the `--runapi` flag

Add api pytest mark and --runapi flag

---

src/inspect_ai/_display/rich.py
src/inspect_ai/_util/registry.py

This PR improves the serialization of task args by detecting `Plan` objects passed and saving their registry name and params. This enables plans constructed from `@plan` decorated functions to be brought back when calling `eval_retry`.

serialize plan when its passed as a task arg

---

CHANGELOG.md
docs/parallelism.qmd
docs/workflow.qmd
src/inspect_ai/_eval/loader.py
src/inspect_ai/_eval/run.py
src/inspect_ai/_eval/score.py
src/inspect_ai/_eval/task/constants.py
src/inspect_ai/_eval/task/run.py
src/inspect_ai/_eval/task/rundir.py
src/inspect_ai/_eval/task/sandbox.py
src/inspect_ai/_eval/task/util.py
src/inspect_ai/util/_sandbox/self_check.py
tests/test_helpers/utils.py
tests/test_run_dir.py
tests/test_run_dir/task1/task1.py
tests/test_run_dir/task2/task2.py
tests/tools/test_sandbox_docker_and_local.py

This PR makes task parallelism work for tasks that live in different directories. Note that this was previously possible using `@task(chdir=False)`, however the updated implementation handles changing directories when required via patching the event loop's dispatching function (`call_soon()`). 
We have chosen to eliminate the `chdir` option entirely so that there are consistent directory semantics no matter how a task is run. The `chdir` option should therefore be removed from any tasks that use it (a warning is emitted if it is encountered).

eliminate need to use chdir=False for task parallelism

---

benchmarks/mmlu_pro/README.md
benchmarks/mmlu_pro/mmlu_pro.py

The package currently does not support the [MMLU-Pro](https://arxiv.org/pdf/2406.01574) benchmark.
Implementation of the [MMLU-Pro](https://arxiv.org/pdf/2406.01574) benchmark.
The benchmark can be run using the following command:
```python
cd benchmarks
inspect eval mmlu_pro/mmlu_pro.py  --model openai/gpt-4o
``` 
This implementation has been validated against the results for `Llama-3.1-8B-Instruct` reported in the paper [here](https://ai.meta.com/research/publications/the-llama-3-herd-of-models/) (Table 2). The following generations parameters were passed to reproduce the results: `--max-tokens 1024 --temperature 0 --seed 42 --stop-seqs '<|eot_id|>' -T fewshot=5` following [this](https://huggingface.co/datasets/meta-llama/Meta-Llama-3.1-8B-Instruct-evals/viewer/Meta-Llama-3.1-8B-Instruct …

MMLU-Pro benchmark

---

CHANGELOG.md
src/inspect_ai/_eval/evalset.py
src/inspect_ai/_util/file.py
src/inspect_ai/log/__init__.py
src/inspect_ai/log/_file.py
tests/util/test_file.py

This PR introduces a new `write_log_dir_manifest()` function, which will write a `manifest.json` file into a log directory (which in turn is a dictionary of relative log file name => log file header).
The `eval_set()` function now automatically calls this after each pass of work.

`write_log_dir_manifest()` to write log header manifests

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/appearance/Icons.mjs
src/inspect_ai/_view/www/src/components/ChatView.mjs
src/inspect_ai/_view/www/src/workspace/WorkSpace.mjs

Shows the message number next to the message in the messages view:

Display a message index in messages tab

---

src/inspect_ai/_view/view.py

The parameter is supposed to always be an int (older version of inspect do not pass it).

properly process the header only parameter

---

pyproject.toml
src/inspect_ai/_eval/evalset.py
src/inspect_ai/_util/file.py
src/inspect_ai/log/_file.py
src/inspect_ai/log/_retry.py
tests/test_eval_set.py

The attempt to write the manifest `logs.json` fails on S3 [here](https://github.com/UKGovernmentBEIS/inspect_ai/blob/main/src/inspect_ai/_util/file.py#L176) because `timestamp` is not implemented for s3fs.
The code no longer attempts to retrieve the mtime for a directory file.
`FileInfo` changes `mtime` from `float` to `float | None` which might break some people's types.
I added a mock S3 server, this should probably be documented and encouraged, since I couldn't find any other tests that use S3.

Fix eval sets on S3

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/samples/transcript/TranscriptState.mjs
src/inspect_ai/_view/www/src/samples/transcript/TranscriptView.mjs

I suspect that this is caused by a state change with `None` for a value. This results in JsonChange which has no value, which isn't value. Provide a a `null` default value in this case.

Provide a default value if an add operation is missing a value

---

benchmarks/README.md
benchmarks/mbpp/README.md
benchmarks/mbpp/mbpp.py

No implementation for MBPP.
Adds implementation for [Mostly Basic Python Problems (MBPP)](https://arxiv.org/abs/2108.07732).
No.
This implementation is on the sanitized test split, with the same 3 few-shot examples ([task IDs 2-4](https://github.com/google-research/google-research/tree/master/mbpp)) in the prompt, and uses $k=1$ code completion.
For future PRs, here are some possible extensions:
- Include variable number of few-shot examples, though this may not matter as much ([Section 4.2](https://arxiv.org/abs/2108.07732))
- Include different subsets of few-shot examples. They mentioned 15 subsets (seeds) of few-shot prompts in Section 4.3, but did not detail which examples were used in each subset
- Consider multiple code completions for a problem, e.g., $k=80$ in Sections 3 & 4, …

Add MBPP benchmark

---

src/inspect_ai/util/_sandbox/docker/docker.py
src/inspect_ai/util/_sandbox/self_check.py
tests/tools/docker-compose-context-alpine/Dockerfile
tests/tools/test_sandbox_compose_alpine.yaml
tests/tools/test_sandbox_docker_and_local.py

Per https://github.com/UKGovernmentBEIS/inspect_ai/pull/271 there are some problems running with Alpine Linux
Busybox `id` does not support GNU-style long switches like `--user` 
Bash is not installed
The docker sandbox works better with Alpine

Fixes for alpine

---

tools/vscode/CHANGELOG.md
tools/vscode/package.json

The command will appear for any json file now. When the command is executed, we verify that the file appears to be a log file.

VSCode: 0.3.30 - Less restrictive `open with` command

---

src/inspect_ai/util/_sandbox/registry.py

The `sandboxenv` decorator can mess with any classes that inherit from `SandboxEnvironment`, as it returns a `SandboxEnv` type rather than the same type that was passed in. Using generic types should fix this. 
Below is a minimal reproduction of the error (you'll need to do this in an environment with a linter or run mypy/pyright over the file):
```python
from inspect_ai.util._sandbox.environment import SandboxEnvironment
from inspect_ai.util._sandbox.registry import sandboxenv
@sandboxenv(name="mocksandbox")
class MockSandbox(SandboxEnvironment):
def specific_method(self):
pass
mock_sandbox: MockSandbox = MockSandbox()
mock_sandbox.specific_method()  
```
see example above
see example above
no

Make sandbox env use generic types

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/components/LargeModal.mjs
src/inspect_ai/_view/www/src/samples/SampleDialog.mjs
src/inspect_ai/_view/www/src/samples/SampleDisplay.mjs
src/inspect_ai/_view/www/src/samples/SamplesTab.mjs

Previously, when moving between samples using `next` and `previous`, the tab would reset. This is annoying- the tab should only reset when the dialog is dismissed and re-opened.
This required converting from using bootstrap + javascript to manage the modal to using preact state to manage the modal.

Impove Sample Tab Selection

---

docs/agents.qmd
docs/scorers.qmd

There were multiple enquires about how to access the sandbox from a scorer. It's trivial, but undocumented.
Now documented.
I also found the docs a bit ambiguous about the sandbox lifecycle so I tried to clarify it.
I am not convinced I've got the correct qmd syntax for links in this PR

Clarify scorer can access sandbox.

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/api/api-http.mjs

It needs to only return the requested files.

Correct eval_log_headers implementation

---

.gitignore
pyproject.toml
src/inspect_ai/_cli/eval.py
src/inspect_ai/_display/rich.py
src/inspect_ai/_eval/eval.py
src/inspect_ai/_eval/evalset.py
src/inspect_ai/_eval/loader.py
src/inspect_ai/_eval/run.py
src/inspect_ai/_eval/task/log.py
src/inspect_ai/_eval/task/run.py
src/inspect_ai/_util/registry.py
src/inspect_ai/_view/www/log-schema.json
src/inspect_ai/_view/www/src/types/log.d.ts
src/inspect_ai/log/_log.py
src/inspect_ai/scorer/_reducer/registry.py
src/inspect_ai/solver/__init__.py
src/inspect_ai/solver/_plan.py
src/inspect_ai/util/_sandbox/registry.py
tests/conftest.py
tests/solver/test_plan.py
tests/test_extensions.py
tests/test_helpers/utils.py
tests/test_package/inspect_package/inspect_extensions.py
tests/test_package/inspect_package/plans/cot.py
tests/util/test_registry.py

Several improvements related to providing the `plan` externally (i.e. overriding a tasks default plan):
- Inspect `eval` and `eval-set` CLI arguments for plans (`--plan` and `-P` for plan args)
- `eval-retry` now works correctly with `eval()` invoked with a `plan` override.
- Recursively serialize all registry objects (plans, solvers, tools, etc.) when saving params (improves support for retry even with registry objects in function signatures)
Also made some improvements to test scaffolding (always fully uninstall the test "inspect_package" at the end of tests)

more flexible external specifications of plan

---

src/inspect_ai/tool/__init__.py

This PR includes a minor change to expose `ToolCallError` in `inspect_ai.tool`

Exposing ToolCallError

---

CHANGELOG.md
src/inspect_ai/_eval/eval.py
src/inspect_ai/_eval/run.py
tests/test_eval.py

- Fix bug that prevented `epoch_reducer` from being used in eval-retry
- Fix bug that prevented eval() level `epoch` from overriding task level `epoch`

bug fixes for epoch handling

---

CHANGELOG.md
docs/scorers.qmd
src/inspect_ai/_eval/score.py
src/inspect_ai/_eval/task/results.py
src/inspect_ai/_eval/task/run.py
src/inspect_ai/scorer/_reducer/reducer.py
tests/scorer/test_reducers.py

We incorrectly may drop non-value score values when running the reducer. 
We don't drop the values -  we instead select the values from the first score in the reduced set. fixes #400

Preserve first score data when reducing scores

---

CHANGELOG.md
src/inspect_ai/scorer/_scorer.py
tests/scorer/test_scorer.py
tests/test_package/inspect_package/__init__.py
tests/test_package/inspect_package/score/scorer.py

We already have logic to ensure scorer names are unique, so just drop the package qualification
fixes #383

Don’t use scorer qualified name

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/App.mjs

Don't flash the no logs error message when the viewer first loads.

Only show no logs error once log_dir is initialized

---

evals/gdm_capabilities/in_house_ctf/data/cmd_injection/compose.yaml
evals/gdm_capabilities/in_house_ctf/data/db_3/compose.yaml
evals/gdm_capabilities/in_house_ctf/data/grafana/compose.yaml
evals/gdm_capabilities/in_house_ctf/data/idor/compose.yaml
evals/gdm_capabilities/in_house_ctf/data/pw_reuse/compose.yaml
evals/gdm_capabilities/in_house_ctf/data/spray/compose.yaml
evals/gdm_capabilities/in_house_ctf/data/sqli/compose.yaml
evals/gdm_capabilities/in_house_ctf/data/ssh/compose.yaml
evals/gdm_capabilities/in_house_ctf/data/webmin/compose.yaml

Some services don't have `init: true` specified.
All services don't have `init: true` specified. They will now respect signals e.g. SIGTERM/SIGINT and shutdown gracefully.

Add `init: true` to all services in GDM in-house CTF

---

evals/gaia/compose.yaml

Provide a Docker Comopse file that does not disable network access (but is otherwise the same is the default one).

gaia: enable network access

---

evals/gdm_capabilities/in_house_ctf/data/cmd_injection/compose.yaml
evals/gdm_capabilities/in_house_ctf/data/db_3/compose.yaml
evals/gdm_capabilities/in_house_ctf/data/grafana/compose.yaml
evals/gdm_capabilities/in_house_ctf/data/idor/compose.yaml
evals/gdm_capabilities/in_house_ctf/data/pw_reuse/compose.yaml
evals/gdm_capabilities/in_house_ctf/data/spray/compose.yaml
evals/gdm_capabilities/in_house_ctf/data/sqli/compose.yaml
evals/gdm_capabilities/in_house_ctf/data/ssh/compose.yaml
evals/gdm_capabilities/in_house_ctf/data/webmin/compose.yaml

Compose projects are marked as ready and the eval starts before some of the infrastructure has properly started.
See #449 
The healthchecks must succeed before `docker compose up --wait` returns. If the healthcheck never succeeds (indicating something has gone horribly wrong), the eval fails.
No
Whilst these healthchecks could be baked into the docker images instead of specified in `compose.yaml`, I think this approach will be more compatible with our k8s work. K8s ignores healthchecks in docker images, so we'll have to define `readinessProbe`s.
I've run this eval suite with `--max-messages=1` just to confirm that all compose projects do correctly start.
These healthchecks are actually quite a good basic sanity check that ports are configured properly etc.

Add healthchecks to services in GDM CTFs

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/samples/transcript/state/StateEventView.mjs

Renderers currently on pay attention to 3 ops (add, remove, replace) when rendering previews. But we would incorrectly assume that an op that appeared in a patch would be supported on renderers, so move, copy, or test would cause an error.
fixes #455

Ensure non add/copy/move ops don’t throw

---

src/inspect_ai/_eval/evalset.py
tests/test_eval_set.py
tests/test_helpers/utils.py

You get ten retries if you pass a retry count of zero
You get zero retries

eval_set does not support zero retries

---

pyproject.toml
requirements.txt
src/inspect_ai/log/_file.py
src/inspect_ai/log/_log.py
tests/log/test_eval_log.py
tests/log/test_eval_log/log_valid.txt

Right now, in header_only mode we actually will store the entire JSON object in memory, which is very slow for huge logs. On one 70MiB log in S3, it took over 3 minutes to do the header only parse. This is because the `read_field` helper used `data.keys()` which ended up reading the entire blob. 
After this change, reading the header from the same file only took 2 seconds from S3. 
To do this, I replaced json-stream with `ijson` which has better paradigms which support what I needed the parser to do. 
Should be identical but with higher performance.
No.
1. I added a new test to parse a valid header.
2. I fixed the version 3 log txt file to make it valid JSON.
3. I duplicated the EvalLog status type as I think type aliases aren't supported in the tooling we use yet. Not sure if there is a …

Fast header-only streaming log reads

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/samples/transcript/TranscriptState.mjs
src/inspect_ai/_view/www/src/samples/transcript/state/StateDiffView.mjs

Make the viewer robust against failures to apply diffs properly. Instead, display an ‘Unable to render diff’ message and log some details in the console. This will prevent state bugs from blowing up the viewer.
For discussion and a working branch as I work on improving the robustness of our state diff rendering.

Diffs don’t fail the viewer

---

evals/mmmu/utils.py

MMMU images are embedded at their native size. This causes failures with some API endpoints which have limits in terms of both pixels and bytes.
Use [Image.thumbnail](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.thumbnail) to reduce the size of images to be at most 1024 pixels on a dimension. Images which are already less than 1024 pixels on each side will not be resized.
No

MMMU: Resize images to be <= 1024 pixels per side

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/api/api-http.mjs

On some platforms, unencoded urls are not properly fetched.

Properly urlencode paths before fetching

---

CHANGELOG.md
src/inspect_ai/model/_call_tools.py

No longer required since we added automatic coercion of str to first arg and full JSON schema validation (w/ error reporting to the model) prior to tool calls.

Don't catch TypeError when calling tools (we now handle this in other ways)

---

CHANGELOG.md
src/inspect_ai/util/_subtask.py
tests/solver/test_subtask.py

regression from introduction of `fork()` in v0.3.30

fix issue w/ subtasks not getting a fresh store()

---

evals/drop/drop.py

DROP `Sample` objects do not include a passage identifier. This makes it difficult to perform analyses that specially treat questions which share a passage.
Include an MD5 hash of the passage in `Sample.metadata["passage_hash"]`.
No
Tested on a subset of the DROP dataset.

DROP: include passage_hash in sample metadata

---

CHANGELOG.md
src/inspect_ai/_cli/common.py
src/inspect_ai/_display/rich.py
src/inspect_ai/_util/platform.py

Addresses https://github.com/UKGovernmentBEIS/inspect_ai/issues/496

Option to disable ANSI terminal output with `--no-ansi` or `INSPECT_NO_ANSI`

---

CHANGELOG.md
src/inspect_ai/_eval/task/run.py
src/inspect_ai/solver/_solver.py
src/inspect_ai/solver/_transcript.py
tests/solver/test_solver_spec.py

Sample task state is used for creating state change events for steps, as well as soon for approvals. Previously we set it along with the transcript, which caught it whenever we were explicitly executing the solver (e.g. the main task solver(s), chains, and fork) however would not catch user solver executions. Now, we add a wrapper function that sets the state within the solver decorator.

Track sample task state in solver decorator rather than solver transcript

---

CHANGELOG.md
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/samples/transcript/SubtaskEventView.mjs
src/inspect_ai/solver/_fork.py
src/inspect_ai/util/_subtask.py

@dragonstyle This is the first part of addressing https://github.com/UKGovernmentBEIS/inspect_ai/issues/490. The solver params are now captured for forked subtasks -- could you add to this PR an update to the viewer that display the params?

Capture solver input params for subtasks created by `fork()`

---

CHANGELOG.md
src/inspect_ai/util/_sandbox/docker/cleanup.py
src/inspect_ai/util/_sandbox/docker/compose.py
src/inspect_ai/util/_sandbox/docker/config.py

- 60 second timeout (and warn if we hit it)
- Print complete error message for failures
- Survive docker compose files that no longer exist

improvements to docker compose down cleanup

---

CHANGELOG.md
src/inspect_ai/solver/_basic_agent.py
src/inspect_ai/solver/_task_state.py
tests/solver/test_basic_agent.py

Require a `max_messages` for use of `basic_agent()` (as without it, the agent could end up in an infinite loop).

require a `max_messages` for use of `basic_agent()`

---

evals/mathvista/mathvista.py
src/inspect_ai/_util/images.py

https://github.com/UKGovernmentBEIS/inspect_ai/issues/483
PNG images from Mathvista are now saved with the extension `.png` instead of `.jpg`.
Hopefully none, though I am not certain.
I checked that this works by running sections of the code locally - if this needs proper tests, I may need someone to point me in the right direction.

Handle Mathvista PNG images with .jpg extension

---

evals/humaneval/humaneval.py

HumanEval's `sandbox` property is not immediately configurable
Let callers to `humaneval` specify a `sandbox` argument
No

HumanEval: add sandbox parameter

---

src/inspect_ai/util/_sandbox/docker/compose.py

- [] Changes to dev-tools e.g. CI config / github tooling
- [] Docs
- [] Bug fixes
- [] Code refactor
Logs like `SANDBOX  DOCKER: compose command: ['docker', 'compose', '--project-name', 'inspect-startup-ibbfditfgxpc4nsjex3wd2t', '-f', ...`
Logs like `SANDBOX  DOCKER: compose command: docker compose --project-name inspect-startup-ibbfditfgxpc4nsjex3wd2t -f ...`
Shouldn't

docker/compose.py: `shlex.join` for more copy-pastable logs

---

CHANGELOG.md
docs/scorers.qmd
src/inspect_ai/scorer/_reducer/reducer.py
tests/scorer/test_reducers.py

* Extended `test_reducer_preserve_metadata` to check for new behavior.
* Added changelog entry and adjusted existing note in documentation, mentioning the possibility of having a custom reducer.
* Added a new documentation section for custom reducers.
Reduced scores retain `explanation`, `answer`, and `metadata` fields from the first score, which may not be the best choice in all cases.
`Score` fields `explanation`, `answer`, and `metadata` are retained only if equal across all epochs. Based on discussion in #426 (after it was merged).
Technically, it does, since as of #426 the additional fields were always retained from the first score, but this behavior is only two weeks old. Before that, these additional fields weren't retained at all.
Since the doc note added in #426 now mentions the …

Preserve reduced score data only if equal across all epochs

---

pyproject.toml
src/inspect_evals/swe_bench/__init__.py
src/inspect_evals/swe_bench/build_images.py
src/inspect_evals/swe_bench/scorers.py
src/inspect_evals/swe_bench/swe_bench.py

- Break scoring into its own module to make the main task file a bit more comprehensible.
- Be careful to only import swebench and docker when used (this avoids making these implicit requirements for the package, as the _registry.py file will be executed when any inspect_eval is used)
- Rename scoring functions to be consistent w/ swe_bench (e.g. swe_bench_scorer)
- Rename build_images_for_samples to build_images (just a bit more pithy)
- Move the default solver into a function so it isn't created on import
- Move monkeying w/ global loggers into task function so we only do it when using swe_bench (minimise blast radius in case this has unexpected interactions)

review/modifications to swe_bench

---

src/inspect_ai/util/_sandbox/docker/prereqs.py

This happens when we get an error such as "Cannot connect to the Docker daemon ..."

docker sandbox: give an informative error message if version cmd fails

---

CHANGELOG.md
src/inspect_ai/_util/entrypoints.py
src/inspect_ai/_util/registry.py
tests/test_package/inspect_package/_registry.py
tests/test_package/pyproject.toml

This will prevent prevent unnecessary imports from packages not being referenced.

load extension entrypoints per-package

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/components/ChatView.mjs
src/inspect_ai/_view/www/src/samples/transcript/ModelEventView.mjs

When we display a model call, we will no display any user message that immediately preceded it, making it easier to understand the context of the model call (and to be aware that this user message exists!).

Display user messages prior to the model call

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/samples/SamplesTab.mjs

This steals focus when a view is loaded since it tries to dimsiss any visible sample dialog.

Don’t steal focus

---

src/inspect_ai/_cli/view.py

The change to create a subcommand for bundling caused a regression which breaks common options (e.g. log-dir and others).

Restore common options to view & view bundle

---

evals/humaneval/humaneval.py

Correctly parse markdown code blocks which do not include the language after the backticks
The HumanEval function `find_code` only matches code blocks that start with triple backticks followed by `python`. Code blocks with backticks only, without the string `python`, are not found.
As a result, all models that write code with backticks only score approximately 0%. See this example with Llama 3 8B Chat. [2024-09-30T16-02-46+01-00_bench-humaneval_FCpw3ESRoQmiy7WKtfUmxQ.json](https://github.com/user-attachments/files/17192249/2024-09-30T16-02-46%2B01-00_bench-humaneval_FCpw3ESRoQmiy7WKtfUmxQ.json)
Both types of code blocks are parsed correctly. Llama 3 8B Chat gets 58% on HumanEval, which is close to the [claims](https://ai.meta.com/blog/meta-llama-3/) made by Meta. See …

Improve HumanEval code parsing

---

CHANGELOG.md
src/inspect_ai/model/_providers/anthropic.py

For example, to use a bedrock model:
```bash
--model anthropic/bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
```

support service prefixes for anthropic models

---

CHANGELOG.md
docs/scorers.qmd
src/inspect_ai/scorer/_reducer/reducer.py
tests/scorer/test_reducers.py

Fixes #587
See conversation on PR #591
The simplest approach which is deterministic is to simply preserve the first metadata value when reducing (without any comparison). This will avoid the complicated comparison of metadata objects which have all the various traps we're running into and keep metadata around for common cases.
The alternative would be to never preserve score metadata, but this would have the effect of clearing the metadata even when a single score is being ‘reduced’ since we run the reducer pass no matter the number of epochs being run.
Score metadata is compared for equality using hashing to determine whether the value should be retained when reducing.
The first score metadata value is always preserved when reducing scores.
It could - if there is code depending upon the …

Always preserve first metadata value when reducing scores

---

src/inspect_ai/_eval/task/log.py

Note that this will mean that eval-retry won't work for these logs (eval-set can be used instead)

remove api_key from model_args

---

src/inspect_ai/dataset/_sources/csv.py

1. It is not possible to load `.tsv` files properly
2. It is not possible to load `.csv` and `.tsv` files without a header
MGSM dataset uses tab-separated file format without a header.
See [simple-evals/mgsm_eval.py](https://github.com/openai/simple-evals/blob/main/mgsm_eval.py)
This functionality would help add MGSM to `inspect_eval` (see https://github.com/UKGovernmentBEIS/inspect_evals/issues/3 )
1. New parameter `fieldnames` is added to `csv_dataset`. By default it is None, which preserves backward compatibility. This parameter is passed directly into csv.
2. Docstring is updated.
No breaking changes.
This is how I currently use `csv_dataset`:
```python
mgsm_dataset = csv_dataset(
tsv_file_path, fieldnames=["input", "target"], dialect="excel-tab"
)
```
I am not very familiar with the …

Add dataset support for `.tsv` files

---

CHANGELOG.md
src/inspect_ai/solver/_basic_agent.py

Default to 50 if the task does not specify `max_messages`

For `basic_agent()`, defer to task `max_messages` if None is specified for the agent

---

CHANGELOG.md
src/inspect_ai/model/_model_output.py

* When calling `ModelOutput.for_tool_call()`, the `content` of the model output is `"tool call for {tool_name}"`
* The `content` of the model output defaults to the same, but can be customised via an optional parameter
No. it's optional and the default doesn't change

Add optional content parameter to ModelOutput.for_tool_call

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/samples/SampleList.mjs

Add a footer with a small sample count display.

Display the sample count in the viewer

---

src/inspect_ai/log/_file.py

When returning `header_only` we’re trying to provide macro level performance and metadata while omitting sample specific data which inflates the size the of the data. We are currently leaving `sample_reductions` when providing `header_only`, which can inflate the size of the headers file since it includes an entry for each sample (bad, for example, when model grading and each reduced sample carries an explanation from the model).

Prune Sample Reductions

---

docs/index.qmd
docs/workflow.qmd

As per [src/inspect_ai/solver/_prompt.py](https://github.com/UKGovernmentBEIS/inspect_ai/blob/main/src/inspect_ai/solver/_prompt.py#L16), the prompt template is supposed to contain a `{prompt}` placeholder, not a `<prompt>` placeholder.
This is incorrect in the docs in places, which causes confusion when getting set up as to why the prompt template does not work.
This PR fixes the docs examples to correctly use `{prompt}` as a placeholder.

docs: Fix DEFAULT_PROMPT examples

---

docs/parallelism.qmd

> you need now worry about how many you put in flight
I think this meant to be:
> you need *not* worry about how many you put in flight
This sentence is quite long too, so I've simplified it a bit by bringing forward the note on throttling.
I realise I'm submitting a lot of these! I'm not sure how useful you're finding it - do let me know if you'd rather not receieve all these tiny nit-picky PRs.

docs: Fix typo, and minor phrasing simplification on parallelism

---

src/inspect_ai/_eval/run.py
src/inspect_ai/_eval/task/log.py
src/inspect_ai/_eval/task/task.py
tests/log/test_eval_log.py
tests/log/test_eval_log/log_valid.txt
tests/test_log_dir/example_task/example_task.py
tests/test_log_dir/test_log_dir.py
tests/test_run_dir.py
tests/test_run_dir/task1/task1.py
tests/test_run_dir/task2/task2.py

Task does not support a `metadata` argument despite EvalSpec supporting one.
You can optionally pass an arbitrary `metadata: dict[str, Any]` argument into the `Task` constructor. This metadata will get logged to the inspect log file, and will also be read by `read_eval_log`.
No
Implements the feature requested in https://github.com/UKGovernmentBEIS/inspect_ai/issues/655 and https://github.com/UKGovernmentBEIS/inspect_ai/issues/50#issuecomment-2175918773.

Task metadata

---

src/inspect_ai/model/_providers/azureai.py
src/inspect_ai/model/_providers/bedrock.py
src/inspect_ai/model/_providers/cloudflare.py
src/inspect_ai/model/_providers/openai_o1.py
src/inspect_ai/model/_providers/together.py
src/inspect_ai/model/_providers/util/chatapi.py
src/inspect_ai/model/_providers/util/llama31.py
tests/model/providers/test_openai_o1.py

Also fix typo in our function name
The o1 tool call parsing is overly strict. The following valid tool call fails validation because arguments is empty:
```
<tool_call>
{"name": "web_browser_back", "arguments": {}}
</tool_call>
```
This results in poor elicitation with the new browser tool
This case is handled correctly
Any model providers using `parse_assistent_response` will need to use the updated spelling `parse_assistant_response`

Correct o1 tool calling when empty arguments passed

---

.github/workflows/build.yml

Avoids opening a PR just to get the workflow to run on a new branch

allow CI checks to be run manually with workflow_dispatch

---

CHANGELOG.md
src/inspect_ai/model/_providers/google.py
src/inspect_ai/model/_providers/vertex.py

Use named parameter for`Tool` instantiation for compatibility w/ recent updated to google-generativeai (0.8.3)
Fixes https://github.com/UKGovernmentBEIS/inspect_ai/issues/695

Google: compatibility with google-generativeai v0.8.3

---

CHANGELOG.md
src/inspect_ai/model/_providers/anthropic.py

Only one of this PR and https://github.com/UKGovernmentBEIS/inspect_ai/pull/701 should be merged. These two PRs are two variants of a fix.
Currently, whenever we call an Anthropic model with tool calls enabled, a system message "Before answering, explain your reasoning step-by-step in tags." is forcibly injected at the end of the existing system message.
This injection cannot be turned off and is very difficult to detect in the log viewer -- you can see it in the json details of the transcript log which logs raw model requests but not the main Messages view.
The tool call injection is removed. I feel like it is somewhat of an anti-pattern to be injecting a prompt at this level of the abstraction hierarchy, so I opted to remove this injection instead of making it optional. 
If we were to …

Remove anthropic tool reminder injection

---

CHANGELOG.md
src/inspect_ai/_eval/task/sandbox.py

For the Docker sandbox we have a deferred cleanup logic that allows users to see console progress for cleanup. This was initially put in because cleanup could be very long (in which case users might Ctrl+C, leaking containers). 
At the time there was no concept of multiple concurrent tasks and no concept of `fail_on_error`, which meant at a practical level "deferred" cleanup was really just deferring a few hundred milliseconds (because any error implied that the entire eval was ending). In the meantime, a number of things have changed:
(1) We have resolved the long cleanup issues w/ a combination of `init: true` and `stop_grace_period: 1s` (which means that containers terminate typically in 1 second or less)
(2) We have added two independent ways that evals can continue in the presence of …

Cleanup Docker Containers immediately for samples with errors

---

CHANGELOG.md
requirements.txt

Required for use of `semver.Version`: https://github.com/UKGovernmentBEIS/inspect_ai/blob/d52b1920391eabc69bb32f3ea83470f3ad2ec760/src/inspect_ai/_util/version.py#L19
Resolves https://github.com/UKGovernmentBEIS/inspect_ai/issues/705

requirements: require semver >= 3.0.0

---

docs/scorers.qmd

Missing metric decorator in the example [here](https://inspect.ai-safety-institute.org.uk/scorers.html#custom-metrics)
Added the missing decorator
No
I copied this example as a starting point for my custom metric and kept getting a registry error. It took me a little while to realize that the example I copied was missing the decorator.

add missing metric decorator to docs

---

CHANGELOG.md
src/inspect_ai/_util/registry.py
tests/util/test_registry.py

Previously lists of registry objects were not logged correctly in the `plan`. For example:
```json
{
"solver": "use_tools",
"params": {
"tools": [
"execute",
"execute"
]
}
},
```
With this PR this is now logged as:
```json
{
"solver": "use_tools",
"params": {
"tools": [
{
"type": "tool",
"name": "add",
"params": {}
},
{
"type": "tool",
"name": "list_files",
"params": {}
}
]
}
}
```

capture list and dict of registry objects when logging plan

---

CHANGELOG.md
src/inspect_ai/_util/registry.py
src/inspect_ai/scorer/_metric.py
src/inspect_ai/scorer/_scorer.py
src/inspect_ai/solver/_basic_agent.py
src/inspect_ai/solver/_prompt.py
src/inspect_ai/solver/_solver.py
src/inspect_ai/solver/_use_tools.py
src/inspect_ai/tool/_tool.py
tests/scorer/test_metric.py
tests/tools/test_tool_def.py

Captures type information in decorated functions for type checkin and docs/autocomplete.
Uses [ParamSpec](https://docs.python.org/3/library/typing.html#typing.ParamSpec) which was added in Python 3.10 to make decorated functions more typesafe (thanks to @rusheb-apollo for the pointer on this!).
Resolves https://github.com/UKGovernmentBEIS/inspect_ai/issues/506

Use ParamSpec to capture types of decorated solvers, tools, scorers, and metrics

---

docs/scorers.qmd
src/inspect_ai/scorer/_model.py
tests/scorer/test_model_graded.py

Follow on to https://github.com/UKGovernmentBEIS/inspect_ai/pull/738 that enables customisation of the way the chat history is presented by passing a function rather than `True`.

enable users to pass a function for include_history

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/components/MarkdownDiv.mjs

We rely upon html tags occasionally when rendering markdown (for example, in multiple choice answers, we use paragraphs).

Allow HTML in markdown

---

CHANGELOG.md
src/inspect_ai/_util/entrypoints.py

Resolves https://github.com/UKGovernmentBEIS/inspect_ai/issues/747
Note that one other change to `pyproject.toml` is required for this all to work end to end:
```toml
[project.entry-points.inspect_ai]
el = "el.supervision.inspect_ai._registry"
```

correctly load extensions in packages where package name differs from dist name

---

CHANGELOG.md
src/inspect_ai/model/_providers/openai.py

Sporadically supported across models and we already internally validate and report errors to the model

OpenAI: eliminate use of `strict` tool calling

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/components/CopyButton.mjs

I haven't yet been able to consistently cause this, but this issue (#717) does sometimes happen and when it does, the target element is the BUTTON not the I. Since I can't reliably determine the cause, for now just band-aid by getting the child in this case.
Fixes #717

Improve robustness of copy button

---

CHANGELOG.md
src/inspect_ai/_util/appdirs.py
src/inspect_ai/_view/notify.py
src/inspect_ai/_view/view.py
tools/vscode/src/inspect/props.ts
tools/vscode/src/providers/inspect/inspect-logs-watcher.ts

Resolves https://github.com/UKGovernmentBEIS/inspect_ai/issues/665
It seems as if unlike other directories, user_runtime_dir does not have a fallback if the user don't have the requisite parent directories with permissions. This causes failure modes on devcontainers and other minimally configured systems.
The resolution is to use the user_data_dir instead, which has a `~/.local/share` fallback on Linux. VS Code extension is also updated to look for view notification files in both locations to support older and newer versions.

use user_data_dir rather than user_runtime_dir for view notifications

---

tests/conftest.py
tests/view/test_bundle.py

The s3-related tests were broken.
The s3 tests pass. (Note, having INSPECT_API_KEY_OVERRIDE or INSPECT_TELEMETRY will break them)
No
I assume at no point should inspect be trying to create a bucket if it doesn't exist. The combination of s3fs+fsspec tries to do this sometimes (e.g. here https://github.com/UKGovernmentBEIS/inspect_ai/blob/main/src/inspect_ai/_util/file.py#L172)  which can cause confusion.

Fix S3 tests

---

src/inspect_ai/tool/_tools/_web_browser/_resources/playwright_crawler.py

Any HTTPS errors (such as from self-signed certs) will result in empty responses.
https://github.com/UKGovernmentBEIS/inspect_ai/issues/772
Page content is now returned when HTTPS errors occur if the developer uses a custom image and specifies any non-empty value of IGNORE_HTTPS_ERRORS for the web browser server.
No.
Tested when forking the browser code. Also not sure how to rebuild the official image after this change to get these to take effect.
See the issue - I also explored other options, but I think this is the fastest way to unblock workflows with self-signed certs.

Add option for ignoring HTTPS errors in web browser tooling

---

CHANGELOG.md
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/samples/SampleTranscript.mjs
src/inspect_ai/_view/www/src/samples/transcript/ScoreEventView.mjs
src/inspect_ai/_view/www/src/samples/transcript/TranscriptView.mjs

We were simply displaying score values in transcripts, but the score value could be a complex object. This would result in the object participating in the preact render lifecycle and gaining additional properties (making it circular). When it was then stringified to JSON, the circularity was an issue. 
This fixes the rendering properly render records and arrays which removes the circularity.
Error rendering logs which contains scorers that produce arrays or records.
No error.
No.

Properly render complex scores in transcript

---

CHANGELOG.md
src/inspect_ai/_view/www/.gitignore
src/inspect_ai/scorer/_reducer/reducer.py
tests/scorer/test_metric.py

If a user produces a score whose value is a string, when that value is ‘reduced’ using the default mean reducer, it is coerced to a float. For strings thing means when the Score arrives at the custom metric, it will carry the reduced value which has been coerced to a float.
This fix is minimal - it implements support for string values in the mean reducer, providing the most common string value (or the first string value if non are most common).
Fixes #775
Scorers that return string values run through the reduction process and the string values are reduced to a float by the mean reducer.
The mean reducer will reduce strings to the most common value, meaning that the string value is preserved across the mean reducer. 
No

Better support string values for scores

---

CHANGELOG.md
src/inspect_ai/model/_providers/mistral.py

Bug: When passing both an api_key and base_url to MistralAPI.init, the base_url gets ignored.
Fix: Always set the base_url if available.

Bugfix: Properly setting base_url for mistral provider

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/samples/transcript/state/StateDiffView.mjs

Currently keys with angle brackets ‘disappear’ when rendered in the state / store events of the transcript.

Sanitize keys displayed in state/storage

---

src/inspect_ai/util/__init__.py
src/inspect_ai/util/_sandbox/self_check.py

This exports `SandboxEnvironmentLimits` so that non-inspect `SandboxEnvironment` providers can access them (e.g. k8s in the works).

Export `SandboxEnvironmentLimits` (for 3rd party sandbox providers)

---

src/inspect_ai/util/_sandbox/environment.py
src/inspect_ai/util/_sandbox/self_check.py

Unfortunately, the claim that I'd put in the `SandboxEnvironment.exec()` docstring as part of #781  is (technically true but) misleading wrt behaviour in k8s (and eventually docker if we move to streaming output)
>This will not cause the command to be terminated.
**Why?**
To avoid battering the Kubernetes API when an agent executes a command which results in a very large output, we want to stop the network traffic (by closing the websocket) once the limit is reached. Whilst this does not terminate the underlying sandboxed command, it will prevent stdout/stderr pipes from being consumed. Depending on the command being run, this can cause the remote sandboxed process to block when trying to write to stdout/stderr.
We _could_ continue streaming all the output from these commands but just …

Remove `SandboxEnvironment.exec()` claim (and associated test)

---

CHANGELOG.md
src/inspect_ai/_view/www/.gitignore
src/inspect_ai/scorer/_reducer/reducer.py
tests/scorer/test_metric.py
tests/scorer/test_reducers.py

This reverts commit 79f1d7e730195303e283aed4b7ac6329da3be291.
Fixes #796
#	CHANGELOG.md

Revert "Better support string values for scores (#785)"

---

docs/extensions.qmd
src/inspect_ai/util/_sandbox/environment.py

If other sandbox providers (e.g. k8s) happen to provide the sandboxes in another order (e.g. alphabetically because that's how the API returns them) then even calling `sandbox("default")` would resolve the sandbox named `another` below:
```
service:
default: ...
another: ...
```
This PR aims to make Inspect's requirement clearer both in the docs and in the `SandboxEnvironment` interface inline docs.

Clarify sandbox provider ordering requirement

---

CHANGELOG.md
src/inspect_ai/dataset/_sources/file.py

Some arguments aren't propagated from `file_dataset` to csv and json datasets. This means that some functionality (such as shuffle) is broken.
All arguments are now propagated
Existing calls to `file_dataset` using positional arguments for `dialect`, `encoding`, `name`, `fs_options` will need to be updated.

Propagate missing json and csv arguments through file_dataset

---

CHANGELOG.md
src/inspect_ai/_eval/task/results.py

This change regressed some scoring scenarios. We will look for another fix for metrics that want access to raw string content.

revert change to single epoch reducer behavior

---

src/inspect_ai/_eval/evalset.py

"Identifier" incorrectly spelt as "identifer" (missing an "i") in multiple places
Spelling is now correct 
No: only affects private functions and function-local variables

Fix typo 'identifer' --> 'identifier'

---

CHANGELOG.md
src/inspect_ai/model/_providers/bedrock.py

I’ve observed that Bedrock apepars to be returning OAI compatible responses for Mistral Large 2407. This makes the parsing of the completion resilient by preferring the old form (`outputs`) but falling back to parsing OAI compatible choices.

Fix parsing of Bedrock Mistral Large 2407 responses

---

CHANGELOG.md
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/api/client-api.mjs
src/inspect_ai/_view/www/src/samples/SampleError.mjs
src/inspect_ai/_view/www/src/samples/SampleList.mjs
src/inspect_ai/log/_recorders/eval.py

Sample summaries were not properly carrying error messages, so sample errors in .eval files are not currently displayed. This fixes that issue, and also preserves the display of errors in json formatted files.
Existing ‘eval’ formatted log files will not display errors (the error is missing from the file). They can be updated to properly display by round tripping them using `inspect log convert` and converting them to json and then back to eval format.

Properly display sample errors

---

CHANGELOG.md
src/inspect_ai/log/_convert.py

Preserve existing behavior for converting folders. For files, no longer use the original file name subdirectories - just place the converted file in the folder provided by the `—output-dir` arg.

Improve conversion path resolution

---

CHANGELOG.md
src/inspect_ai/util/_sandbox/limits.py
src/inspect_ai/util/_sandbox/self_check.py

@craigwalton-dsit We have already seen scorers exceeding the 1 MiB limit (e.g. in SWE bench capturing all of the test results, etc.). I think we can afford to take this higher without risking a run on memory (given that even if _every_ `exec()` call was simultaneously at the limit it would at most require `max_subprocesses * 10mb` of memory). LMK what you think!

Increase sandbox `exec()` output limit from 1 MiB to 10 MiB

---

src/inspect_ai/model/_model.py

If INSPECT_DISABLE_MODEL_API was set, an error would be thrown even if there would have been a cache hit
An error is only thrown if there is a cache miss and we are actually about to call a model for realsies
If someone was relying on the previous behaviour (excluding cache hits) then this would break, but I doubt that is the case

Move INSPECT_DISABLE_MODEL_API check

---

CHANGELOG.md
src/inspect_ai/solver/_basic_agent.py

Inspect's basic agent will, by default, run the scorer at least twice.
It will run it at least once when checking the score, and then once for the actual scoring.
As I understand it, this is to enable retrying based whether your submission is correct. But the issue is - this means the scorer runs twice! If your scorer makes mutations to some state (e.g. in the sandbox environment), this can cause problems with scoring correctness.
This came up in the context of an evaluation where the scorer runs some script on the disk which checks if a marker file exists, does nothing if it does, and writes this marker file at exit. This ensures the script runs once and only once on the machine. 
But, since our scorer runs twice, and the score that actually gets reported is from the second time it runs, …

Fix scoring behaviour in basic agent

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/App.mjs
src/inspect_ai/_view/www/src/components/LargeModal.mjs
src/inspect_ai/_view/www/src/components/TabSet.mjs
src/inspect_ai/_view/www/src/samples/SampleDialog.mjs
src/inspect_ai/_view/www/src/samples/SamplesTab.mjs
src/inspect_ai/_view/www/src/utils/sync.mjs
src/inspect_ai/_view/www/src/workspace/WorkSpace.mjs

When a log viewer in vscode is sent to the background (e.g. you select another tab), the scroll position of the viewer is reset since we completely reload the viewer when restoring the tab.
When a log viewer in vscode is sent to the background (e.g. you select another tab), the scroll position of the viewer is preserved. We don't preserve other potentially useful things like expanded panels, selected sub tabs within transcripts, etc.. But the general scroll position will be preserved now.

Log View: Restore Scroll Position in VS Code

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/App.mjs

Do not re-render when scroll completes as this can lose things like expanded state for panels and additionally can cause jitter
Expansion state can be lost, scrolling can jitter 
No state loss, no jitter

Fix bug with view scroll

---

CHANGELOG.md
src/inspect_ai/solver/_basic_agent.py
tests/solver/test_basic_agent.py

When using the `basic_agent` solver, if the model submits an incorrect answer, the user can only return a pre-defined static string (such as `Your answer was incorrect.`)
When using the `basic_agent` solver, if the model submits an incorrect answer, the user can return a custom string based on the `TaskState` and `Score`. This allows the user to incorporate a Score's explanation, or other state information, into feedback for the model. One use case for this: if the model writes some code, and the scorer executes that code and finds that it raises an exception, the exception message can be passed back to the model.
No
See conversation on Slack here: https://inspectcommunity.slack.com/archives/C080K7SQ4SG/p1731605753325889

Support custom incorrect messages in basic_agent

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/components/ChatView.mjs
src/inspect_ai/_view/www/src/components/Tools.mjs

If the model makes more than one tool call in a single message, we previously would capture on the last tool output and display that for all tool calls. This allows the message to carry more than one tool output for display.

Properly Support Multi Tool Call Output

---

src/inspect_ai/util/_sandbox/self_check.py

It wasn't clear whether write_file should allow an existing file to be overwritten. 
It should be allowed, as long as the sandbox user would be allowed to. I've added a test to clarify.
Original discussion https://inspectcommunity.slack.com/archives/C0805HJTK8U/p1731645089944059

Add a test for overwriting a file with write_file

---

src/inspect_ai/model/_providers/groq.py

fix: remove upper limit for max_connections for Groq

---

CHANGELOG.md
docs/scorers.qmd
src/inspect_ai/_eval/task/results.py
tests/scorer/test_metric.py

When a score value returns a dictionary value, it is common to provide a dictionary of metrics to apply to the keys in the score value. For example:
```
@scorer(metrics={
"basic": [mean(), stderr()],
"fancy_1": [mean(), stderr()],
"fancy_1": [mean(), stderr()]
})
def complex_score():
async def score(state: TaskState, target: Target):
return Score(value={
"basic": 1.0,
"fancy_1": 0.9,
"fancy_1": 0.1
})
return score
```
glob keys permit this (which is the equivalent of the above):
```
@scorer(metrics={
"*": [mean(), stderr()],
})
def complex_score():
async def score(state: TaskState, target: Target):
return Score(value={
"basic": 1.0,
"fancy_1": 0.9,
"fancy_1": 0.1
})
return score
```
or this (which will apply mean, stderr to the base score and mean, stderr, and accuracy to the fancy …

Treat dictionary keys as globs

---

CHANGELOG.md
src/inspect_ai/_eval/run.py
src/inspect_ai/_eval/task/run.py

The normal behavior for `max_samples` is that it is is applied per task (i.e. total running samples is `max_tasks` * `max_samples`). However, we previously implemented special behavior for evals with sandboxes, enforcing this limit globally rather than per task This was in turn a result of the observation that Docker tended to get flakey at > 30 running containers (especially if they used networking) so we were trying to make it harder for users to unknowingly get into a situation where Docker was overloaded.
With this PR, `max_samples` are handled the same for all evals (sandbox or no sandbox). There are several benefits to this:
1. The previous inconsistent behavior is harder to reason about consistently (a simple answer to how `max_samples` is applied is better than one with …

consistent behavior for `max_samples` across sandbox and non-sandbox evals

---

CHANGELOG.md
docs/eval-logs.qmd
src/inspect_ai/log/_file.py
src/inspect_ai/log/_log.py
src/inspect_ai/log/_recorders/eval.py
src/inspect_ai/log/_recorders/json.py
tests/log/test_eval_log.py
tests/log/test_log_formats.py
tests/test_eval_set.py

The `EvalLog` object returned from `eval()` and `read_eval_log()` now has a `location` property that indicates the storage location it was written to or read from.
The `write_eval_log()` function will use this `location` if it isn't passed an explicit `location` to write to. This enables you to modify the contents of a log file return from `eval()` as follows:
``` python
log = eval(my_task())[0]
write_eval_log(log)
```
Or alternatively for an `EvalLog` read from a filesystem:
``` python
log = read_eval_log(log_file_path)
write_eval_log(log)
```
If you are working with the results of an [Eval Set](eval-sets.qmd), the returned logs are headers rather than the full log with all samples. If you want to edit logs returned from `eval_set` you should read them fully, edit them, and then write …

location property for eval logs

---

CHANGELOG.md
src/inspect_ai/tool/_tools/_execute.py
tests/tools/test_bash_tool.py

In for example SWE-Bench, the Docker container setup adds things to `.bashrc` (etc), as part of Conda.
But if you run the inspect bash tool, it doesn't include these modifications, so it's very unusual for a AI agent to get the Python environment into the correct state before attempting the task.
See for example here https://github.com/princeton-nlp/SWE-bench/blob/main/swebench/harness/dockerfiles.py#L29
The bash tool uses a login shell so it sources the expected files
It's possible this could break things if any existing evals relied on bash not having a login shell

Make bash a login shell

---

CHANGELOG.md
src/inspect_ai/_util/text.py
src/inspect_ai/scorer/_common.py
tests/util/test_str_to_float.py

Resolves https://github.com/UKGovernmentBEIS/inspect_ai/issues/848 so the e.g. following will now be handled: `1²`

handle exponents when converting str to float

---

tools/vscode/webpack.config.js

This fixes eslint complaints about our webpack.config wihout requiring more work to switch to modern imports.

Minimal fix to vscode eslint complaint

---

src/inspect_ai/scorer/_common.py
tests/scorer/test_match.py

This improves our text splitting, but will result in changes vs the way matching previously worked:
1) consecutive whitespace characters would previously have been multiple words (e.g. an empty string in the word list). Now, consecutive whitespace will be treated as a single whitespace.
2) Word splits with new lines would span new lines, so `60\nThis` would be treated as a single word. Now, that will be split into two words: `[“60”, “This”]`
3) Previously only spaces would split words, now any whitespace will.
Thx to @fastfedora for the fix.

Improve word splitting / text matching

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/samples/SampleList.mjs
src/inspect_ai/_view/www/src/samples/SamplesDescriptor.mjs

More consistently compute proper grid for scores. In particular ensures that column heading grid and sample value grids stay aligned with long scores, missing answers, and other edge cases.

Improve score column sizing

---

src/inspect_ai/util/_sandbox/self_check.py

Fixes tests which appear to have been broken since #833 (updating exec output limits from 1 MiB -> 10 MiB).
I presume these `self_check` tests aren't run as part of CI in `test_sandbox_docker_and_local.py` or else CI wouldn't have been passing. Is this intentional?

Fix `self_check` tests: update sizes from 1 MiB to 10 MiB

---

src/inspect_ai/_display/textual/app.py

This PR makes two improvements to cancellation when using fullscreen display:
1) Provides feedback that a cancel request was received by changing the titlebar text
2) Does not allow repeated cancellation requests (which would prevent proper cleanup of e.g. docker containers)
Resolves https://github.com/UKGovernmentBEIS/inspect_ai/issues/914

improve cancellation feedback

---

src/inspect_ai/tool/_tool_call.py

The current behavior is that we are using the pydantic `Field` function on a python dataclass object. I believe this is a typo and leads to the warning
```
pydantic/main.py:390: UserWarning: Pydantic serializer warnings:
Expected `ToolCallContent` but got `FieldInfo` with value `FieldInfo(annotation=Unio...red=False, default=None)` - serialized value may not be as expected
return self.__pydantic_serializer__.to_python(
```
Unfortunately I do not have a minimal reproduction of the above warning.
We switch to using the `dataclasses.field` function and the warning no longer appears.
No

Change Field to field in ToolCall

---

CHANGELOG.md
src/inspect_ai/_util/file.py

This PR changes our directory creation behavior for S3 filesystems as follows:
1) Rather than calling the the fsspec [makedirs](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.spec.AbstractFileSystem.makedirs) function w/ `create_parents=True` (which in turn [calls create_bucket](https://github.com/fsspec/s3fs/blob/b6a00957d77c83df11a1680a0590bdfd06d6ddc6/s3fs/core.py#L905) for S3FS), we start off by calling [mkdir](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.spec.AbstractFileSystem.mkdir) with `create_parents=False`.
2. If this fails due to `FileNotFoundError` then we go ahead and call `makedirs` to cause the bucket to be created.
This avoids calling S3 CreateBucket unless absolutely required, which in turn makes it play better with prvillieges that …

Logging: Only call CreateBucket on Amazon S3 when the bucket does not already exist

---

CHANGELOG.md
src/inspect_ai/_display/textual/app.py
src/inspect_ai/util/_sandbox/docker/compose.py
src/inspect_ai/util/_sandbox/docker/docker.py
src/inspect_ai/util/_sandbox/local.py
src/inspect_ai/util/_subprocess.py
tests/tools/test_max_exec_output.py

This PR makes a few changes aimed at enforcing sandbox output limits at the source (thereby never allowing larger than desired outputs into memory):
- Our `subprocess()` function now streams stderr and stdout rather than reading them in one shot. 
- The `subprocess()` function gains an `output_limit` argument which terminates the read loop if the total bytes read exceeds the `output_limit`.
- The Docker sandbox passes the requisite read_file and exec output limits into `subprocess()`
- Output limits are still enforced in the same place (they just will have less excess output in memory due to the truncation in `subprocess()`.
I have run the main test suite + run some agent evals (Intercode CTF, GDM In House CTF, and GAIA Level 1) to confirm that `subprocess()` is still working as expected. …

docker sandbox: streamed reads of stderr/stdout (enabling us to enforce output limits for read_file and exec at the source).

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/components/Tools.mjs
src/inspect_ai/_view/www/src/utils/debugging.mjs

Because an object was getting through the input parsing, it was ending up decorated with props and other reactive elements from preact. when it was then converted to json, there is circularity. The  `extractInput` should be returning a string always, so ensure this is true.

Fix circular error when rendering tool input

---

tools/vscode/CHANGELOG.md
tools/vscode/package.json
tools/vscode/src/extension.ts
tools/vscode/src/providers/activity-bar/log-listing/log-listing-provider.ts
tools/vscode/src/providers/protocol-handler.ts

- Supports both json and eval files (both local and remote)
- Copy Editor Link command is available from the `logs` activity panel for remote files only

Open log files directly in the vscode log viewer

---

docs/_quarto.yml
docs/llms.txt
docs/scripts/post-render.sh

Generate LLM friendly version of site as per the LLMS standard described here: https://llmstxt.org/

generate llms.txt and markdown versions of articles

---

CHANGELOG.md
src/inspect_ai/tool/_tool_def.py
src/inspect_ai/tool/_tool_info.py
src/inspect_ai/tool/_tool_params.py
tests/tools/test_tool_parse.py

The PR enhances our support for generating JSON schemas for tools from Python types. We now support the following additional typing constructs:
- Unions (e.g. `str | list[str]`)
- Optional parameters (e.g. `str | None`)
- Default parameters (e.g. `str | None = None`)
- Enum/literal parameters (e.g. `Literal[1,2,3]`)
These in addition to existing support for `TypedDict`, `@dataclass`, and Pydantic `BaseModel` should mean that we can parse just about any type definition. In the case where we can't discover a type definition we've also clarified the error message to indicate that the type is unsupported (previously the error indicated that there was no annotation, which wasn't actually correct in the case of unsupported type annotations).

tools: improved typing/schema support (unions, optional params, enums)

---

CHANGELOG.md
src/inspect_ai/tool/_tools/_web_browser/_web_browser.py

Current behaviour is seen on the left, new behaviour is on the right.
Only if you rely on base64 image data, which is unlikely.

Remove base64 data from images

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/samples/transcript/ModelEventView.mjs

Display model time in model call events

---

tools/vscode/CHANGELOG.md
tools/vscode/package.json
tools/vscode/src/providers/activity-bar/log-listing/log-listing-provider.ts

This correctly encodes the log file path, which can contain characters such as `+` which must be encoded.
500 error when following URLs with incorrect encoding.
It works!

Correctly URL encode copied URL

---

src/inspect_ai/_display/textual/widgets/tasks.py
src/inspect_ai/_eval/task/run.py

- Place floor (2%) and ceiling (98%) on task progress (2%) 
- Restore the clock
- Only tick sample progress when a sample is completed
This change will make the % complete exactly match the total number of samples completed which will match the progress bar completion display as well.

Small sample progress fixes

---

CHANGELOG.md
src/inspect_ai/_eval/run.py
src/inspect_ai/_eval/task/run.py

Previously, when running with `max_tasks > 1` errors occurring during the final write of the log file were not reported (and the task scheduler exited abnormally).

report errors that occur during task finalisation

---

CHANGELOG.md
src/inspect_ai/dataset/_sources/hf.py

Previously, it would crash when not specified.

`hf_dataset` now explicitly requires the `split` argument

---

CHANGELOG.md
src/inspect_ai/_display/core/display.py
src/inspect_ai/_display/core/input.py
src/inspect_ai/_display/textual/app.py
src/inspect_ai/approval/_human/console.py
src/inspect_ai/approval/_human/panel.py
src/inspect_ai/util/_panel.py

This PR makes available a new `input_panel()` API for adding custom panels to the fullscreen display (e.g. we use this API for the new approvals UI: https://github.com/UKGovernmentBEIS/inspect_ai/pull/958

input panel api: minor improvements + make public

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/package.json
src/inspect_ai/_view/www/src/components/Tools.mjs
src/inspect_ai/_view/www/yarn.lock

When transition from a prism highlighted tool input to a non highlighted input (if both appear in identical positions in the overall DOM tree), the stale content would still be rendered. This is addressed by adding a key to the code element itself, which will ensure that input is remounted when the contents change (which is currently not happening since the contents are being mutated ‘behind the back’ of react by prism.

Fix issue with stale rendered tool input

---

CHANGELOG.md
src/inspect_ai/solver/_use_tools.py
tests/tools/test_use_tools.py

use_tools always replaces the existing tools, so you can't for example chain it
There's a new optional parameter `append` (defaults to false) to allow you to append instead of replacing
Prior discussion https://inspectcommunity.slack.com/archives/C0805HJTK8U/p1733830171419849

use_tools append

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/samples/transcript/state/StateEventRenderers.mjs

In some cases (particularly when rendering tools out of state changes)

Allow tool parameters to be optional

---

CHANGELOG.md
src/inspect_ai/_eval/run.py
src/inspect_ai/_eval/task/run.py
tests/test_run_dir/task2/task2.py

The system requires unique sample ids (for example, it is used when naming sample data files in the eval log format).
Fixes #972

Raise error for duplicate sample ids

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/samples/SampleDisplay.mjs
src/inspect_ai/_view/www/src/samples/SampleScoreView.mjs
src/inspect_ai/_view/www/src/samples/SamplesDescriptor.mjs

Ensure that we're properly displaying score metadata in the score tab for samples.

Score metadata display

---

src/inspect_ai/_display/textual/widgets/task_detail.py
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/samples/SamplesDescriptor.mjs

- only bind boolean scoring when there are 1s and 0s (not just 0s)
- bind to individual score rendering when at least one dictionary key is used in a metric
- don't error if glob makes it through to metrics keys (which is can since metrics are computed before scoring, preventing any metrics from being expanded against score values)

Improve Handling of Partial Dictionary Scores

---

CHANGELOG.md
src/inspect_ai/_util/logger.py

Since the main task display app is in a difference context than the logger, it can’t use a context variable to hold this value.

Use global variable to track rate limits

---

CHANGELOG.md
docs/models.qmd
src/inspect_ai/model/_providers/azureai.py

Emulation is enabled by default for Llama models

Azure AI: Add `emulate_tools` model arg to force tool emulation

---

CHANGELOG.md
src/inspect_ai/_util/logger.py

Add support for detecting Bedrock http rate limits. The log configuration for these errors is described here:
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html#validating-retry-attempts
We now will inspect debug messages from botocore and respond appropriately to messages.

Add support for rate limit detection on Bedrock

---

CHANGELOG.md
src/inspect_ai/_display/textual/widgets/task_detail.py

The first implementation assumed that metric names would be static through the eval, but there are cases (e.g. agentharm) where keys may be changed (for example, a category level metric). This removes the assumption that metric names are static.
We use metric names to pick widgets to update (so we update only the value, not recomputing the whole grid constantly) - when we encounter a metric that we don’t have a value widget for, this means the grid is stale and needs to be re-computed.
Fixes #1002

Support dynamic metric names

---

CHANGELOG.md
src/inspect_ai/_view/www/App.css
src/inspect_ai/_view/www/dist/assets/index.css
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/components/JsonPanel.mjs

The panel content would disappear with a re-render caused by showing the find view in vscode.
This converts to reactively highlighting rather than setting the innerhtml.

Simplify JSON Panel rendering

---

CHANGELOG.md
docs/models.qmd
src/inspect_ai/model/_providers/azureai.py
src/inspect_ai/model/_providers/bedrock.py
src/inspect_ai/model/_providers/hf.py
src/inspect_ai/model/_providers/vllm.py

When using the `bedrock` model provider, tool calling support can be 'emulated' for models that Bedrock has not yet properly implemented converse tool calling for. This occurs by default for Nova models. For other models, use the `emulate_tools` model arg to force tool emulation:
```bash
inspect eval ctf.py -M emulate_tools=true
```
You can also use this option to disable tool emulation for Nova models with `emulate_tools=false`.

emulated tools for bedrock/nova

---

CHANGELOG.md
src/inspect_ai/_eval/task/run.py

The sample count was incorrect when retrying an evaluation (as the sample count wasn't being incremented when a sample was skipped because it was already complete).

Make sure to increment sample count when retrying

---

CHANGELOG.md
src/inspect_ai/_eval/task/results.py
tests/scorer/test_metric.py

`metric`s return value is `Value` which means that a list or dict is allowed to be returned, like so:
```
@metric
def nested_dict_metric() -> Metric:
def metric(scores: list[Score]) ->  Value:
total = 0
for score in scores:
if not isinstance(score.value, dict) and not isinstance(score.value, list):
total = int(score.value)+ total
return {
"total": total,
"ratio": total/26
}
return metric
```
or
```
@metric
def nested_array_metric() -> Metric:
def metric(scores: list[Score]) ->  Value:
total = 0
for score in scores:
if not isinstance(score.value, dict) and not isinstance(score.value, list):
total = int(score.value)+ total
return [total, total/26]
return metric
@scorer(
metrics={"*": [nested_dict_metric(), nested_array_metric()]}
)
```
This properly handles this case (which currently just …

Properly handle dicts and lists

---

CHANGELOG.md
src/inspect_ai/_cli/eval.py
src/inspect_ai/model/_generate_config.py
src/inspect_ai/model/_providers/openai.py
src/inspect_ai/model/_providers/providers.py

This PR adds support for access to the full o1 model. PR is marked as draft b/c as of yet I still get "The model `o1` does not exist or you do not have access to it" when trying to access `o1`.  Changes include:
1) Native tool calling API for `o1` (we still fall back to emulation for `o1-preview` an `o1-mini`).
2) Yield the new "developer" message type for system messages when running with `o1`
3) Support `reasoning_effort` generation config option.
4) We now require the latest version of the OpenAI package (1.58.1) to support all of the above.
We'll keep trying out the API tomorrow to see if we can verify that all is working and will merge after that.

OpenAI: Support for o1 including native tool calling and `reasoning_effort` generation option

---

CHANGELOG.md
pyproject.toml
requirements.txt
src/inspect_ai/util/_sandbox/docker/config.py
src/inspect_ai/util/_sandbox/docker/docker.py
src/inspect_ai/util/_sandbox/docker/util.py
src/inspect_ai/util/_sandbox/local.py

We currently use aiofiles for sandbox read_file implementations as well as for writing auto-compose files. These are all local file reads and they are for small files so in most cases this will make read performance considerably worse (as it schedules the read/write onto a thread pool).
Further, we are attempting to eliminate any possibility of threading deadlocks, and this represents another point of exposure to them.

remove use of aiofiles

---

docs/_sandboxenv-interface.md
docs/tools.qmd
src/inspect_ai/util/_sandbox/environment.py
src/inspect_ai/util/_sandbox/limits.py

This was updated in #833 - just updating the places the value was referenced.

Update py doc strings to reflect new 10 MiB exec output limit

---

tools/vscode/CHANGELOG.md
tools/vscode/package.json
tools/vscode/src/extension.ts

Properly terminate `inspect view` when the extension is disposed

Properly terminate `inspect view` when the extension is disposed

---

CHANGELOG.md
src/inspect_ai/_eval/task/run.py

This was originally done b/c `max_samples` was global, after the change to per-task `max_samples` this no longer makes sense.

concurrency: do not use `max_tasks` as a lower bound for `max_samples`

---

CHANGELOG.md
src/inspect_ai/util/_sandbox/docker/compose.py

Temporary mitigation for https://github.com/UKGovernmentBEIS/inspect_ai/issues/1034 while we decide whether we can get rid of `docker compose cp` entirely.

docker sandbox: introduce 120 second timeout on `docker compose cp`

---

CHANGELOG.md
src/inspect_ai/tool/_tools/_web_browser/_web_browser.py
src/inspect_ai/util/_sandbox/context.py
src/inspect_ai/util/_sandbox/docker/compose.py
src/inspect_ai/util/_sandbox/docker/docker.py
src/inspect_ai/util/_sandbox/service.py

We have discovered that under some configurations (in this case Ubuntu 24.04 on EC2 t3.2xlarge instance w/ the latest version of Docker) docker compose commands can hang (at a low rate e.g. something like 1/1000 commands). This might be a race condition in the docker daemon (as it likely doesn't normally get the density/volume of commands we send when running so many parallel samples/containers).
Issue here: https://github.com/UKGovernmentBEIS/inspect_ai/issues/1034
The resolution is to treat `docker compose` commands as inherently unreliable and prone to this hanging. The mitigate this we do the following:
1) Provide a default timeout for docker compose commands (60 seconds) and retry twice for commands that time out (there first retry waits the lower of 60 seconds and the original …

provide retry for docker compose commands 

---

CHANGELOG.md
src/inspect_ai/log/_recorders/eval.py

In testing large eval-sets with high sample frequency (many small samples with short generates), we observe hangs when attempting to write eval logs to S3. Those hangs go away when writing synchronously, so switch to pure sync writes for the time being to improve stability.

Switch to sync S3 logging

---

.gitignore

Developer specific VSCode bookmarks are within `git`'s scope.
`.vscode/bookmarks.json` is ignored.
No.

Add .vscode/bookmarks.json to .gitignore.

---

tools/vscode/package.json
tools/vscode/src/providers/codelens/codelens-provider.ts
tools/vscode/src/test/codelens-provider.test.ts

The VSCode extension of inspect provides two commands ("Run task" and "Debug Task") when it identifies a task function. The current pattern looks for an `@task` decorator, which leads to problems with packages that use a similarly named decorator, for example, my package [pytask](https://github.com/pytask-dev/pytask).
The changes allow for better detection, which are documented in the added tests.
- inspect-ai does not mistakingly assume all `@task` decorators specify an inspect task.
- `import inspect; @inspect.task`, `from inspect import task as t; @t`, and other patterns documented in the tests correctly identify an inspect task.
If all is correctly implemented, only false positives should be prevented.
I had to remove the linting stage from the pretest checks to enable running tests …

Implement better task detection for code lense commands.

---

src/inspect_ai/model/_call_tools.py

A tool call with an appropriately missing parameter still throws "Required parameter {param_name} not provided to tool call." from `tool_params`. For example, `text` is not required in calls to the following tool:
```python
async def execute(
action: str,
text: str | None = None,
coordinate: tuple[int, int] | None = None,
) -> ToolResult:
```
The `tool_params` code will no longer throw in this condition.

Update `tool_params` to support default values of `None` if supported by the type hint.

---

CHANGELOG.md
src/inspect_ai/model/_call_tools.py
src/inspect_ai/model/_providers/google.py
src/inspect_ai/tool/_tool_info.py
tests/tools/test_tool_types.py

A tool call with an appropriately missing parameter still throws "Required parameter {param_name} not provided to tool call." from `tool_params`. For example, `text` is not required in calls to the following tool:
```python
async def execute(
action: str,
text: str | None = None,
coordinate: tuple[int, int] | None = None,
) -> ToolResult:
```
The `tool_params` code will no longer throw in this condition.

support for tool parameters with a default of `None`

---

src/inspect_ai/_view/www/.prettierrc.js
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/App.mjs
src/inspect_ai/_view/www/src/Types.mjs
src/inspect_ai/_view/www/src/api/Types.mjs
src/inspect_ai/_view/www/src/api/api-http.mjs
src/inspect_ai/_view/www/src/components/ExpandablePanel.mjs
src/inspect_ai/_view/www/src/components/FindBand.mjs
src/inspect_ai/_view/www/src/components/LargeModal.mjs
src/inspect_ai/_view/www/src/components/TabSet.mjs
src/inspect_ai/_view/www/src/components/Tools.mjs
src/inspect_ai/_view/www/src/components/VirtualList.mjs
src/inspect_ai/_view/www/src/navbar/Navbar.mjs
src/inspect_ai/_view/www/src/samples/SampleDisplay.mjs
src/inspect_ai/_view/www/src/samples/SampleList.mjs
src/inspect_ai/_view/www/src/samples/SampleScoreView.mjs
src/inspect_ai/_view/www/src/samples/SampleScores.mjs
src/inspect_ai/_view/www/src/samples/SamplesDescriptor.mjs
src/inspect_ai/_view/www/src/samples/SamplesTab.mjs
src/inspect_ai/_view/www/src/samples/tools/SampleFilter.mjs
src/inspect_ai/_view/www/src/samples/tools/SelectScorer.mjs
src/inspect_ai/_view/www/src/samples/tools/SortFilter.mjs

This PR contains multiple non-user-visible changes to Inspect view. It is mostly (but not entirely) a subset of https://github.com/UKGovernmentBEIS/inspect_ai/pull/911.
The only substantial change is factoring `EvalDescriptor` out of `SamplesDescriptor`. The `EvalDescriptor` is computed once per eval and contains information that doesn't change with the selected score. The `SamplesDescriptor` is now focused on data that depends on the selected score. I find that this separation improves readability, it should make caching better, and it is required for the fancy filter which doesn't depend on the selected score.
This PR also contains a lot of new JSDoc type annotations and type fixes.
Finally, it adds a prettierrc to ensure that per-user prettier settings don't break formatting.
---
Bonus …

Factor EvalDescriptor out of SamplesDescriptor, improve JSDoc type annotations and more

---

CHANGELOG.md
src/inspect_ai/_util/transcript.py

We now only HTML escape lines that aren't within code bocks and when doing escaping only escape <, >, and &.

More fine grained HTML escaping for sample transcripts displayed in terminal

---

CHANGELOG.md
src/inspect_ai/model/_providers/openai.py

The openai provider seems to remap max_tokens to max_completion_tokens for o1-preview and o1-mini, but it doesn't for o1-2024-12-17 (because it currently doesn't use the generate_o1 helper since it's not text-based). This results in an error if you try to pass --max-tokens for an o1-2024-12-17 evaluation
If o1-full, the OpenAI provider remaps max_tokens to max_completion_tokens
No
The OpenAI API reference says `max_tokens` ["is now deprecated in favor of max_completion_tokens,"](https://platform.openai.com/docs/api-reference/chat/create#:~:text=This%20value%20is,series%20models.) but oddly `max_completion_tokens` doesn't seem to be always supported on previous models. I ran gpt-4o-mini on some test samples with `max_completion_tokens` in the params, and 7/20 (not 0%, nor 100%!?) of …

o1-full: remap max_tokens to max_completion_tokens

---

CHANGELOG.md
src/inspect_ai/model/_providers/openai.py
src/inspect_ai/model/_providers/openai_o1.py

Status codes are mapped to appropriate `StopReason`

Open AI: Handle additional bad request status codes

---

CHANGELOG.md
src/inspect_ai/_util/json.py

Since `~` and `/` have special meanings in JSON pointers (used in json patches), these characters are encoded when generating a patch. Since we’re manually interacting with json pointers in patches directly, we need to decode these values ourselves.
(https://www.rfc-editor.org/rfc/rfc6901)

Properly decode json pointers

---

CHANGELOG.md
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/samples/SampleList.mjs

Don’t show the input column header when there isn’t an input

---

CHANGELOG.md
src/inspect_ai/_eval/run.py

This PR addresses https://github.com/UKGovernmentBEIS/inspect_ai/issues/1078
Currently all sandboxes referenced by a task are initialised prior to running the task's samples. However, if sandboxes are provided at the sample level (as is done by Cybench and the GDM In House CTF evals) they all end up getting initialised even if some samples are filtered out. This PR moves some of our sample id logic to before sandbox initialisation, and then applies active filters (`--limit` and `--sample-id`) to the list of sandboxes to be initialised.
@dragonstyle Could you do a close review of this? I recall you and I originally introduced the `slice_dataset()` function and I want to make sure I'm not missing any subtleties.

sandboxes: apply dataset filters (limit and sample id) prior to sandbox initialisation

---

CHANGELOG.md
docs/typing.qmd
src/inspect_ai/log/_log.py
src/inspect_ai/util/_store.py
tests/solver/test_store_model.py

This PR implements typed wrappers for accessing the store and metadata fields in log samples. For example, given an eval log, you can manually construct a `Store` from a sample as follows:
```python
sample_store = Store(log.samples[0].store)
```
You can also use the `store_as()` and `metadata_as()` functions to reconstruct the Pydantic typed-wrappers for the store and metadata. For example:
```python
activity = log.samples[0].store_as(Activity)
metadata = log.samples[0].metadata_as(PopularityMetadata)
```
See the documentation on [sample data typing](https://inspect.ai-safety-institute.org.uk/typing.html) for additional details on Pydantic wrappers.

optional typed wrappers for store and metadata in log samples

---

CHANGELOG.md
src/inspect_ai/log/_recorders/eval.py

The eval recorder isn't properly capturing sample input for the sample summary when the sample input contains a simple string.

Properly preserve input when it is a string

---

CHANGELOG.md
src/inspect_ai/util/_sandbox/docker/util.py

When the 12th character of a task is an underscore, this leads to something like "inspect-evaluation_is_-abcdef". The "_-" breaks Docker for an unknown reason.
We now strip trailing underscores, so "evaluation_is_" becomes "evaluation_is", preventing the behaviour from occuring.
No.
This can easily be tested by using docker compose commands to create a name with _-, and identify it failing.

Fix Docker name breaking on _-

---

src/inspect_ai/model/_providers/openai.py
src/inspect_ai/model/_providers/openai_o1.py

o1 models use `max_completion_tokens` rather than `max_tokens`. We previously handled this separately for `o1-preview` and `o1-mini`, now the logic is consolidated.

consolidate o1 max tokens logic

---

src/inspect_ai/_util/logger.py

Reduce the matching of 429 so it will only match 429 with word boundaries around it (space, punctuation, start or end of string) rather than anywhere in string.
This reduces false positives on retries.

Improve 429 retry filtering

---

CHANGELOG.md
src/inspect_ai/_display/textual/widgets/samples.py
src/inspect_ai/log/_transcript.py
src/inspect_ai/model/_call_tools.py

Long running tool calls can now be timed out manually by the operator from the running sample display.

task display: timeout tool button for manually timing out a tool call

---

CHANGELOG.md
src/inspect_ai/model/_providers/hf.py

#1103 Error when using models that don't have a chat template.
We extract the role and content from messages without using chat template.
Doesn't support tool usage, but most likely such old models won't used for tool based evals.
None

Fixing error for HF models with no chat_template

---

CHANGELOG.md
src/inspect_ai/util/_sandbox/docker/compose.py
src/inspect_ai/util/_sandbox/docker/docker.py

Continuance of https://github.com/UKGovernmentBEIS/inspect_ai/pull/1111 (mypy lint + comment in compose_up on ignoring result status)

handle docker service exits during compose_up

---

CHANGELOG.md
src/inspect_ai/_util/thread.py
src/inspect_ai/util/_display.py

If we are on a background thread then throttle down to "plain" mode, as "full" requires textual which cannot run in a background thread, b/c it calls the Python signal function, and "rich" assumes exclusive display access which may not be the case for threads.

task display: automatically switch to "plain" mode when running in a background thread

---

docs/scorers.qmd
src/inspect_ai/scorer/__init__.py
src/inspect_ai/scorer/_metrics/__init__.py
src/inspect_ai/scorer/_metrics/std.py

Fixes the very confusing (arguably incorrect) name of the metric that computes the standard error of the mean via bootstrap. Also clarified the docstring.
The previous naming would lead to absurd outputs like:
```
╭─ math (50 samples): google/gemini-1.5-flash-002 ─────────────────────────────╮
│                                                                              │
│  stderr: 0.0714  std: 0.505  bootstrap_std: 0.0702                           │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
```
I understand that a breaking change is not ideal here, but the fact that `std` and `bootstrap_std` calculate two completely different things is pretty bad in my opinion.

Fix inconsistent naming of bootstrap standard error

---

CHANGELOG.md
src/inspect_ai/log/_recorders/eval.py
tests/log/test_log_formats.py

This only will occur when we rewrite an eval log file (e.g. overwrite an existing file with a new EvalLog) - we were reading summaries from the original file, then adding summaries as the new EvalLog was written, causing duplication.

Fix duplication of summaries when eval log file is rewritten

---

CHANGELOG.md
src/inspect_ai/_eval/task/run.py

i.e. errors permitted by the `fail_on_error` option

Log warning when a non-fatal sample error occurs

---

src/inspect_ai/model/_model.py

PR #1126 introduced an off-by-one error in message limits by changing `>=` to `>`.
This caused the following test in our codebase (and multiple others) to fail:
```python
def test_scheming_solver_message_limit():
custom_outputs = [
ModelOutput.from_content(
model="mockllm/model",
content="Message",
)
for _ in range(5)
]
model = get_model(
"mockllm/model",
custom_outputs=custom_outputs,
)
log = run_scheming_solver(
[ToolDef(addition())],
ExitCondition(None),
model=model,
message_limit=3,
)
assert log.samples is not None
messages = log.samples[0].messages
assert len(messages) == 3
assert log.status == "success"
```
I've reverted the change to the equality to remove the change in behaviour.
However, semantically it seems slightly strange because we are raising SampleLimit*Exceeded*Error if …

Fix off-by-one error in message limit

---

src/inspect_ai/_display/core/active.py
src/inspect_ai/_display/plain/display.py

The recent addition of `DisplayType` is a very welcome one, thank you.
I am especially interested in `plain` for plain-text logging and for use in environments where ANSI escape sequences are not supported.
No progress is shown in `plain` mode
This PR adds `PlainDisplay` and `PlainTaskDisplay`, inheriting from `Display` and `TaskDisplay`. They behave as follows:
* During an evaluation, progress is shown in plain text.
* At the start and end of an evaluation, information is shown once in `rich` panels. (The end-of-evaluation behaviour is identical to the current behaviour with `DisplayType` set to `rich`)
* No ANSI escape sequences are used
I care about having this functionality available in some form, but I don't feel strongly about the specific aesthetic choices. Feel free to amend what …

Improve display when `DisplayType` is `plain`

---

CHANGELOG.md
src/inspect_ai/_display/core/panel.py
src/inspect_ai/_display/plain/display.py
src/inspect_ai/_display/rich/display.py
src/inspect_ai/_util/text.py
tests/util/test_truncate.py

- Handle multiple models and multiple tasks (display task/model to disambiguate if required)
- Pad display so columns always line up
- Throttle updates to once every second
- Condense task panel when there is no body or footer
- Call rich_initialise in PlainDisplay constructor so ansi colors, etc. are disabled globally for rich printing.
- Remove spurious plain print from rich display (since plain now has its own display handler)
cc @tadamcz

Misc improvements to display=plain

---

src/inspect_ai/_display/plain/display.py

Caught this just after you merged https://github.com/UKGovernmentBEIS/inspect_ai/pull/1166
Previous:
```
Steps:   1/16   6% | Samples:   1/ 16 | accuracy:  n/a | google:  0/10openai:  9/10 | HTTP rate limits: 0
```
Fixed (comma-separated):
```
Steps:   1/16   6% | Samples:   1/ 16 | accuracy:  n/a | google:  0/10, openai:  9/10 | HTTP rate limits: 0
```
Feel free to make the separating character something else based on your taste (like a single space or a pipe)

Separate multiple resources in display=plain

---

CHANGELOG.md
src/inspect_ai/util/_sandbox/docker/prereqs.py

This commit updates the version parsing logic in prereqs.py to correctly handle Docker Compose version strings that include additional metadata.
The previous implementation failed to parse versions like 2.27.1+ds1-0ubuntu1~24.04.1, resulting in an invalid SemVer error.
Example:
```
WARNING  Unexpected error executing docker: 2.27.1+ds1-0ubuntu1~24.04.1 is not valid SemVer string                                                                                                                        prereqs.py:88
ERROR: Docker sandbox environments require Docker Engine
...
```
The updated logic removes the "v" prefix and separates the version string at the "+" character, additional metadata after the "+" character which might be included in the output of `docker compose version --format json` …

Fix invalid SemVer string parsing on Ubuntu

---

CHANGELOG.md
src/inspect_ai/_eval/score.py
src/inspect_ai/_eval/task/results.py
src/inspect_ai/_eval/task/run.py
src/inspect_ai/scorer/_metric.py

When a solver returns a score, we synthesize scorer info for it. The previous logic was using key/name matching to determine whether to synthesize scorer info. Instead, explicitly note the scorer that produced the SampleScore and only synthesize score info for sample scores whose scorer is None.
Fixes #1200

Explicitly handle scorers created from TaskState

---

CHANGELOG.md
src/inspect_ai/model/_providers/anthropic.py

For example, here we override `max_tokens`:
```python
from inspect_ai import Task, eval, task
from inspect_ai.dataset import Sample
from inspect_ai.scorer import exact
from inspect_ai.solver import generate
@task
def hello_world():
return Task(
dataset=[
Sample(
input="Just reply with Hello World",
target="Hello World",
)
],
solver=[
generate(),
],
scorer=exact(),
)
if __name__ == "__main__":
eval(
hello_world(),
model="anthropic/claude-3-5-sonnet-latest",
model_args={"extra_body": {"max_tokens": 1}},
)
```
You can also set `model_args` on the command line with careful quoting and removal of spaces:
```bash
inspect eval hello.py -M extra_body="{'max_tokens':1}"
```

Anthropic: Support for `extra_body` model arg (for adding additional JSON properties to the request)

---

CHANGELOG.md
src/inspect_ai/model/_providers/anthropic.py

I have observed Anthropic return an http standard [413 Content Too Large](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413). This PR catches that error and turns it into a more graceful stop message.

Handle Anthropic 413 http status code.

---

src/inspect_ai/log/_message.py

If you use `--log-level-transcript` with TRACE or DEBUG, runs fail because the pydantic model can't validate records with the `trace` log level
`inspect eval inspect_evals/blah --log-level-transcript TRACE --model ....`

Add trace logging level to log model

---

CHANGELOG.md
src/inspect_ai/scorer/_classification.py
tests/scorer/test_classification.py

This allows user to pass a list of stop words which will be normalized out of the text when processing.

Add `stop_words` param to f1 scorer

---

src/inspect_ai/util/_sandbox/self_check.py

On alpine the test_exec_as_user was failing because it's using busybox adduser
The test figures out which adduser is available and uses the appropriate syntax

Fix self_check: alpine test_exec_as_user

---

CHANGELOG.md
src/inspect_ai/scorer/_answer.py

This avoids a registry tagging error if the named param is used when using the answer scorer (duplicate arg type when tagging)

rename type param

---

CHANGELOG.md
docs/_shuffling-choices.md
docs/datasets.qmd
docs/solvers.qmd
src/inspect_ai/dataset/_dataset.py
src/inspect_ai/dataset/_sources/csv.py
src/inspect_ai/dataset/_sources/file.py
src/inspect_ai/dataset/_sources/hf.py
src/inspect_ai/dataset/_sources/json.py
src/inspect_ai/solver/_multiple_choice.py

This is the preferred way to shuffle choices for multiple choice question.
- The `shuffle` param of the multiple choice scorer is deprecated and will warn users.
- The `shuffle_choices` implementation will shuffle the choices within the sample and update the target as well, eliminating the need for any hijinks with target, scoring, and display (relating to unshuffling).
- The various dataset reading functions (e.g. `json_dataset`) take a new `shuffle_choices` param (or call `dataset.shuffle_choices()`

Shuffle Choices for Dataset

---

CHANGELOG.md
src/inspect_ai/model/_providers/anthropic.py

`400 BadRequestError`'s are not handled properly. #1234 regressed the behavior because it used the wrong order of `except` blocks. The rule is that they should be in most specific to most general order. Because `APIStatusError` is the base class of `BadRequestError`, the `400`'s were handled by the `APIStatusError` block essentially shadowing the more appropriate `BadRequestError` block.

Fix regression caused by inverted except block order.

---

src/inspect_ai/scorer/_common.py

This PR removes multiple snippets of the form
```
explanation = (
state.output.completion
if state.output.completion != answer
else None
)
```
from `str_match_scorer`, which is employed by both the `includes()` scorer and the `match()` scorer. The first instance of this snippet appears to be unused, while it looks like the second is irrelevant and `state.output.completion` can be used instead. (In the second case, the `match` function passed to `str_match_scorer` seems like it would have to be quite weird for `state.output.completion == answer` to trigger for the case of an *incorrect* score, which is what the second deleted snippet is addressing. Anyhow, it's likely useful for the completion to be returned as an explanation regardless.)

Clean up outdated / unused lines in common scorer code

---

CHANGELOG.md
src/inspect_ai/_eval/task/run.py

This change adds a transcript event when a solver score is recorded. This event will then be properly rendered by the log viewer, properly displaying the score when provided by a solver.

Event when scores provided by solver

---

docs/tools.qmd

Broken link to #sec-custom-images in configuration section, section anchor is #sec-custom-image
Updated anchor to #sec-custom-images
No

Fix typo in link in Tools doc

---

CHANGELOG.md
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/logfile/remoteZipFile.ts

As eval files get larger (approaching 4GB), the central directory will stop using 32 bit ints and instead use 64 bit ints to store offsets to byte ranges.
This is signaled by the file offset being a sentinel value, in which case we need to look through the extra fields to find the 64 bit offset and use that instead.
This change adds support for reading these large zip files.

Add Zip64 Support to JS Zip Reader

---

src/inspect_ai/model/_model.py

Exception is raised if a model responds with no choices (can be the case for content/safety violations)
Exception will not be raised as we don't try to access index 0 of empty list.
No
I'm not too familiar with the conversation display type behaviour and if not calling `conversation_assistant_message` in the case that there are no choices will have any adverse effects.
Lmk if it would be better to fabricate an empty `ChatMessageAssistant` to pass to `conversation_assistant_message()` instead!

Do not assume that `result.choices` will contain elements 

---

docs/sandboxing.qmd

The type checker gives an error if you do what the docs suggest and specify a list of strings. Instead, a `tuple[str, str]` is required, as can be seen [here](https://github.com/UKGovernmentBEIS/inspect_ai/blob/37befa145cf8034a7b38df9181f27028f74573e7/src/inspect_ai/util/_sandbox/environment.py#L295):
```
SandboxEnvironmentType = SandboxEnvironmentSpec | str | tuple[str, str]
```
In this PR, I change the relevant line of the docs to be consistent with this type specification.

Fix docs to suggest the correct type for sandbox

---

CHANGELOG.md
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/log-schema.json
src/inspect_ai/_view/www/src/components/AnsiDisplay.tsx
src/inspect_ai/_view/www/src/components/JsonPanel.tsx
src/inspect_ai/_view/www/src/samples/transcript/InfoEventView.tsx
src/inspect_ai/_view/www/src/samples/transcript/ScoreEventView.tsx
src/inspect_ai/_view/www/src/types/log.d.ts
src/inspect_ai/log/_transcript.py
src/inspect_ai/scorer/_score.py
src/inspect_ai/solver/_human_agent/commands/clock.py
src/inspect_ai/solver/_human_agent/commands/note.py
src/inspect_ai/solver/_human_agent/commands/score.py
tools/vscode/src/@types/log.d.ts

Addresses: https://github.com/UKGovernmentBEIS/inspect_ai/issues/1264
Addresses: https://github.com/UKGovernmentBEIS/inspect_ai/issues/1263
This PR adds additional event structure in order to add more granularity to human baselining logs:
1) Add an `intermediate` flag to `ScoreEvent` and log events with this flag whenever the `score()` function is called. This is now displayed in the transcript as follows:
2) Add a `source` field to `InfoEvent` and modify the human agent to log start/stop events using JSON rather than strings. This is now displayed in the transcript as follows:

improved events for scoring / human agent

---

src/inspect_ai/util/_sandbox/docker/config.py
tests/util/sandbox/test_sandbox_setup.py

(I'm not sure if this counts as a new feature or a bug fix. It allows for a wider convention of file naming for Dockerfiles.)
Currently, `is_dockerfile` does not detect files named `Dockerfile.{name}`. It only detects either `Dockerfile` or `{name}.Dockerfile`.
This relates to a secondary issue raised in #1321.
This PR causes `is_dockerfile` to return true on `Dockerfile.{name}` as well.
No. However, undoing this might constitute a breaking change.
Conventions often allow Dockerfiles to be named as `Dockerfile.{name}` (e.g. see [here](https://stackoverflow.com/questions/26077543/how-to-name-dockerfiles)).
However, I'm not completely sure this change is desirable. Are there reasons you might want users to not be able to specify a Dockerfile with a custom name that looks like a file …

Allow Dockerfiles to be named Dockerfile.{name}

---

CHANGELOG.md
src/inspect_ai/_util/format.py
src/inspect_ai/solver/_prompt.py
tests/solver/test_prompt.py
tests/util/test_format_template.py

Applies to `prompt_template()`, `user_message()`, and `system_message()` solvers.

prompt templates: Ignore template placeholders that don't map to passed parameters

---

CHANGELOG.md
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/samples/transcript/SubtaskEventView.tsx

Explicitly display that there are no inputs and no transcript events.
Related to #1329 (but does not resolve it)

Improve display for empty subtasks

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/samples/sample-tools/filters.ts
src/inspect_ai/_view/www/src/samples/sample-tools/sample-filter/SampleFilter.tsx
src/inspect_ai/_view/www/src/samples/sample-tools/sample-filter/completions.ts
src/inspect_ai/_view/www/src/samples/sample-tools/sample-filter/language.ts

1. Sample filter fails if the eval contains failed samples (only possible with `--no-fail-on-error`).
2. Impossible to filter samples with errors.
3. It is impossible to filter by scores that could be `None`.
4. Completions are sometimes duplicated.
1. Failed samples are considered to not match any score filter.
2. Can filter samples with errors via `has_error` and `error_contains()`.
3. It is possible to filter by a tristate score `foo: bool | None`. The filter expression should be `foo == True`, `foo == False` or `Foo == None`. Note that this is different from `foo: bool` score, where `foo == True` and `foo == False` still work, but the recommended form is just `foo` and `not foo`.
4. Completions are always unique.
No
—

Fix filtering in presence of sample errors and nullable scores

---

CHANGELOG.md
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/samples/transcript/TranscriptView.tsx

We currently don’t have a visual treatment for pending events, so they are appearing in the event stream and it can be confusing since they have no input or child events.
Fixes #1329

Filter pending events from transcript

---

CHANGELOG.md
src/inspect_ai/_display/plain/display.py

Would you be open to this change?
Prints on every integer percentage change, at most once every second.
This is not ideal because, for evaluations with many samples, 1% can take a long time, so it's hard to tell if the eval is completely stuck or just slow.
Print on every "step" change, at most once every 10 seconds. I'm open to other options.

PlainTaskDisplay: print on every step

---

CHANGELOG.md
src/inspect_ai/model/_providers/mistral.py
tests/tools/test_tool_types.py
tests/tools/test_tools.py
tests/tools/test_web_browser.py

The full test suite includes `--runapi` and `--runslow`, however due to cost/techincal constraints we don't currently run all of these in CI. Some of these additional tests have some non-determinism (due to models being erratic in their behavior) so when running the whole suite you can get failures due to various vagaries of model behavior.  This PR uses a combination of selective skipping and more flexible output checking to make `--runapi` and `--runslow` succeed or fail more deterministically.

make full test suite more deterministic

---

src/inspect_ai/util/_sandbox/self_check.py
tests/tools/test_web_browser.py

- accommodate that some shells output 'canceled\n' to stdout for aborted `yes` process
- pick a search target for web_browser_input which has less potential of trip ups for the model

runslow determinism

---

CHANGELOG.md
src/inspect_ai/util/_sandbox/docker/compose.py
src/inspect_ai/util/_sandbox/docker/docker.py

If a docker service fails to start, you get an opaque error message with no information about what went wrong.
Now you get to see the stderr of the docker compose up command
no
n/a

Add error feedback if docker services fail to start

---

CHANGELOG.md
requirements.txt

HF datasets maintains a manual upper bound of `fsspec` out of general paranoia that they'll be broken on upgrade: https://github.com/huggingface/datasets/issues/7326
This causes no issues for the default install of Inspect (which has no `datasets` dependency) however once `hf_dataset()` is used or Inspect Evals are in play then `datasets` is in play, and the user sees this (non-fatal) error when installing or updating `inspect_ai` alongside `datasets`:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 3.3.1 requires fsspec[http]<=2024.12.0,>=2023.1.0, but you have fsspec 2025.2.0 which is incompatible.
```
This PR matches the `datasets` upper bound (the …

align with HF datasets `fsspec` version contraints to avoid pip errors when installing alongside `datasets`

---

src/inspect_ai/solver/_basic_agent.py

Removed duplicate "may" in DEFAULT_SYSTEM_MESSAGE
The prompt contains the sentence "Each message may may perform one function call."
The sentence is now "Each message may perform one function call."
No
Minor typo

[MINOR] typo in _basic_agent.DEFAULT_SYSTEM_MESSAGE

---

src/inspect_ai/_util/logger.py

Relevant Slack thread is [here](https://inspectcommunity.slack.com/archives/C080K7SQ4SG/p1740066834687599).
Right now, if there are root logging handlers present before Inspect initialises its logger, they will receive all of the logs which Inspect is interested in (like DEBUG logs from botocore and TRACE logs from other libraries.) 
If root loggers are present, Inspect will remove them and also print a WARNING message to the console.
To test this, I ran the test pasted below, as well as imported this into the AS evaluation codebase and verified it fixed the issue.
If people had root logging handlers they depend on, they will break. While we could add a CLI option to disable this behavior, I don't think anyone depends on that behavior (and they'll get a ton of log spam from Inspect.) We …

Remove root logging handlers upon Inspect logger initialisation

---

CHANGELOG.md
src/inspect_ai/_eval/task/run.py
src/inspect_ai/solver/_basic_agent.py
src/inspect_ai/solver/_plan.py

`basic_agent()` no longer sets `completed` so can be used in longer compositions of solvers

only explicitly set `state.completed=True` when entering scoring

---

docs/reasoning.qmd
docs/reference/inspect_ai.model.qmd
src/inspect_ai/_display/textual/widgets/transcript.py
src/inspect_ai/_util/content.py
src/inspect_ai/_util/transcript.py
src/inspect_ai/_view/www/dist/assets/index.css
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/log-schema.json
src/inspect_ai/_view/www/src/samples/chat/ChatMessage.tsx
src/inspect_ai/_view/www/src/samples/chat/MessageContent.tsx
src/inspect_ai/_view/www/src/types/log.d.ts
src/inspect_ai/log/_condense.py
src/inspect_ai/log/_recorders/eval.py
src/inspect_ai/model/__init__.py
src/inspect_ai/model/_chat_message.py
src/inspect_ai/model/_conversation.py
src/inspect_ai/model/_model.py
src/inspect_ai/model/_openai.py
src/inspect_ai/model/_providers/google.py
src/inspect_ai/model/_providers/groq.py
src/inspect_ai/tool/__init__.py
src/inspect_ai/tool/_tool.py
tests/model/providers/test_google.py
tests/model/test_reasoning_content.py
tools/vscode/src/@types/log.d.ts

This PR introduces a new `ContentReasoning` content block type to represent reasoning yielded by models. This replaces the `reasoning` field we had previously added to `ChatMessageAssistant`. The new scheme accommodates additional properties of reasoning blocks (which will be required by Anthropic) and matches the way Anthropic represents reasoning (as a block that is a peer of text, images, etc.). Straightforward conversions to this schema are done for other models that use a simpler/flatter approach.

`ContentReasoning` to represent reasoning blocks

---

src/inspect_ai/model/_providers/openai.py

Right now, if we get 429 errors with the string "Request too large" in them, we will error the sample. Example error below:
```
Error code: 429 - {'error': {'message': 'Request too large for organization org-XXXXXXXXXXXXX on tokens per min (TPM): Limit 250000, Requested 546. The input or output tokens must be reduced in order to run successfully. Visit         https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}
```
I checked with OpenAI and they said 
> This is just another rate-limiting error, effectively 'Your prompt can't fit in your current rate limit allocation"
I haven't seen ones with "You exceeded your current quota" but I don't see why we wouldn't retry those as well.
These requests will be retried.
My …

Retry all OpenAI rate limit errors

---

src/inspect_ai/util/_sandbox/self_check.py

The sandbox behaviour isn't especially well defined for when the specified user for exec isn't found. The existing self_check test is overly coupled to the existing Docker implementation.
I think it's good enough to insist the exec returns failure, and that the erroneous username is somewhere in the result stdout/stderr. So the test is relaxed a bit in this PR.

Relax assertion in test_exec_as_nonexistent_user

---

docs/_model-providers.md
docs/providers.qmd
pyproject.toml

The documentation for model providers at https://inspect.ai-safety-institute.org.uk/providers.html does not contain instructions for how to use DeepSeek models.
* Adds a new section to the "Providers" docs with instructions for using DeepSeek models. Screenshots below, referencing @dragonstyle's instructions on Slack ([link](https://inspectcommunity.slack.com/archives/C080K7SQ4SG/p1741124519095879?thread_ts=1741124349.312469&cid=C080K7SQ4SG)). 
* Adds `griffe` as a `doc` dependency, since `pip install ".[doc]"` followed by `quarto render docs` gave me a dependency error that the `griffe` package was missing (it's used in `docs/reference/filter.py`).
No

Add documentation for DeepSeek

---

CHANGELOG.md
src/inspect_ai/_eval/task/images.py
src/inspect_ai/_view/www/log-schema.json
src/inspect_ai/_view/www/src/types/log.d.ts
src/inspect_ai/dataset/_sources/util.py
src/inspect_ai/model/_chat_message.py
src/inspect_ai/model/_model.py
src/inspect_ai/model/_providers/openai_o1.py
tests/model/test_tool_result_images_as_user_message.py
tools/vscode/src/@types/log.d.ts

The `id` defaults to `shortuuid.uuid()` and is assigned at creation.
The `id` is preserved during ordinary course of business transformations including:
1. When messages are combined to meet the constraints of APIs which prohibit consecutive user or assistant messages (in which case the `id` of the first message is used).
2. When messages are edited to base64 encode images or de-duplicate content.

Model API: `ChatMessage` now includes an `id` field

---

tools/vscode/CHANGELOG.md
tools/vscode/package.json
tools/vscode/src/providers/workspace/workspace-task-provider.ts

- Make the cache a persistent workspace cache
- Improve the perf by working more asynchronously
- Add log output to startup channel to track perf

VSCode: Improve startup performance task detection

---

src/inspect_ai/model/_providers/google.py
tests/model/providers/test_google.py

When FinishReason.MALFORMED_FUNCTION_CALL, Inspect raises inside `completion_choice_from_candidate` because `content.parts` is None
https://github.com/UKGovernmentBEIS/inspect_ai/blob/db5f35996129c4e9dea75433ba9cdee1d1960b48/src/inspect_ai/model/_providers/google.py#L560
Properly handle the case FinishReason.MALFORMED_FUNCTION_CALL. I decided to map it to `StopReason` "unknown", but I am also open to adding a new option to `StopReason` if that is preferred. 
Added a test

Google: handle FinishReason.MALFORMED_FUNCTION_CALL

---

CHANGELOG.md
src/inspect_ai/model/_openai.py

Some providers return content untagged -- as `{"type": "content"}` instead of `{"type": "type", "type": "content"}`.
Getting "type" unconditionally results in KeyError despite the actual content being present in the expected place.
`content_from_openai` will now check for such tagless (self-tagging?) encoding and use that single field as tag.
Additionally, the code now recognizes stand-alone "reasoning" content.
No.
The linter spots missing final `else:` clause which returns `None`, contrary to the type annotation.

Fix KeyError "type" for untagged content encoding

---

.github/workflows/docker.yml

Historically, we've manually run a makefile to build and push the tool (e.g. computer, web browser) images to Docker Hub. This often required coordination between multiple people (sometimes across timezones) as only @tcatling and myself have access to the relevant UK AISI secret used by the makefile.
This PR adds a GitHub workflow which can be triggered manually to allow trusted individuals (I suggest we copy whatever config we have for the PyPI workflow) to build and push these images as and when is needed.
We'll need to create 2 secrets in a new `docker` environment. I don't have admin permissions but am happy to share the secrets or create them myself if given admin access:
`DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`
This workflow supports all the same features the makefile does:
* …

Add docker GitHub workflow for building and pushing tool Docker images

---

CHANGELOG.md
src/inspect_ai/_view/server.py

triple is allowed, but fsspec and others normalize to double slash
Fixes #1499

Normalize windows URIs to double slash

---

CHANGELOG.md
src/inspect_ai/_view/server.py

The previous fix failed to decode url encoded params in non-file uris. Fixes #1499 Take 2.

Properly deal with windows triple slash uris in view server

---

CHANGELOG.md
src/inspect_ai/log/_transcript.py
tests/log/test_eval_log.py

This resolves the issue that @tbroadley kindly reported: when trying to serialise a `SubtaskEvent` which was deserialised from
```json
{
"timestamp": "2025-02-18T21:03:28.265168-08:00",
"working_start": 0,
"pending": true,
"event": "subtask",
"name": "test",
"input": {},
"events": []
}
```
Pydantic fails because the `SubtaskEvent` serialisation function assumes that `completed` is always non-`None` (despite the schema types specifying it as optional).
I've made similar fixes to `ToolEvent` and `SandboxEvent`. `ModelEvent` already handled this correctly (but I fixed the type hint).

Fix `SubtaskEvent` deserialisation error when `completed` is unset

---

.github/workflows/docker.yml

See #1498 for more context - just updating this to include the new `inspect-tool-support` image.

Add `inspect-tool-support` image to Docker Hub workflow

---

src/inspect_ai/util/_sandbox/docker/config.py
src/inspect_tool_support/CHANGELOG.md
src/inspect_tool_support/MANIFEST.in
src/inspect_tool_support/pyproject.toml
src/inspect_tool_support/src/inspect_tool_support/_remote_tools/_bash_session/bash_process.py
src/inspect_tool_support/src/inspect_tool_support/_util/_json_rpc_helpers.py

- `bash_session` commands whose `stdout` output did not end in a newline character, would cause an eval to fail.
- Unexpected errors in the `inspect-tool-support` container code yield an inspect side error with no details.
- `bash_session` now properly supports lack of a trailing newline.
- Exception details are now properly marshaled back to the Inspect process via a fleshed out JSON RPC error.
No

Fast follow changes to for the tool support functionality.

---

CHANGELOG.md
src/inspect_ai/_eval/registry.py

When a task does not take a kwargs argument, warnings should only be raised if the provided argument is not valid.
If a task does not define a `kwargs` parameter, warnings will be generated for every `-T` argument set.
Consider a file `mytask.py` that defines a task, `sometask`
```py
@task
def sometask(some_arg = None):
...
```
Running `inspect eval mytask.py -T some_arg=foo` will print an incorrect warning
```
WARNING  param 'some_arg' not used by task 'sometask'
```
A warning will only be printed if the task method does not take the specified argument AND does not take a `kwargs` argument.
Something unchanged by this PR but perhaps notable is that the check here is focused on an argument _named_ kwargs, if someone defined a method using a different name with the same `**` syntax, the …

fix incorrect warning when parsing task arguments

---

src/inspect_ai/model/_providers/openai.py

Other providers that subclass from us like together expect to have the qualifier in the model name, e.g. `google/gemma-2b-it`
cc @andrew-aisi

only remove model_name prefix for azure service

---

.vscode/launch.json
src/inspect_ai/_view/www/log-schema.json
src/inspect_ai/_view/www/src/types/log.d.ts
src/inspect_ai/log/_transcript.py
src/inspect_ai/model/_call_tools.py
src/inspect_ai/model/_chat_message.py
src/inspect_ai/model/_model.py
src/inspect_ai/model/_model_output.py
src/inspect_ai/model/_openai.py
src/inspect_ai/model/_providers/anthropic.py
src/inspect_ai/tool/_tool_call.py
tests/tools/test_tool_internal_name.py
tools/vscode/src/@types/log.d.ts

As mentioned by @jeremyschlatter in #1507 [here](https://github.com/UKGovernmentBEIS/inspect_ai/issues/1507#issuecomment-2735383777) our built-in tool name rewriting code left misleading information in the chat history sent back to the model. 
We now translate back to the model/native tool name when writing `ChatMessageTool`'s into the history.

Transform Inspect tool name back to model native name if needed when creating `ChatMessageTool`'s.

---

CHANGELOG.md
docs/options.qmd
src/inspect_ai/_cli/eval.py
src/inspect_ai/_eval/eval.py
src/inspect_ai/_eval/evalset.py
src/inspect_ai/_eval/run.py
tests/test_metadata.py

note that tasks can also contribute metadata, which is merged with the eval metadata in the log

`--metadata` option to eval for associating metadata with eval runs

---

CHANGELOG.md
docs/providers.qmd
src/inspect_ai/model/_providers/mistral.py
src/inspect_ai/model/_providers/openai.py

e.g. `openai/azure/gpt-4o-mini` or `mistral/azure/Mistral-Large-2411`
Also improve documentation to provide examples that match expected semantics and clarify that the deployment target is Azure AI Foundary.

AzureAI: Support for use of native OpenAI and Mistral clients using service qualifiers

---

CHANGELOG.md
docs/_tools-standard.md
docs/reference/_sidebar.yml
docs/reference/inspect_ai.tool.qmd
docs/tools-standard.qmd
src/inspect_ai/tool/__init__.py
src/inspect_ai/tool/_tool.py
src/inspect_ai/tool/_tools/_think.py
tests/tools/test_think_tool.py

Based on <https://www.anthropic.com/engineering/claude-think-tool>
The `think()` tool provides models with the ability to include an additional thinking step as part of getting to its final answer. 
Note that the `think()` tool is not a substitute for reasoning and extended thinking, but rather an an alternate way of letting models express thinking that is better suited to some tool use scenarios. 
You should read the original [think tool article](https://www.anthropic.com/engineering/claude-think-tool) in its entirely to understand where and where not to use the think tool. In summary, good contexts for the think tool include:
1. Tool output analysis. When models need to carefully process the output of previous tool calls before acting and might need to backtrack in its approach;
2. …

`think()` tool that provides models with the ability to include an additional thinking step

---

docs/tutorial.qmd

#1183 , #1283 , #1526 
The eval runs on the updated dataset
Ran this on 50/12500 tests. Here is a snapshot from `inspect eval maths.py`

Update competition math dataset

---

src/inspect_ai/model/_openai_responses.py

In the case of invalid prompt errors, Inspect will handle them using openai_handle_bad_request in the generic provider. Invalid Prompt responses are coded with the `invalid_prompt` code, which causes the OpenAI provider to return a `ModelOutput` without an ID but with content present.
In this case, because we are deserialising from the response, Inspect will generate a message UUID for that message. However, when we go to pass this back to the Responses API, it is lacking the `msg_` prefix and therefore causes an API error.
Normally, the old API doesn't seem to be sensitive to ID formatting, though the new Responses API does seem to be pretty sensitive. Note that even though we are randomly generating these IDs, OpenAI doesn't seem to care, likely because we are using the `store=False` …

Ensure OpenAI Responses API assistant message IDs start with msg_ 

---

src/inspect_ai/_eval/run.py

In the event of multiple tasks, the previous version was recording the scorer/metric specs for the first task only (and using it as the spec for all subsequent tasks). This corrects this to use the correct spec for each task.

Properly record the score spec

---

CHANGELOG.md
src/inspect_ai/_view/www/src/logfile/remoteZipFile.ts

When log data is being proxied by Cloudflare the HEAD request to fetch the content size will not contain the `Content-Length` field (this is valid HTTP, so other servers might behave the same way).
This falls back to performing a 1 byte Range request instead and uses the `Content-Range` response header to get the content length. This is still not guaranteed to return the full content size, but it is more likely to do so than the HEAD request.
When opening log files proxied by Cloudflare you get an ugly error `Error: Failed to read or parse file _journal/start.json: File not found: _journal/start.json`
Opening log files work.
No.

Make remoteZipFile handle Content-Length not being present in HEAD

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/samples/chat/MessageContent.tsx

This will prevent a 'Reasoning' header from appearing in the message view when the reasoning is empty.

Omit empty reasoning

---

CHANGELOG.md
docs/log-viewer.qmd
src/inspect_ai/_view/www/src/logfile/remoteZipFile.ts

Improve the documentation and error message when the statically bundled viewer is served from a server which is ignoring the HTTP range requests that we are making.
Addresses #1557

Better deal with non-range request servers

---

docs/_sandbox-dockerfile.md
src/inspect_ai/tool/_tool_support_helpers.py
src/inspect_tool_support/Dockerfile

When using the suggested `Dockerfile` commands for `inspect-tool-support`, the image's default Python environment is overridden with the `inspect-tool-support`'s virtual env. This is because the directory is put at the front of `PATH` instead of at the end.
It's not put at the end.

Update `inspect-tool-support` Dockerfile and documentation to put tool directory at the end of the path rather than the front.

---

CHANGELOG.md
src/inspect_ai/tool/_tools/_web_browser/_web_browser.py

When current versions of the Inspect web browser tool are executed against the old/deprecated Docker image, it fails because the tool call parameters are not passed through the `docker exec` properly.
They are now passed properly.

Fix parameter passing bug that prevented the backward compatibility code for the web browser tool from working properly.

---

CHANGELOG.md
src/inspect_ai/util/_sandbox/docker/docker.py

Was failing on files > 2MB due to stdout interleaving with stdin. Fix was to redirect `tee` to `/dev/null` (as is already done for binary files). 
A broader fix would be to enhance `run_command()` to interleave stdin and stdout but this is riskier, more intrusive change so not pursuing this for the time being.

Docker: `write_file()` function now gracefully handles larger input file sizes

---

src/inspect_ai/agent/_human/commands/clock.py
src/inspect_ai/agent/_human/service.py

#1592 contained a bug: The initial event it records has an action of `pause` when it should be `stop`, to match the other actions it records.
`human_agent` now uses an action of `stop`, as it should.
No.
N/A

Fix human_agent initial clock event action

---

src/inspect_ai/agent/_human/state.py
tests/agent/_human/test_state.py

`test_human_agent_state_time_accumulation` fails at least occasionally in CI: https://github.com/UKGovernmentBEIS/inspect_ai/actions/runs/14237922878/job/39900932495
This PR changes the test not to use `time.sleep` to advance the clock, but instead to mock `time.time`.
No.
None.

Fix test_human_agent_state_time_accumulation

---

CHANGELOG.md
src/inspect_ai/agent/_react.py
src/inspect_ai/solver/_basic_agent.py
tests/agent/test_agent_react.py
tests/solver/test_basic_agent.py

This PR addresses the same core issue in closed PR #1608.
Currently, when using the basic_agent, anytime the agent uses the submit tool to submit an answer, we overwrite the completion with the contents of the submit tool. This allows scorers to check the completion when determining whether to continue the agent. This also has the side effect of overwriting any other contents of the completion that the model may have included when calling the submit tool (for example thinking or analysis as context for the submit tool call).
This PR has two changes to address this:
1) The `react` agent will now always just append the submit tool to the completion text, preserving any model output that accompanied the tool call.
2) The `basic_agent` now has an option to append the submitted text to the …

Append `submit` tool output

---

src/inspect_ai/_display/textual/widgets/task_detail.py
src/inspect_ai/_display/textual/widgets/tasks.py
src/inspect_ai/_display/textual/widgets/vscode.py
src/inspect_ai/_util/file.py
src/inspect_ai/_util/vscode.py
src/inspect_ai/_view/server.py
tools/vscode/src/providers/openlog.ts

This PR introduces a new link in the task progress display (when running in VSCode) which will open the log file for a running log (requires version 0.3.60 of the VSCode extension):
When clicked, opens the selected log with live updating as the eval runs:

View Log Link in Task Progress

---

src/inspect_ai/scorer/_metrics/grouped.py

I think there is a missing decorator from the grouped metric. Minimal failing example:
```python
from inspect_ai import Task, task
from inspect_ai.dataset import example_dataset, FieldSpec
from inspect_ai.scorer import model_graded_fact
from inspect_ai.solver import chain_of_thought, generate
from inspect_ai.scorer import Scorer, scorer, grouped, accuracy
@task
def biology_qa():
dataset = example_dataset("biology_qa",
FieldSpec("question", "answer"))
for sample in dataset:
sample.metadata = {"group_label": sample.id in ("q1", "q2", "q3")}
return Task(
dataset=dataset,
solver=[chain_of_thought(), generate()],
scorer=grouped_model_graded_fact()
)
@scorer(metrics=[grouped(accuracy(), "group_label")])
def grouped_model_graded_fact() -> Scorer:
return model_graded_fact()
```
Returns:
```
The …
```

Add metric decorator to grouped

---

src/inspect_ai/_display/textual/widgets/vscode.py

This prevents link clicks resulting in an open browser window (seen intermittently on linux and windows)

Suppress link click behavior in vscode links

---

src/inspect_ai/log/_recorders/buffer/database.py

https://inspectcommunity.slack.com/archives/C080K7SQ4SG/p1744204399673029
```
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Cleaning up Docker environments (please do not interrupt this operation!):                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ run_eval_with_single_mode (473 samples): anthropic/claude-3-5-sonnet-latest ────────────────────────────────────────────────────────╮
│ ╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮             │
│ │ …
```

Bugfix: Fix sqlite row value misused exceptions

---

CHANGELOG.md
docs/approval.qmd
docs/extensions.qmd
examples/approval/approval.py
src/inspect_ai/approval/_apply.py
src/inspect_ai/approval/_approver.py
src/inspect_ai/approval/_auto.py
src/inspect_ai/approval/_call.py
src/inspect_ai/approval/_human/approver.py
src/inspect_ai/approval/_human/manager.py
src/inspect_ai/approval/_human/panel.py
src/inspect_ai/approval/_policy.py
src/inspect_ai/model/_call_tools.py

This enables approvers to get the full conversation history for sub-agents

Approval: Approvers now take `history` argument (rather than `TaskState`)

---

tests/test_sample_limits.py

The `solver` parameter to `check_message_limit()` was unused which I think is unintentional as currently `test_message_limit_generate`, `test_message_limit_append`, `test_message_limit_overwrite` run exactly the same eval.
Once the passed solver is correctly used, `test_message_limit_overwrite` fails because it is "blocked" from overwriting the `TaskState.messages: ChatMessageList` with a list longer than `message_limit`. So `assert len(messages) == message_limit` fails e.g. `1 != 6`. I've adapted the solver to overwrite incrementally, but lmk if this was not the intention of the test!

Fix `test_message_limit_*` tests

---

pyproject.toml
src/inspect_ai/_eval/run.py
src/inspect_ai/tool/_tool_def.py
src/inspect_tool_support/pyproject.toml
src/inspect_tool_support/src/inspect_tool_support/_remote_tools/_web_browser/cdp/dom_snapshot.py
src/inspect_tool_support/src/inspect_tool_support/_remote_tools/_web_browser/playwright_page_crawler.py

Introduces a lint check to catch issues, including late binding closure bugs and resolves two existing bugs in the codebase.
I added the entire [flake8-bugbear](https://github.com/PyCQA/flake8-bugbear?tab=readme-ov-file#list-of-warnings) class of rules to our ruff configuration. I then opted out of noisy/marginal rules.
See:
- [Late binding closures](https://docs.python-guide.org/writing/gotchas/#late-binding-closures)
- [Why do lambdas defined in a loop with different values all return the same result?](https://docs.python.org/3/faq/programming.html#why-do-lambdas-defined-in-a-loop-with-different-values-all-return-the-same-result)

Added lint check to catch (among other things) late binding closure bugs and fixed two extant bugs.

---

CHANGELOG.md
docs/_model-providers.md
docs/providers.qmd
src/inspect_ai/agent/_bridge/bridge.py
src/inspect_ai/model/_openai.py
src/inspect_ai/model/_providers/grok.py
src/inspect_ai/model/_providers/llama_cpp_python.py
src/inspect_ai/model/_providers/ollama.py
src/inspect_ai/model/_providers/openai.py
src/inspect_ai/model/_providers/openai_compatible.py
src/inspect_ai/model/_providers/openrouter.py
src/inspect_ai/model/_providers/providers.py
src/inspect_ai/model/_providers/together.py
tests/model/providers/test_openai_compatible.py
tests/test_helpers/utils.py

If your model provider makes an OpenAI API compatible endpoint available, you can use it with Inspect via the `openai-api` provider, which uses the following model naming convention:
```
openai-api/<provider-name>/<model-name>
```
Inspect will read environment variables corresponding to the api key and base url of your provider using the following convention (note that the provider name is capitalized):
```
<PROVIDER-NAME>_API_KEY
<PROVIDER-NAME>_BASE_URL
```
Together already has it's own Inspect provider but is still useful for purposes of demonstrating the `openai-api` provider since it implements an OpenAI compatible endpoint. Here's how you would interface with Together using the `openai-api` provider:
```bash
TOGETHER_API_KEY=<your-together-api-key> …
```

openai-api model provider for interfacing with arbitrary services that have Open AI API compatible endpoints

---

CHANGELOG.md
src/inspect_ai/agent/_agent.py

Running `inspect eval mytask.py --solver mysolver.py` with the following two files produces an error
`TypeError: object function can't be used in 'await' expression `
mytask.py:
```py
from inspect_ai import Task, task
from inspect_ai.dataset import Sample
from inspect_ai.solver import generate
@task
def test_agent_react_ctf():
task = Task(
dataset=[Sample(input="Submit the flag 'hello'.")],
solver=generate(),
sandbox="docker",
max_messages=5,
)
return task
```
mysolver.py:
```py
from __future__ import annotations # XXX Remove this line and the error goes away
from inspect_ai.agent import Agent, agent, react
@agent
def ctf_agent(attempts=1) -> Agent:
return react(
description="Expert at completing cybersecurity challenges.",
prompt="Submit any flag",
tools=[],
attempts=attempts,
)
```
The …

Fix agent decorator to work with imported annotations

---

src/inspect_ai/model/_call_tools.py

Fix call_tools: ensure result_exception is always set

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/plan/ModelCard.tsx

Error introduced when processing model roles - old logs will not produce a config (despite the type system asserting this is required).

Fix null ref in model card

---

src/inspect_ai/agent/_react.py
tests/agent/test_agent_react.py

- Keep `submit()` tool invocations in the history presented to model (so that it doesn't think it can answer w/o the `submit()` tool)
- Remove `submit()` tool invocations in messages yielded from agent at the end of the loop (so that parent agents aren't confused by `submit()` executed in child agents)
- When `on_continue` returns `True` and there were no tool calls, automatically include the default continue message (otherwise the message history is invalid b/c it ends with an assistant message)

improvements to react agent submit and continue handling

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/samples/transcript/state/StateEventView.tsx

This reverts commit e534e0642f1bc188471cc51df856440b92fa9311. This fix introduces rendering issues (for example system message rendering is broken) and is not necessary (the real root issue was an assumption that numeric keys meant lists when generating the log files).
This fix is superceded by https://github.com/UKGovernmentBEIS/inspect_ai/pull/1654

Revert "Fix support for nested arrays"

---

CHANGELOG.md
docs/providers.qmd
docs/reasoning.qmd
src/inspect_ai/_cli/eval.py
src/inspect_ai/model/_generate_config.py
src/inspect_ai/model/_openai.py
src/inspect_ai/model/_openai_responses.py
src/inspect_ai/model/_providers/openai.py
src/inspect_ai/model/_providers/openai_responses.py
tests/model/providers/test_openai_responses.py
tests/model/test_reasoning_openai.py
tests/test_helpers/utils.py

- Responses API is now used by default for all reasoning models.
- `reasoning_summary` generation option for reasoning models.
- `responses_store` model argument to control whether the `store` option is enabled (it is enabled by default for reasoning models to support reasoning playback).

openai: support for new reasoning models + reasoning summaries

---

CHANGELOG.md
src/inspect_ai/model/_call_tools.py
src/inspect_ai/model/_providers/google.py
src/inspect_ai/tool/_tool_def.py
src/inspect_ai/util/_json.py
tests/tools/test_call_tools.py
tests/tools/test_tool_parse.py

Currently tools with `datetime`, `date`, `time`, `set`/`Set`, or `Any` arguments are first all translated to an empty JSONSchema spec (which is correct for `Any`, but loses a lot of information for the other three argument types). A little bit later in the flow they are then all rejected without any good reason.
Translates `datetime`, `date`, and `time` into string arguments with date-time/date/time format specifiers.
`Set` is translated into an array.
Allows the empty JSONSchema for `Any` and unknown types.
It should only allow some tools than weren't previously allowed.

Handle tools with datetime, date, time, Set, or Any arguments

---

CHANGELOG.md
src/inspect_ai/util/_sandbox/docker/docker.py

This will ensrue that they are still cleaned up even if interrupted during startup.

docker: register samples for cleanup immediately

---

src/inspect_ai/_eval/task/log.py
src/inspect_ai/_view/www/dist/assets/index.css
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/app/appearance/icons.ts
src/inspect_ai/_view/www/src/app/samples/SampleDisplay.tsx
src/inspect_ai/_view/www/src/app/samples/SampleSummaryView.tsx
src/inspect_ai/_view/www/src/app/samples/descriptor/samplesDescriptor.tsx
src/inspect_ai/_view/www/src/app/samples/descriptor/types.ts
src/inspect_ai/_view/www/src/app/samples/list/SampleHeader.tsx
src/inspect_ai/_view/www/src/app/samples/list/SampleList.tsx
src/inspect_ai/_view/www/src/app/samples/list/SampleRow.module.css
src/inspect_ai/_view/www/src/app/samples/list/SampleRow.tsx
src/inspect_ai/_view/www/src/app/samples/sample-tools/filters.ts
src/inspect_ai/_view/www/src/app/samples/sample-tools/sample-filter/SampleFilter.tsx
src/inspect_ai/_view/www/src/app/samples/sample-tools/sample-filter/language.ts
src/inspect_ai/_view/www/src/client/api/types.ts
src/inspect_ai/_view/www/src/constants.ts
src/inspect_ai/log/_recorders/eval.py
src/inspect_ai/log/_recorders/types.py

Support for displaying sample retries in the viewer, including display in the sample list, sample summary, and a new errors tab for displaying the errors that caused the retries. Filter to samples with retries using `has_retries` (or the opposite using `not has_retries`).

Display Sample Retries in Viewer

---

src/inspect_ai/_view/www/dist/assets/index.css
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/app/samples/SampleDisplay.module.css
src/inspect_ai/_view/www/src/app/samples/SampleDisplay.tsx

Introduce a single ‘errors’ tab that will display retry errors and/or the final sample error (if there is a final sample error, it will be displayed first).

Consolidate errors tabs

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/app/log-view/LogViewContainer.tsx
src/inspect_ai/_view/www/src/app/samples/InlineSampleDisplay.tsx
src/inspect_ai/_view/www/src/app/samples/SampleDisplay.tsx
src/inspect_ai/_view/www/src/app/samples/descriptor/samplesDescriptor.tsx
src/inspect_ai/_view/www/src/state/appSlice.ts
src/inspect_ai/_view/www/src/state/hooks.ts

- Improved layout for samples- failure to initialize can cause column layout issues. Introduced today when adding retries column.
- Don't unintentionally show the errors tab when there are no errors or retries
- Fix flash of error when switching from single sample log to multiple sample log
- Fix excessive sample loading (wouldn't be apparent, but wasteful) when viewing a single sample eval using the log route.

Properly initialize column sizes

---

src/inspect_ai/_eval/evalset.py

`retry_on_error` is not used when using the `eval_set()` function. So by default `eval_set` cannot set the number of per-sample retry attempts.
This passes `retry_on_error` to `eval()` so that you can set the number of per-sample retries.
n/a

pass retry_on_error from eval_set() to eval()

---

CHANGELOG.md
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/client/storage/index.ts

It uses JSON serialization internally which can’t deal with Nan, so take over serialization and use JSON5 as we do everywhere else.
Fixes #1747

takeover vscode storage serialization

---

src/inspect_tool_support/pyproject.toml
src/inspect_tool_support/src/inspect_tool_support/_in_process_tools/_text_editor/text_editor.py

If an agent calls the text editor tool in view mode and specifies an end line number that's larger than number of lines in the file, it will get an error. If the agent tries to use the tool to view a directory and specifies line numbers, it will get an error.
To improve model performance, I believe it's better for us to just ignore these errors and instead show the model what it asked for - in the first case the contents of the file up to the end. In the second case, the contents of the directory.
The current text_editor tool's view logic will fall apart if a model tries reading a binary file. Maybe not a big surprise given that it is a **text** editor, but perhaps something worth improving. It might also have issues with very long lines.
In the binary file case, converting to a hex dump …

More flexible text editor

---

src/inspect_ai/util/_sandbox/docker/compose.py
tests/util/sandbox/sandbox_setup_symlink.sh
tests/util/sandbox/test_sandbox_setup.py

Trying to read a symlink from within a docker sandbox will raise a RuntimeError, even though the file exists. E.g.,
```
┌───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────┐
│ /home/dev/git/inspect_ai/src/inspect_ai/_eval/task/run.py:667 in task_run_sample                                     │
│                                                                                                                      │
│ /home/dev/git/inspect_ai/src/inspect_ai/solver/_plan.py:106 in __call__                                              │
│                                                                                                                      │
│ /home/dev/git/inspect_ai/src/inspect_ai/agent/_as_solver.py:56 in solve …
```

Follow symlinks when reading files from docker sandbox

---

CHANGELOG.md
docs/eval-logs.qmd
docs/reference/_sidebar.yml
docs/reference/inspect_ai.log.qmd
src/inspect_ai/_eval/task/log.py
src/inspect_ai/_eval/task/run.py
src/inspect_ai/log/__init__.py
src/inspect_ai/log/_file.py
src/inspect_ai/log/_log.py
src/inspect_ai/log/_recorders/__init__.py
src/inspect_ai/log/_recorders/buffer/database.py
src/inspect_ai/log/_recorders/buffer/filestore.py
src/inspect_ai/log/_recorders/buffer/types.py
src/inspect_ai/log/_recorders/eval.py
src/inspect_ai/log/_recorders/file.py
src/inspect_ai/log/_recorders/recorder.py
src/inspect_ai/log/_recorders/types.py
src/inspect_ai/log/_transcript.py
src/inspect_ai/log/_util.py
tests/log/test_log_eventdb.py
tests/log/test_log_eventdb_sync.py
tests/log/test_log_summaries.py

`read_eval_log_sample_summaries()` enables reading summary level information about samples (input, target, error status, and scoring) from a log file.  This will be considerably higher performance than reading the entire log.
For example:
```python
from inspect_ai.log import read_eval_log_sample_summaries
summaries = read_eval_log_sample_summaries(log_file)
```
Some sample data is "thinned" in the interest of keeping the summaries small: images are removed from `input`, `metadata` is restricted to scalar values (with strings truncated to 1k), and scores include only their `value`.
Reading only sample summaries will take orders of magnitude less time than reading all of the samples one-by-one, so if you only need access to summary level data, always prefer this function to reading the …

`read_eval_log_sample_summaries()` function for reading sample summaries from eval logs

---

CHANGELOG.md
src/inspect_ai/_view/www/log-schema.json
src/inspect_ai/_view/www/src/@types/log.d.ts
src/inspect_ai/tool/_tool_call.py
tests/log/test_eval_log.py
tests/log/test_eval_log/log_tool_call_error.json

Fixes #1777 
This issue was introduced in #1737
I've added a regression test to prevent this sort of issue in future.

Ensure old log files with `output_limit` can be loaded

---

src/inspect_ai/_cli/eval.py

Calling `eval retry` from the command line throws an error
```txt
inspect eval-retry logs/2025-04-29T16-20-17+10-00_cybench_iEuY7tm6PYZvLZB8C5taB5.eval
Traceback (most recent call last):
File "/Users/matt/Developer/inspect_ai/inspect_evals_scoring/.venv/bin/inspect", line 8, in <module>
sys.exit(main())
~~~~^^
File "/Users/matt/Developer/inspect_ai/inspect_ai/src/inspect_ai/_cli/main.py", line 56, in main
inspect(auto_envvar_prefix="INSPECT")  # pylint: disable=no-value-for-parameter
~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/matt/Developer/inspect_ai/inspect_evals_scoring/.venv/lib/python3.13/site-packages/click/core.py", line 1161, in __call__
return self.main(*args, **kwargs)
~~~~~~~~~^^^^^^^^^^^^^^^^^
File "/Users/matt/Developer/inspect_ai/inspect_evals_scoring/.venv/lib/python …
```

Add `--no-log-realtime` option to `eval_retry_command`

---

src/inspect_tool_support/CHANGELOG.md
src/inspect_tool_support/pyproject.toml
src/inspect_tool_support/src/inspect_tool_support/_remote_tools/_web_browser/controller.py
src/inspect_tool_support/src/inspect_tool_support/_remote_tools/_web_browser/playwright_page_crawler.py

Web browser code properly waited for potential navigation triggered by a click action, but it neglected to wait when the action was a submit. 
It now waits with the same code on a submit.
`_click_and_await_navigation` was generalized to `_await_navigation_after_action` and is now shared between `click` and `submit`.
Fixes #1734

Fix web browser bug (#1734) caused by not properly awaiting navigation on a submit operation.

---

CHANGELOG.md
src/inspect_ai/_eval/eval.py
src/inspect_ai/_eval/evalset.py
src/inspect_ai/_eval/run.py
tests/test_sample_id.py

e.g. `--sample-id=popularity:10,security:5`

`--sample-id` option can now include task prefixes

---

src/inspect_ai/model/_providers/openai_o1.py
tests/model/providers/test_openai_o1.py

* Update tool_call_content_regex pattern in o1 provider to be symmetric to tool_call_regex
* Update comments to attempt to avoid future decoupling

Update o1 provider tool call regex patterns

---

src/inspect_tool_support/.bumpversion.cfg
src/inspect_tool_support/README.md
src/inspect_tool_support/make-release-commit
src/inspect_tool_support/pyproject.toml

This PR automates the changelog generation and release commit creation process by adding configuration for towncrier and a release script.
- Added towncrier configuration in pyproject.toml to manage changelog entries.
- Introduced the make-release-commit Python script to determine version bumps, build the changelog, and update the version using bump2version.
- Updated README.md to document the new release process.

Add process for automating changelog generation and release commit creation.

---

CHANGELOG.md
docs/reasoning.qmd
src/inspect_ai/model/_providers/anthropic.py

By default, streams when using extended thinking.

anthropic:`streaming` model argument to control whether streaming API is used

---

CHANGELOG.md
src/inspect_ai/agent/_react.py
src/inspect_ai/agent/_types.py

Used to control how submitted answers are reflected in the assistant message content.

React agent: `answer_only` and `answer_delimiter` options

---

CHANGELOG.md
src/inspect_ai/_eval/task/run.py
src/inspect_ai/_util/working.py

Now matches behavior of other sample limits.

Don't enforce sample `working_limit` after sovlers have completed executing

---

CHANGELOG.md
src/inspect_ai/util/_sandbox/events.py

eases compatibility with older sandbox providers

only pass `user` parameter on to sandboxes if is not `None`

---

CHANGELOG.md
src/inspect_ai/_view/www/dist/assets/index.css
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/package.json
src/inspect_ai/_view/www/src/components/ExpandablePanel.module.css
src/inspect_ai/_view/www/src/components/ExpandablePanel.tsx
src/inspect_ai/_view/www/yarn.lock

The panel is capped at 15rem, so we should be computed based upon font size rather than line-height

Properly compute whether to show toggle

---

CHANGELOG.md
src/inspect_ai/model/_providers/anthropic.py

`RuntimeError: BadRequestError('Error code: 400 - {\'type\': \'error\', \'error\': {\'type\': \'invalid_request_error\', \'message\': "\'claude-3-5-sonnet-20240620\' does not support tool types: text_editor_20250124."}}'`
This is because Anthropic uses slightly different tool schema names between 3.5 and 3.7.
> Anthropic’s text editor tool is only available for Claude 3.5 Sonnet and Claude 3.7 Sonnet:
>
> - Claude 3.7 Sonnet: text_editor_20250124
> - Claude 3.5 Sonnet: text_editor_20241022

Fix use of text editor tool with Claude 3.5 Sonnet.

---

CHANGELOG.md
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/app/samples/sample-tools/SelectScorer.tsx

Two level score selection was not correctly selecting the correct scorer (when a score produces multiple values, the secondary selector would incorrectly always select the wrong score).

Fix score selection

---

src/inspect_ai/tool/_tools/_web_search/_web_search.py

Prior to #1817, `web_search` had a default value for `provider`. Despite writing backward compatibility code, I mistakenly removed the default value.
The default value is now `None`. This will allow old code to continue to build without error, and it will do runtime checks to see if it's likely that "google" was the intended provider.

Fix unintentional breaking change in `web_search` caused by removing a default value.

---

CHANGELOG.md
src/inspect_ai/_util/local_server.py

Use system to identify a free port.
Don't reserve it.
Closes  #1809
Connection to vllm server fails on MacOS from version 3.93.
Connection to vllm server succeeds on MacOS.
No
From the doc:
```
with socket.socket(socket.AF_INET, socket
```

Binding port reservation on MacOS

---

CHANGELOG.md
src/inspect_ai/model/_providers/azureai.py

Newer versions of vllm reject requests with tools or tool_choice if the server hasn't been started explicitly with the `--tool-call-parser` and  `--enable-auto-tool-choice` flags

AzureAI: Don't include `tools` or `tool_choice` in requests when emulating tool calling

---

CHANGELOG.md
src/inspect_ai/model/_providers/google.py

When a Google Gemini models that supports thinking is called via Vertex AI with `--reasoning-tokens 0`, this results in the following error:
```
ClientError: 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'Unable to submit request because Thinking_config.include_thoughts 
is only enabled when thinking is enabled.. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini', 
'status': 'INVALID_ARGUMENT'}}
``` 
You can reproduce this error using the following command:
```
inspect eval examples/hello_world.py --model google/vertex/gemini-2.5-flash-preview-04-17 --reasoning-tokens 0
```
When `--reasoning-tokens 0` is passed, we explicitly disable thinking in a way that does not result in an error. Running the command above no longer results in an …

Disable Gemini reasoning when reasoning_tokens is set to zero

---

src/inspect_ai/_eval/run.py
tests/test_sample_id.py

#1865 broke passing sample_ids with a task prefix (i.e. `sample_id=task:sample` from #1782)
When setting up the sandboxes in `eval_run()`, `startup_sandbox_environments()` passes the unresolved sample_ids to slice_dataset, which breaks it. I guess the sandbox might have gotten empty sample_ids when using sample_id task prefixes earlier as well, but it didn't cause an error before.
You can use sample_ids with task prefixes again
No

Fix breakage of sample_id task prefix

---

docs/errors-and-limits.qmd
src/inspect_ai/agent/_run.py
src/inspect_ai/log/_log.py
src/inspect_ai/util/__init__.py
src/inspect_ai/util/_limit.py
tests/agent/test_agent_execute.py
tests/util/test_limit.py
tests/util/test_limit_message.py
tests/util/test_limit_token.py

Based on JJ and I's discussions with UK AISI's elicitation team.
- `apply_limits()` can optionally catch just its own limit errors (but let others propagate)
- `run()` overload to return a `LimitExceededError` (if one was raised) and most recent `AgentState`
- refactor of `_limits` (this will help reduce repetition with upcoming time & working limits)
- can no longer re-use an instance of a `Limit` ctx manager (this will also be helpful when we come implement querying of how much of a resource you've used)
- The `run()` overload has a new return type, and the `limits` parameter is now keyword-only (not positional). This only affects users who are passing a non-empty `limits` list to `run()`.
This builds upon the initial scoped limits work from #1737

Scoped limits improvements

---

CHANGELOG.md
docs/parallelism.qmd
docs/reasoning.qmd
src/inspect_ai/_util/_async.py
src/inspect_ai/model/_providers/providers.py
tests/model/providers/test_google.py
tests/model/test_api_key.py
tests/model/test_structured_output.py
tests/tools/test_tool_images.py
tests/tools/test_tool_types.py
tests/tools/test_tools.py
tests/util/test_images.py
tests/util/test_media.py

Includes support for reasoning summaries and is now compatible with the trio async backend

Google: Updated required version of `google-genai` to 1.16.1

---

CHANGELOG.md
src/inspect_ai/_eval/run.py

`run_multiple` will return tasks in the order they finish.
`run_multiple` will return tasks in the order they are passed in
No

Fix task return order in `run_multiple`

---

src/inspect_ai/log/_bundle.py

Fixes #1904
When `inspect view bundle` copies log files from the input directory to the output directory, it changes their relative mtime-ordering. This has the effect of scrambling the ordering of experiments in the sidebar in certain (maybe unusual!) conditions. See #1904 for a full description.
The relative mtime-ordering is now preserved.

inspect view bundle: preserve mtime-ordering in the output log directory

---

.github/workflows/log_viewer.yml
requirements.txt
src/inspect_ai/_view/schema.py

The new job introduced with #1897, failed for any PR that actually changed the schema. cc @tbroadley 
- Properly sets the working directory before doing `yarn install`
- `schema.py` now properly checks the subprocess result results from the calls to `json2ts` and `prettier`
- Bumps the required version of `pydantic` to avoid differences in the generated schema between local machines and GitHub (despite being within the same major version `pydantic` effectively made a breaking change causing generated schemas to differ).

Fix `check-schema-and-types` GitHub CI job.

---

src/inspect_ai/model/_openai_web_search.py
src/inspect_ai/tool/_tools/_web_search/_tavily.py
src/inspect_ai/tool/_tools/_web_search/_web_search.py
tests/model/providers/test_openai_web_search.py
tests/tools/test_web_search.py

Passing `None` for OpenAI internal web search params improperly raises an error.
`None` is now honored as the equivalent to `{}`

Add unit tests and bug fixes for passing None for OpenAI and Tavily web search parameters.

---

src/inspect_ai/model/_openai.py

`inspect eval biology_qa.py --model openai/mlx_community/Llama-3.1-8B-Instruct --model-base-url=http://10.0.0.100:8001/v1` 
which accesses local mlx server running on 10.0.0.100 like `python -m mlx_lm server --model mlx-community/Llama-3.1-8B-Instruct --host 0.0.0.0 --port 8001` 
crashed with
```
│ │ ❱  253 │   │   validated_self = self.__pydantic_validator__.validate_python(data, self_instance                      │                  │
│ │    254 │   │   if self is not validated_self:                                                                        │                  │
│ │    255 │   │   │   warnings.warn(                                                                                    │                  │
│ │    256 │   │   │   │   'A custom validator is returning a value other …
```

Fix to make inspect ai mlx compatible

---

src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/client/api/api-browser.ts
src/inspect_ai/_view/www/src/state/samplePolling.ts
src/inspect_ai/_view/www/src/utils/attachments.ts

Add an optional handler to deal with attachments that fail to resolve. Add a sample polling handler that will log polling state to the console as a warning when this happens.

Attachment warning

---

CHANGELOG.md
src/inspect_ai/_display/core/config.py
src/inspect_ai/_display/rich/display.py
src/inspect_ai/_util/text.py

- collapse dicts
- limit individual values to 50 chars
- limit overall output to 500 chars

truncate task config to prevent overflow

---

CHANGELOG.md
src/inspect_ai/model/_providers/azureai.py

Addresses #1813 
Right now, the Mistral provider has this behavior included, however the Azure provider (necessary for Azure Mistral inference recently, there has been some regression) does not have the behaviour. 
For Mistral models, we perform folding of user messages into tool messages when there is a user message immediately following the tool message.
This should not introduce a breaking change.
1. Install my local modified copy of Inspect
2. Rerun my test eval (below) to see that it no longer breaks the provider.
3. Verify that reverting to the PyPI inspect causes the breakage again.
```python
from inspect_ai import Task, task
from inspect_ai.dataset import Sample
from inspect_ai.scorer import includes
from inspect_ai.solver import basic_agent
from inspect_ai.tool import Tool, tool …
```

Backport Mistral message folding behavior into Azure provider

---

src/inspect_ai/tool/_tools/_web_search/_web_search.py
tests/tools/test_web_search.py

Recent updates (#1838) to `web_search` erroneously assumed that it could use a backward compatibility strategy that would induce static analysis (e.g. `mypy`) errors but still function properly at runtime. With this in mind, the new `providers` parameter was required.
Not only did old code that failed to pass `providers` induce `mypy` errors as expected, the code also failed at runtime.
This approach was based on a misunderstanding of how much runtime validation Python does when making function calls. The assumption was that it was like JavaScript - making no checks. In fact, Python uses introspection to ensure that something is passed for all required arguments.
Despite being semantically required, the new `providers` argument is now actually optional.
This PR adds a suit of unit tests …

Fix `web_search` backward compatibility issue by making new "required" parameter optional.

---

CHANGELOG.md
src/inspect_ai/dataset/_sources/csv.py
src/inspect_ai/dataset/_sources/hf.py
src/inspect_ai/dataset/_sources/json.py
src/inspect_ai/dataset/_util.py
tests/dataset/test_dataset.py
tests/dataset/test_dataset/samples-mcq.csv
tests/dataset/test_dataset/samples-mcq.json
tests/dataset/test_dataset/samples-mcq.jsonl

Passing `shuffle_choices=True` or `shuffle_choices=False` to `hf_dataset`, `json_dataset`, or `csv_dataset` incorrectly interprets the boolean as an integer and uses it as a seed for the random number generator, which is not the intended behaviour.
Fixes #1921 
Passing `shuffle_choices=False` does not shuffle choices, and passing `shuffle_choices=True` shuffles choices without setting a seed value i.e. produces a different result each time.
No breaking changes, but any datasets constructed with `shuffle_choices=True` will now have differently-ordered choices on each run, which is the intended behaviour.
-

Fix handing of shuffle_choices parameter

---

CHANGELOG.md
src/inspect_ai/scorer/_reducer/reducer.py
tests/scorer/test_reducers.py

I reviewed inspect_evals usage of the pass_at reducer and each example will continue to report correct scores (they’re all using Correct/Incorrect with threshold of 1). This would be a breaking change for users who pass a threshhold expecting it to be an exact match, but I think that is a bug since threshhold implies a minimum rather than an exact value.
This would be a breaking change for users who pass a threshhold expecting it to be an exact match, but I think that is a bug since threshhold implies a minimum rather than an exact value. I doubt users are relying upon that behavior.

Treat threshold as inclusive minimum

---

CHANGELOG.md
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/app/routing/navigationHooks.ts
src/inspect_ai/_view/www/src/app/samples/list/SampleList.tsx

Rather than relying up index based selection which is prone to state mismatch, just select directly using the id and epoch, which are in hand anyhow.

Make sample selection explicit

---

src/inspect_tool_support/CHANGELOG.md
src/inspect_tool_support/pyproject.toml
src/inspect_tool_support/src/inspect_tool_support/_remote_tools/_web_browser/accessibility_tree_node.py

Addresses #1964
The accessibility information made available to models for comboboxes does not include the currently selected value in the combobox. After selecting an item from the combobox, this accessibility tree info looks like:
`[11] combobox  [invalid: false, focusable: True, focused: True, hasPopup: menu, expanded]`
The currently selected value is included. Here is what the accessibility tree node for the combobox looks like now.
`[11] combobox Current input: \"February\"  [invalid: false, focusable: True, focused: True, hasPopup: menu, expanded]`

Fix combobox's missing current value from accessibility tree.

---

CHANGELOG.md
src/inspect_ai/agent/_handoff.py
src/inspect_ai/model/_call_tools.py
tests/agent/test_agent_execute.py

Thanks to Charles for spotting this.
Limit context managers do not support being re-used. However, we store the limits passed to `handoff()` in `AgentTool` which can be reused across multiple calls to `agent_handoff()`.
I now take a copy of the limit instances in `agent_handoff()`, and clearly document that the limits passed to `handoff()` are per handoff (i.e. not per handoff definition). By this I mean that if you define `handoff(..., limits=[token_limit(500)])`, you get 500 tokens _each time_ you call the tool.
Added a test which failed before these changes.

Fix: handoff limits when agent handed off to multiple times

---

CHANGELOG.md
src/inspect_ai/util/_subprocess.py
tests/util/test_subprocess.py

This fixes an occasional issue which was primarily observed when executing commands in Docker sandboxes. This issue exists with _any_ call to `inspect_ai.util.subprocess` which:
* has a timeout parameter which is hit
* produces large amounts of stdout/stderr (e.g. `cat large_file.txt`) [regardless of whether the `output_limit` is hit]
* is using asyncio as the anyio backend
The call to `await process.aclose()` within the `finally` block of `subprocess().run_command()` was deadlocking because the child process produced so much output that it was blocking on the OS pipe buffer accepting more data, but we were no longer attempting to read any of this data from stdout or stderr (because we'd cancelled the reading of the streams).
The `finally` block of `run_command()` calls `process.aclose()` …

Fix occasional subprocess deadlock (timeout + large output)

---

CHANGELOG.md
src/inspect_ai/agent/_react.py

If you pass in a string to the react prompt which has some curly brackets in it, an error is thrown when the react code tries to format it as an fstring.
```
│ /home/ubuntu/control-arena/control_arena/control_solver.py:46 in solve                                               │
│                                                                                                                      │
│   43 │   │   state.tools = tools(state)                                                                              │
│   44 │   │   protocol = protocol_builder(state.metadata_as(ControlTaskMetadata))                                     │
│   45 │   │                                                                                                           │
│ > 46 │   │   agent = react( …
```

Bug: Don't try to format all prompts in react agent

---

CHANGELOG.md
src/inspect_ai/_eval/task/run.py

Rather than inspecting the event stream to try to sniff out the limit that terminates the sample, this will instead directly capture the limit when the exception is handled.

Capture Sample Limit Directly

---

src/inspect_ai/model/_providers/groq.py

The `executed_tools` field in groq api cannot be accessed as it doesn't exist in the inspect ai structure. This causes the metadata to be missing or potentially throw errors when the field is accessed for evaluation.  [Groq `executed_tools` Documentation](https://console.groq.com/docs/agentic-tooling#executed-tools)
Correctly extract `executed_tools` from where it actually exists in the Groq API response.
No, this is a bug fix that ensures the `executed_tools` metadata is properly captured without breaking existing functionality.

add executed_tools from Groq api

---

CHANGELOG.md
docs/tools-standard.qmd
src/inspect_ai/model/_providers/groq.py
src/inspect_ai/model/_providers/perplexity.py
src/inspect_ai/tool/_tools/_web_search/_web_search.py
tests/model/providers/test_perplexity.py

- [ X ] New features
Perplexity is a provider but is not configurable with the web search tool
Perplexity is configurable with the web search tool, like other "native" provider search tools
No
Resolves https://github.com/UKGovernmentBEIS/inspect_ai/issues/1975

Perplexity configurable with web search tool

---

CHANGELOG.md
src/inspect_ai/agent/_react.py
tests/agent/test_agent_react.py

React agent removes tool calls to the submit tool. Depending on the model, this can leave reasoning content item that lead to the tool call dangling. OpenAI really doesn't like that.
See discussion [here](https://inspectcommunity.slack.com/archives/C0805HJTK8U/p1750338183162969).
We remove reasoning content items from `ChatMessageAssistant`'s from which we removed the `submit` tool call.

Remove correlated reasoning content items when removing submit tool calls from ChatMessageAssistant's in multi-agent scenarios.

---

CHANGELOG.md
src/inspect_ai/_eval/run.py

When the user cancels an eval (via Ctrl-C), sandbox cleanup code is no longer executed.
#2025 introduced a new task group when executing an eval. An AnyIO task group carries with it a `CancelScope`. When a task group has been cancelled, the cancellation is propagated _down_ to all child task groups. This includes any new task group that is create. It will immediately be cancelled. Beyond that, any _wait_ done in the context of a cancelled task group will induced a `CancelledError` exception.
Sandbox cleanup must be done even if the user has used Ctrl-C. Because of the behavior described above, the cleanup is immediately terminated.
AnyIO provides an affordance for altering the behavior described above. An inner `CancelScope` can be created with `shield=True`. This causes code that waits …

Shield critical shutdown code from cancel scope.

---

CHANGELOG.md
docs/agent-custom.qmd
docs/reference/_sidebar.yml
docs/reference/inspect_ai.scorer.qmd
docs/tools-custom.qmd

- `store_as` examples don't work as expected. Python doesn't regenerate the value of argument defaults each time the function is called. Therefore, each sample gets the same `instance` UUID.
- `inspect_ai.scorer.score` isn't documented
This PR:
- Changes the `store_as` examples to generate new `instance` values for each `web_surfer` invocation
- Adds `inspect_ai.scorer.score` to the docs
No.
N/A

Fix `store_as` examples, document `inspect_ai.scorer.score`

---

CHANGELOG.md
docs/agent-custom.qmd
docs/tools-custom.qmd
src/inspect_ai/tool/_tools/_bash_session.py
src/inspect_ai/tool/_tools/_web_browser/_web_browser.py

indicate that you must pass an `instance` explicitly to get distinct processes

correct `instance` docs for `web_browser()` and `bash_session()` 

---

CHANGELOG.md
src/inspect_ai/model/_providers/mistral.py
src/inspect_ai/model/_providers/providers.py

This PR updates the Mistral provider to align with breaking changes in mistralai v1.9.1 by bumping the minimum supported version and adding support for the new FileChunk type in content chunk handling.

Conform to Mistral breaking change.

---

src/inspect_ai/hooks/_hooks.py
tests/hooks/test_hooks.py

I was incorrectly returning the instance rather than the class. This meant that if you did
``` py
@hooks(...)
class MyHooks(Hooks):
pass
instance = MyHooks()
```

Return `hook_type` (i.e. class) rather than instance from decorator wrapper

---

src/inspect_ai/hooks/_startup.py
tests/hooks/test_hooks.py

Motivation: Certain orgs like UK AISI want to configure researcher machines in such a way that Inspect will verify that certain [hooks](https://inspect.aisi.org.uk/extensions.html#hooks) are installed. Otherwise, it is very easy for a user to forget to install custom hooks in their environment (especially when working in public repos like inspect_evals).
E.g.
```
INSPECT_REQUIRED_HOOKS=aisitools/aisitools
```
Note that hooks are automatically namespaced by their package (part of the Inspect registry name).
Migration note:
For orgs where env vars are set on developer VMs, once we set this env var, users on this new version of Inspect but an old version of the plugin will see this error. They can resolve by simply upgrading the version of the plugin. We _could_ decide to only verify …

Add support for `INSPECT_REQUIRED_HOOKS`

---

src/inspect_ai/_cli/eval.py
src/inspect_ai/_cli/util.py

```
(modelscan-inspect) metr/modelscan-inspect » inspect eval modelscan/scan_malt --model anthropic/claude-sonnet-4-20250514,anthropic/claude-3-5-haiku-20241022,anthropic/claude-3-5-sonnet-20241022 --epochs 5 --batch 300 -T job_name=reward_hacking --temperature 1 --max-tokens 1000 --log-level info                                                                                                                                                                                        
Traceback (most recent call last):
File "/Users/neev/repos/metr/modelscan-inspect/.venv/bin/inspect", line 10, in <module>
sys.exit(main())
~~~~^^
File "/Users/neev/repos/metr/modelscan-inspect/.venv/lib/python3.13/site-packages/inspect_ai/_cli/main.py", line 56, in main
inspect(auto_envvar_prefix="INSPECT")  # …
```

fix: return str instead of raising

---

CHANGELOG.md
src/inspect_ai/_view/www/dist/assets/index.js
src/inspect_ai/_view/www/src/client/remote/remoteZipFile.ts

HEAD requests may be fulfilled using compression and this results in a compressed file size rather than an uncompressed file size which is needed for downstream range requests. (accept-encoding is also a way to control this, but the browser controls this, so we can’t set it for the HEAD request).
The downside of this approach is an extra range request (for 1 byte) which will always do if ranges are allowed (before falling back to HEAD requests).
GitHub Pages is the first static deployment target that we've run across that is performing this compression of the eval files. This fix will fix http 416 errors when a bundled viewer is served from gh-pages.  __Note that any published viewer bundles will need to be regenerated using `inspect view bundle` after this fix is merged and redeployed to …

Prefer range request to determine eval file size (gh-pages view bundle support)

---

src/inspect_ai/tool/_tools/_bash_session.py
src/inspect_ai/tool/_tools/_text_editor.py
src/inspect_tool_support/Dockerfile.dev
src/inspect_tool_support/README.md
src/inspect_tool_support/src/inspect_tool_support/_cli/main.py
src/inspect_tool_support/unreleased_changes/+718f270e.minor.md
tests/conftest.py
tests/tools/test_inspect_tool_support.from_source.yaml
tests/tools/test_inspect_tool_support.py

These two tools always run as a sandbox's default user, and cannot be configured differently. The existing `user` argument for the `text_editor` tool is simply ignored while the `bash_session` tool does not expose this argument.
FIXES #2005 
FIXES #2006 
The specified username in these tools will be passed through to the sandbox exec call. This PR also adds some test (and improves how `inspect_tool_support` can be tested).
When using inspect with these changes and the updated version of inspect_tool_support, these tools will run as the specified user. If either package is outdated, the username will continue to be ignored.
| Inspect_ai version    | Inspect_tool_support version | result |
| -------- | ------- | ------- |
| New | New | Username can be set, tools run as specified user |
| …

Support username with `bash_session` and `text_editor` tools

---

src/inspect_ai/log/_recorders/buffer/database.py

Database cleanup code failed to located database files in subdirectories.
This PR fixes a bug where database cleanup code didn’t locate files in subdirectories by switching from `glob` to `rglob` and adds logic to remove empty directories after deleting a database file.
- Switched to recursive searches in running_tasks and cleanup_sample_buffer_databases.
- Added removal of parent directories when they become empty in cleanup_sample_buffer_db.

Fix bug that failed to find sample db files.

---

docs/_model-providers.md
docs/index.qmd
docs/providers.qmd
pyproject.toml
src/inspect_ai/model/_providers/providers.py
src/inspect_ai/model/_providers/transformer_lens.py
tests/model/providers/test_transformer_lens.py
tests/test_helpers/utils.py
uv.lock

Inspect does not support TransformerLens models for mechanistic interpretability research.
Adds TransformerLens provider allowing users to:
- Load HookedTransformer models with interpretability hooks
- Use them in Inspect evaluations via tl_model argument
- Access internal activations for mechanistic interpretability
No - this is purely additive. No existing functionality is changed.
- Includes a test suite (6 test functions)
- Full documentation in providers.qmd
- Built-in tests (and linters) pass on my machine with the exception of the unrelated mistral import issue.

Transformer lens integration

---

docs/tools-standard.qmd

Text editor tool links to computer use tool
Links to text editor tool

Fix link in tools-standard.qmd

---

src/inspect_ai/model/_model.py

If you mystype a model name, the error message is confusing
`ValueError: Model name {model}{from_api} not recognized.`
The actual error is in the from_api part. The name of the model is irrelevant.
`ValueError: Model API openapi of model 'openapi/o3-mini' not recognized.`
No

Improve missing Model API error nessage

---

src/inspect_ai/log/_convert.py

Conversion tries to use filesystem of input file for output path, causing errors
Don't do that

Fix incorrect filesystem in convert

---

docs/extensions.qmd

The code in doesn't work because [`SampleEnd`](https://inspect.aisi.org.uk/reference/inspect_ai.hooks.html#sampleend
) doesn't have `summary` field.
It works now.
No.

Fix typo in WBHooks.on_sample_end sample code

---

CHANGELOG.md
src/inspect_ai/_view/www/src/app/samples/transcript/ModelEventView.tsx
src/inspect_ai/_view/www/src/app/samples/transcript/TranscriptVirtualList.tsx
src/inspect_ai/_view/www/src/app/samples/transcript/TranscriptVirtualListComponent.tsx

We currently don't render tool calls in model events (transcript) b/c we're relying upon the next event being a tool event (and that rendering the tool call). This will look ahead to the next event and render the tool call if the next event isn't a tool event.

Render tool call if next event isn’t tool event

---

src/inspect_ai/analysis/beta/_prepare/frontier.py

Before this change, the frontier operation would process task/models with the same release date sequentially, which means that more than one model could be marked as a frontier for the same release date. This change will only keep the highest score for a given date, resulting in only the model with the highest score on a date being marked as the frontier.

Improve frontier operation

---

CHANGELOG.md
src/inspect_ai/model/_openai_responses.py

Some OpenAI reasoning models return multiple consecutive `reasoning` items in a row. Our current `_filter_consecutive_reasoning_blocks` drops all but the first in each consecutive run. This leads to `400` errors from OpenAI when we play that back to them.
`_filter_consecutive_reasoning_blocks` has been updated to drop all but the _last_ reasoning item instead, and that fixed the bug.
Note that we're updating a heuristic work-around of an issue with the OpenAI API. Though unlikely, it's possible that, in some cases, this fix will break previously functioning scenarios.

Update workaround of OpenAI reasoning issue to retain only the last (rather than the first) in a run of consecutive reasoning items.

---

CHANGELOG.md
src/inspect_ai/_view/server.py

When calling `inspect view --log-dir=s3://...` with a large eval set log, the session gets closed too early resulting in this error:
```
$ uv run inspect view --log-dir=s3://...
======== Running on http://127.0.0.1:7575 ========
(Press CTRL+C to quit)
[07/29/25 14:05:28] ERROR    Error handling request from 127.0.0.1                                                                                                   web_protocol.py:451
Traceback (most recent call last):                                                                                                                         
File "/home/faber/src/metr/inspect-action/.venv/lib/python3.13/site-packages/aiobotocore/httpsession.py", line 222, in send                              
response = await session.request( …
```

Do not use instance cache for S3FileSystem in the async_filesystem context manager

---

CHANGELOG.md
src/inspect_ai/util/_sandbox/self_check.py

Sandbox tests don't check env vars are passed correctly
I added another test to the self_check suite
It might break people's tests if they have written a custom sandbox that violates the spec, but that would be a good outcome

Add sandbox test for env vars

---

CHANGELOG.md
docs/_sandbox-dockerfile.md
src/inspect_tool_support/Dockerfile

The current Dockerfile installed `inspect-tool-support` using `pipx` with default settings, which placed the installation in `/root/.local/bin`. This caused permission issues when the Docker container was used by non-root users, as they couldn't access the tools installed in the root user's private directory.
Solution
- **Relocate installation**: Use custom `PIPX_HOME`, `PIPX_BIN_DIR`, and `PIPX_VENV_DIR` environment variables to install `inspect-tool-support` in `/opt/inspect/` instead of `/root/.local/`
- **Set proper permissions**: Add `chmod -R 755 /opt/inspect` to ensure all users can read and execute the installed tools
- **Update PATH**: Change the `PATH` environment variable to point to the shared `/opt/inspect/bin` directory

Update `inspect-tool-support` dockerfile to allow use by all users.

---

CHANGELOG.md
src/inspect_ai/tool/_tools/_execute.py

Sometimes models call functions with incorrect argument types. (This is particularly notable in the newly-released gpt-oss, which has a strong tendency to pass a list of strings rather than a single string to the bash command.)
The actual function call logic handles this gracefully by returning a string describing the argument parsing error, so the model can correct it.
But the viewer was crashing when the argument type was incorrect. Instead of crashing, it now converts whatever it gets to a string using `str`.
When a model calls `bash` or `python` with an incorrect type for the `cmd` argument (eg `cmd=["echo", "hello", "world"]` rather than `cmd="echo hello world"`), the code viewer crashes.
Instead of crashing, the code viewer renders the argument as a string.

code_viewer: handle non-string arguments

---

CHANGELOG.md
src/inspect_ai/solver/_multiple_choice.py
tests/solver/test_multiple_choice.py

My attempt at fixing https://github.com/UKGovernmentBEIS/inspect_ai/issues/2216. 
The `parse_answers` function is now much stricter. It only parses out answers that are actually valid choices, instead of any character in `[A-Za-z\d ,]`. It now takes in `multiple_correct`, and allows only one answer if it's False. It now returns the parsed answers as `set[str]`.
(I also now allow the answer line to end in a full stop like, `ANSWER: A, B.`, which is more permissive than the previous behaviour. Previously we didn't catch such answers at all).
Full backward compatibility would require preserving the bug, which seems like a shame. I can't think of a reason anyone would be relying on it. If full backward compatibility is desired, I can put this behaviour behind a flag that defaults to False.

Fix bug in multiple_choice solver answer parsing (#2216)

---

src/inspect_ai/model/_providers/google.py

Most (perhaps all) other model provider API URLs can be overridden both through arguments and through environment variables, but there is no environment variable for overriding the Google Vertex API URL.
The Vertex base API URL can be overridden using `VERTEX_BASE_URI`.
No

Option to override Vertex base uri with environment variable

---

src/inspect_ai/model/_providers/openai.py
src/inspect_ai/model/_providers/openai_completions.py
src/inspect_ai/model/_providers/openai_responses.py

The functionality of the user field has been deprecated and split into two arguments. safety_identifier is used for additional safeguards. prompt_cache_key is used for enhanced caching. See: https://platform.openai.com/docs/api-reference/responses/create#responses_create-user

Replace deprecated user with safety_identifier and prompt_cache_key

---

CHANGELOG.md
src/inspect_ai/agent/_bridge/patch.py
src/inspect_ai/model/_openai.py
src/inspect_ai/model/_providers/providers.py

OpenAI introduced a new type of tool call named "custom". This caused breaking changes in the API. This PR does not add support for custom tools, but it does update the typing to conform to the changes.
Roughly speaking, `ChatCompletionMessageToolCall` became a union of `ChatCompletionMessageFunctionToolCall | ChatCompletionMessageCustomToolCall`

Conform to OpenAI SDK 1.99.2 breaking changes.

---

CHANGELOG.md
src/inspect_ai/model/_openai_responses.py
src/inspect_ai/model/_providers/_openai_web_search.py

- Enable native `web_search()` tool for GPT-5.
- Convert "web_search" tool choice to native "web_search_preview" type.

improvements for openai web search tool

---

CHANGELOG.md
src/inspect_ai/_view/www/src/app/content/RecordTree.tsx
src/inspect_ai/_view/www/src/app/samples/chat/ChatMessage.tsx
src/inspect_ai/_view/www/src/app/samples/transcript/ScoreEventView.tsx
src/inspect_ai/_view/www/src/app/samples/transcript/SpanEventView.tsx

Fixes #2249
There were a number of issues conspiring together to cause horrible perf and viewer crashes. There is no issue related to sandbox events, all related to Metadata. Specifically:
- Score event was rendering with a non-virtualized metadata viewer. Switch to visualized viewer.
- RecordTree (the virtualized metadata viewer) had a _very_ inefficient implementation of computing collapsed state which results in tons of objects copies.
- RecordTree would attempt to render all items while is computed collapsed state of items.
These together conspired to terrible perf.

Improve Handling of Large / Complex Message or Score Metadata

---

CHANGELOG.md
src/inspect_ai/scorer/_reducer/reducer.py
tests/scorer/test_reducers.py

NaN values will now be skipped when reducing epochs.
Related: #2104

Skip `NaN` values when reducing

---

src/inspect_tool_support/.bumpversion.cfg
src/inspect_tool_support/CHANGELOG.md
src/inspect_tool_support/README.md
src/inspect_tool_support/pyproject.toml
src/inspect_tool_support/unreleased_changes/+c67d647a.minor.md

Bump inspect-tool-support version: 1.1.2 → 1.2.0

---

tests/agent/test_agent_handoff.py
tests/conftest.py
tests/model/test_model_roles.py
tests/model/test_reasoning_google.py

- `test_google_reasoning` failed improperly on occasion because of a lack of flexibility in result assertions.
- Marked some agent handoff tests as flaky.

Address flakiness in slow tests.

---

CHANGELOG.md
src/inspect_ai/_util/text.py
tests/util/test_str_to_float.py

Ignores trailing characters that are invalid for floats

string to float conversion now extracts the first valid float from the string

---

src/inspect_ai/_view/www/dist/assets/index.css
src/inspect_ai/_view/www/src/app/appearance/icons.ts
src/inspect_ai/_view/www/src/app/samples/chat/MessageContent.tsx
src/inspect_ai/_view/www/src/app/samples/chat/documents/ContentDocumentView.module.css
src/inspect_ai/_view/www/src/app/samples/chat/documents/ContentDocumentView.tsx
src/inspect_ai/_view/www/src/client/api/api-shared.ts
src/inspect_ai/_view/www/src/utils/mime.ts

We have special handling for images (which show a small version of the image) otherwise all others files show filename and link.
Files are downloadable outside of VSCode.

Render document types

---

src/inspect_ai/_eval/evalset.py

When running with display=plain or display=log the message about waiting for retry was not displayed.
The message is now displayed.
No.
I thought about adding a `status_message` method to the `Display` class, but decided that it was too much for something that is only used in one place.

Show the waiting for retry message when using display=plain or display=log

---

CHANGELOG.md
src/inspect_ai/_view/www/src/app/samples/descriptor/score/ListScoreDescriptor.tsx
src/inspect_ai/_view/www/src/app/samples/descriptor/score/ObjectScoreDescriptor.tsx
src/inspect_ai/_view/www/src/app/samples/descriptor/score/ScoreDescriptor.tsx
src/inspect_ai/_view/www/src/app/samples/descriptor/types.ts
src/inspect_ai/_view/www/src/app/samples/sample-tools/filters.ts
src/inspect_ai/_view/www/src/constants.ts

- list scores will be displayed, but are not filterable.
- existing object scores are now properly not filterable.

Properly support list score display

---

.devcontainer/Dockerfile
.pre-commit-config.yaml
uv.lock

I noticed that the devcontainer wouldn't build anymore. Just needed to run `uv lock`. Added a pre-commit hook to keep it from happening again. Also was able to simplify the dockerfile a bit, looks like newer version of either uv of quarto-cli doesn't need the build workaround anymore.

Re-lock uv, fix devcontainer

---

CHANGELOG.md
src/inspect_ai/_util/citation.py
src/inspect_ai/_view/www/log-schema.json

OpenAPI schemas generated from Inspect types are not valid since #1919. 
We had a `json_schema_extra` in that class to ensure that it retained the proper typing when making its way to TypeScript. The issue was we were using some non-compliant functionality. Specifically,`additionalItems: False` is deprecated in JSON Schema Draft 2020-12 (which OpenAPI 3.1.0 uses).
The fix is to use `"items": {"type": "integer"}` instead of the tuple-style array schema, while keeping the `minItems: 2` and `maxItems: 2` constraints to ensure exactly 2 integers are required.

Fix json schema generation of CitationBase.

---

src/inspect_ai/_view/www/src/app/samples/list/SampleList.tsx
src/inspect_ai/_view/www/src/app/samples/list/SampleRow.tsx

vscode doesn’t support navigating urls so we need to support old school click handling for this case.

Fix broken viewer navigation in vscode

---

CHANGELOG.md
src/inspect_ai/_cli/eval.py
src/inspect_ai/_eval/evalset.py
tests/test_eval_set.py
tests/test_eval_set/2024-08-29T15-11-17+00-00_popularity_5EAmX6wjMFqea6WY7XHzZp.json
tests/test_eval_set/2024-08-29T15-11-18+00-00_popularity_5EAmX6wjMFqea6WY7XHzZp.json

When changing the included tasks in an eval-set, you cannot rerun it in the same `log_dir`. If you want to reuse some of the successful earlier runs, you need to manually copy them.
This PR adds a new `--log-dir-allow-dirty` flag, that allows you to run the eval set in a `log_dir` with eval-files from earlier runs that are no longer in the eval set (or from a completely different run).
No
[Slack thread](https://inspectcommunity.slack.com/archives/C080K7SQ4SG/p1755545184752159)

Allow dirty log_dir during eval_set

---

CHANGELOG.md
src/inspect_ai/_view/www/src/client/remote/remoteLogFile.ts

I hven’t yet tried a sample of this size, but this will double our current limit.
- It started at 10MB
- then was raised to 50MB
- this raises it to 100MB
My guess is that 100MB will be ok and we’ll see degraded perf north of that. Still, I’d like to explore raising this further - we may now have done enough optimization that the slow deserialization could be an ok experience (e.g. background worker deserialization).

Increase sample size limit to 100MB

---

src/inspect_ai/_cli/eval.py
src/inspect_ai/_display/core/config.py

You may pass the `--no-epochs-reducer` arg to not use any reductions.
For example:
`inspect eval examples/popularity.py --epochs 3 --no-epochs-reducer`

Add CLI support for epochs-reducer None

---

docs/eval-logs.qmd

Correct documentation for `read_eval_log()` with note regarding `reductions` being present in `eval` formatted log files.
- [] Bug fixes

Tweak read_eval_log() docs

---

src/inspect_ai/_view/www/src/app/samples/transcript/TranscriptFilter.tsx
src/inspect_ai/_view/www/src/app/samples/transcript/TranscriptPanel.tsx
src/inspect_ai/_view/www/src/app/samples/transcript/hooks.ts
src/inspect_ai/_view/www/src/app/types.ts
src/inspect_ai/_view/www/src/state/sampleSlice.ts

Restoring the viewer from the backgrounding vscode will result in an error.
There is no error

Fix event filtering error when restoring from the background in vscode

---

docs/multimodal.qmd

Very small fix. There was just a typo in the documentation about how to use ContentDocument.

Fix ContentDocument typo in documentation.

---

src/inspect_ai/_view/www/src/app/log-view/tabs/SamplesTab.tsx
src/inspect_ai/_view/www/src/app/samples/list/SampleRow.tsx

The fix to screen sample list content out of the DOM caused a regression where sample state (e.g. scroll position, selection) would be list since the view was being completed unloaded and reloaded.
As a simple workaround for the time being, this moves the screening of content lower into the row rendering, allowing the list to preserve its state exactly.

Preserve sample state

---

CHANGELOG.md
src/inspect_ai/agent/_bridge/bridge.py
src/inspect_ai/agent/_bridge/sandbox/bridge.py

enables preservation of messages when agent is run via `as_solver()`

agent bridge: respect reference vs. value semantics of agent caller

---

CHANGELOG.md
src/inspect_ai/agent/_bridge/responses_impl.py
src/inspect_ai/model/_openai_responses.py
src/inspect_ai/model/_providers/_openai_web_search.py
src/inspect_ai/model/_providers/providers.py
tests/agent/test_agent_bridge.py
tests/model/providers/test_openai_web_search.py

OpenAI deployed a breaking change by changing `.action.type == "find"` to `.action.type == "find_in_page"`. They did not, however, update their client SDK to match that server change.
Conformed to the change.

Update OpenAI SDK and work around "find_in_page" breaking change.

---

CHANGELOG.md
src/inspect_ai/model/_providers/groq.py

Models provided by Groq ignore the --reasoning-effort flag.
reasoning_effort for supported Groq models (groq/openai/gpt-oss-20b and groq/openai/gpt-oss-120b) can now be specified with the --reasoning-effort flag. Groq models that do not support reasoning_effort, yet provided with the --reasoning-effort flag, will simply throw a 400 error.
No

feat: support for reasoning_effort with groq

---

src/inspect_ai/model/_openai_responses.py

OpenAI chokes when Inspect plays back a `web_search_call` like this:
```json
{
"id": "ws_68b836b34c708194a7905f8a97b9ecd10c44c6f42d3f5c79",
"action": {
"query": "How to submit answer using functions.submit tool in Inspect AI",
"type": "search",
"sources": null
},
"status": "completed",
"type": "web_search_call"
}
```
```python
BadRequestError('Error code: 400 - {\'error\': {\'message\': "Unknown parameter: 
\'input[8].action.sources\'.", \'type\': \'invalid_request_error\', \'param\': \'input[8].action.sources\', 
\'code\': \'unknown_parameter\'}}')
```
We strip the `None` so that a `null` will not show up in the json.

Omit `None`'s when creating ContentToolUse objects.

---

CHANGELOG.md
docs/_sandboxenv-interface.md
src/inspect_ai/agent/_bridge/sandbox/bridge.py
src/inspect_ai/util/_sandbox/docker/compose.py
src/inspect_ai/util/_sandbox/docker/docker.py
src/inspect_ai/util/_sandbox/environment.py
src/inspect_ai/util/_sandbox/events.py
src/inspect_ai/util/_sandbox/local.py
src/inspect_ai/util/_sandbox/service.py
src/inspect_ai/util/_subprocess.py
tests/test_package/inspect_package/sandboxenv/podman.py

use concurrency=False for long-running / cheap polling requests

add `concurrency` option to sandbox exec() method

---

src/inspect_ai/_cli/score.py
src/inspect_ai/_cli/util.py
src/inspect_ai/_eval/score.py
src/inspect_ai/_eval/task/run.py
src/inspect_ai/_util/_async.py
src/inspect_ai/log/_transcript.py
tests/_cli/test_score.py

You have to load the entire log file into memory in order to score it.
Samples can be streamed from the log file and into the output file, avoiding memory bottlenecks.
Nope! Backwards compatible

Streaming scoring

---

CHANGELOG.md
src/inspect_ai/_view/server.py
src/inspect_ai/_view/www/src/app/log-list/LogsPanel.tsx
src/inspect_ai/_view/www/src/app/routing/AppRouter.tsx

- The view server will check the log_dir to see whether it is a file. If it is, it will provide the proper info to the viewer when responding to the initial logs request (the single file and the log_dir).
- When launching a log viewer where there is only a single file in the log_dir, the viewer will initially load the log view directly, skipping the listing view.

Support viewing single files

---

src/inspect_ai/model/_providers/azureai.py

When not setting an API Key for the Azure AI provider, the `self.api_key` falls back to an empty string, thus passing the later `self.api_key is not None` check, failing to use Managed Identity (which will be tried when no api key can be found)
API key falls back to None, triggering the Managed Identity flow when needed

Fix API key being empty string, not None

---

CHANGELOG.md
src/inspect_ai/agent/_bridge/anthropic_api_impl.py
src/inspect_ai/agent/_bridge/completions.py
src/inspect_ai/agent/_bridge/responses_impl.py
src/inspect_ai/agent/_bridge/types.py

Automatically track agent state based on observing generations made through the bridge. We need to distinguish between the "main" thread of generation and various types of side / sub-agent calls to the model (e.g. claude code does bash path detection using a side call).
Our heuristic is to keep the number of messages that were in the _last_ generation, and to update the state whenever the total messages exceeds it. This should pick up normal agent loops that keep appending, while at the same time discarding side model calls that tend to be shorter. Finally, this should handle recovering from history compaction, which can shorten the message history considerably.

Agent bridge: enhance automatic state tracking

---

src/inspect_ai/model/_providers/bedrock.py

AWS Bedrock models with reasoning incorrectly raise a ValueError. The reasoningContent field is not implemented in bedrock.py, leading to the "else -> raise ValueError" conditional.
AWS Bedrock models with reasoning are now handled properly
No

feat(bedrock): add support for reasoning in bedrock provider

---

src/inspect_ai/tool/_sandbox_tools_utils/sandbox.py

without this we get the following when running tests:
```
/Users/jjallaire/ukinstitute/UKGovernmentBEIS/inspect_ai/src/inspect_ai/tool/_sandbox_tools_utils/sandbox.py:90:
DeprecationWarning: path is deprecated. Use files() instead. Refer to https://importlib-
resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
with resources.path("inspect_ai.binaries", executable) as executable_path:
```

prevent resources.path deprecation warning during tests

---

CHANGELOG.md
src/inspect_ai/model/_trim.py
tests/agent/test_agent_react.py

The react agent crashes if the model context window length is exceeded and truncation is set to `auto` (see #2505).
Truncation now behaves as expected.
No (fix should bring behavior in line with [documented behavior](https://inspect.aisi.org.uk/react-agent.html#truncation)).

Fix truncation of messages in react agent

---

CHANGELOG.md
src/inspect_ai/_eval/score.py
src/inspect_ai/_eval/task/log.py
src/inspect_ai/_eval/task/results.py
src/inspect_ai/_eval/task/run.py
src/inspect_ai/_eval/task/task.py
src/inspect_ai/_view/www/log-schema.json
src/inspect_ai/_view/www/src/@types/log.d.ts
src/inspect_ai/log/_log.py
src/inspect_ai/scorer/_metric.py

`Task.__init__()` cannot take a list that's a mix of `Metric` and `dict[str, list[Metric]]` values for the `metrics` param.
It can take a list that's a mix of `Metric` and `dict[str, list[Metric]]` values for the `metrics` param.
No.
There's a use case where it'd be useful to pass a list that's a mix of `Metric` and `dict[str, list[Metric]]` values.

change Task.metrics type

---

src/inspect_ai/agent/_bridge/responses_impl.py

function_call_output messages will always have a string value for `text` (either the message.text or an erorr message string if present).

Fix Build: Workaround Type Checker

---

CHANGELOG.md
src/inspect_ai/_view/www/src/app/routing/url.ts

We were dropping query params when forming urls for the clipboard

Preserve query params when copying links

---

CHANGELOG.md
requirements.txt
uv.lock

14.0.0 had this bug which was fixed in 14.1.0: https://github.com/Textualize/rich/issues/3682

allow any version of `rich` > 13.3.3 (save for 14.0.0)

---

src/inspect_ai/log/_convert.py
tests/log/test_convert.py

If you run `inspect log convert` with both `--resolve-attachments` (#2465) and `--stream` (#2496), `resolve_attachments` is ignored.
Attachments are resolved.
No.
Note that the unit test was "cheating": it resolved attachments while reading the log back in.

Fix resolve-attachments while log convert --stream

---

CHANGELOG.md
src/inspect_ai/model/_providers/anthropic.py

The anthropic `should_retry` [method](https://github.com/UKGovernmentBEIS/inspect_ai/blob/main/src/inspect_ai/model/_providers/anthropic.py#L506) isn't catching this exception:
```anthropic.APIStatusError: {'type': 'error', 'error': {'details': None, 'type': 'api_error', 'message': 'Internal server error'}, 'request_id': 'req_011CTnpKCE4RQY4wHWtsK2Bv'}```
This patch adds a check for "internal server error" in the error body (in addition to the existing "overloaded" check) to ensure these transient errors are properly retried.
No
N/A

Bugfix: retry on anthropic internal server errors
